import { useMemo, useState } from "react";
import { ArrowDown, ArrowUp, FolderPlus, Pencil, Plus, Save, Trash2, X } from "lucide-react";
import DashboardLayout from "@/components/DashboardLayout";
import { trpc } from "@/lib/trpc";
import { CatalogCategory, CatalogTool } from "@shared/catalog";

type CategoryForm = { id?: number; parentId: number | null; name: string; slug: string; description: string; icon: string; status: "active" | "inactive"; seoTitle: string; seoDescription: string };
const blankForm = (parentId: number | null = null): CategoryForm => ({ parentId, name: "", slug: "", description: "", icon: "FolderTree", status: "active", seoTitle: "", seoDescription: "" });

export default function AdminCategories() {
  const { data, isLoading, error } = trpc.catalog.adminSnapshot.useQuery();
  const utils = trpc.useUtils();
  const [form, setForm] = useState<CategoryForm | null>(null);
  const create = trpc.catalog.createCategory.useMutation({ onSuccess: () => { utils.catalog.adminSnapshot.invalidate(); utils.catalog.snapshot.invalidate(); setForm(null); } });
  const update = trpc.catalog.updateCategory.useMutation({ onSuccess: () => { utils.catalog.adminSnapshot.invalidate(); utils.catalog.snapshot.invalidate(); setForm(null); } });
  const remove = trpc.catalog.deleteCategory.useMutation({ onSuccess: () => { utils.catalog.adminSnapshot.invalidate(); utils.catalog.snapshot.invalidate(); } });
  const reorder = trpc.catalog.reorderCategory.useMutation({ onSuccess: () => { utils.catalog.adminSnapshot.invalidate(); utils.catalog.snapshot.invalidate(); } });
  const updateTool = trpc.catalog.updateTool.useMutation({ onSuccess: () => { utils.catalog.adminSnapshot.invalidate(); utils.catalog.snapshot.invalidate(); } });
  const categories = data?.categories ?? [];
  const rootCategories = useMemo(() => categories.filter((item) => item.parentId === null), [categories]);

  function startEdit(category: CatalogCategory) { setForm({ id: category.id, parentId: category.parentId, name: category.name, slug: category.slug, description: category.description ?? "", icon: category.icon ?? "", status: category.status === "inactive" ? "inactive" : "active", seoTitle: category.seoTitle ?? "", seoDescription: category.seoDescription ?? "" }); }
  function save() { if (!form) return; const values = { parentId: form.parentId, name: form.name, slug: form.slug.toLowerCase().replace(/[^a-z0-9-]/g, "-"), description: form.description || null, icon: form.icon || null, status: form.status, seoTitle: form.seoTitle || null, seoDescription: form.seoDescription || null }; if (form.id) update.mutate({ id: form.id, values }); else create.mutate(values); }
  return <DashboardLayout><div className="admin-catalog"><header><div><p className="eyebrow">ADMIN / CATALOG</p><h1>카테고리 및 인기 도구 관리</h1><p>대분류와 하위 카테고리, 홈페이지 인기 도구의 노출 여부·순서·검색 별칭을 관리합니다.</p></div><button className="admin-primary" onClick={() => setForm(blankForm())}><Plus size={18} />대분류 추가</button></header>{error ? <div className="admin-alert">관리자 권한이 필요합니다. 현재 로그인 계정의 역할을 관리자(admin)로 지정한 뒤 다시 시도하세요.</div> : isLoading ? <p>카테고리를 불러오는 중입니다.</p> : <><div className="admin-tree">{rootCategories.map((root) => <CategoryBranch key={root.id} category={root} depth={0} categories={categories} onEdit={startEdit} onAddChild={(id) => setForm(blankForm(id))} onDelete={(id) => remove.mutate({ id })} onMove={(id, direction) => reorder.mutate({ id, direction })} />)}</div><PopularTools tools={data?.tools ?? []} onUpdate={(id, values) => updateTool.mutate({ id, values })} busy={updateTool.isPending} /></>}{form && <CategoryEditor form={form} categories={categories} onChange={setForm} onCancel={() => setForm(null)} onSave={save} busy={create.isPending || update.isPending} />}</div></DashboardLayout>;
}

function CategoryBranch({ category, depth, categories, onEdit, onAddChild, onDelete, onMove }: { category: CatalogCategory; depth: number; categories: CatalogCategory[]; onEdit: (category: CatalogCategory) => void; onAddChild: (id: number) => void; onDelete: (id: number) => void; onMove: (id: number, direction: "up" | "down") => void }) {
  const children = categories.filter((item) => item.parentId === category.id);
  return <section><CategoryRow category={category} depth={depth} categories={categories} onEdit={onEdit} onAddChild={onAddChild} onDelete={onDelete} onMove={onMove} />{children.length > 0 && <div className="admin-children">{children.map((child) => <CategoryBranch key={child.id} category={child} depth={depth + 1} categories={categories} onEdit={onEdit} onAddChild={onAddChild} onDelete={onDelete} onMove={onMove} />)}</div>}</section>;
}

function CategoryRow({ category, depth, categories, onEdit, onAddChild, onDelete, onMove }: { category: CatalogCategory; depth: number; categories: CatalogCategory[]; onEdit: (category: CatalogCategory) => void; onAddChild: (id: number) => void; onDelete: (id: number) => void; onMove: (id: number, direction: "up" | "down") => void }) {
  const hasChildren = categories.some((item) => item.parentId === category.id);
  return <div className={`category-row depth-${depth}`}><div className="category-name"><span className={category.status === "active" ? "status-active" : "status-inactive"}>{category.status === "active" ? "공개" : "비공개"}</span><div><strong>{category.name}</strong><small>/{category.slug}</small><p>{category.description || "설명 없음"}</p></div></div><div className="category-actions"><button onClick={() => onMove(category.id, "up")} title="위로"><ArrowUp size={16} /></button><button onClick={() => onMove(category.id, "down")} title="아래로"><ArrowDown size={16} /></button><button onClick={() => onAddChild(category.id)} title="하위 카테고리 추가"><FolderPlus size={16} /></button><button onClick={() => onEdit(category)} title="수정"><Pencil size={16} /></button><button onClick={() => { if (!hasChildren && window.confirm(`'${category.name}' 카테고리를 삭제할까요?`)) onDelete(category.id); }} disabled={hasChildren} title={hasChildren ? "하위 카테고리가 있어 삭제할 수 없습니다." : "삭제"}><Trash2 size={16} /></button></div></div>;
}

function PopularTools({ tools, onUpdate, busy }: { tools: CatalogTool[]; onUpdate: (id: number, values: { isPopular?: boolean; sortOrder?: number; searchKeywords?: string[] | null }) => void; busy: boolean }) {
  const ordered = [...tools].sort((a, b) => Number(b.isPopular) - Number(a.isPopular) || a.sortOrder - b.sortOrder || a.title.localeCompare(b.title));
  return <section className="admin-popular-tools"><header><div><p className="eyebrow">HOME / DISCOVERY</p><h2>인기 도구와 검색 별칭</h2><p>체크된 도구만 홈페이지에 노출됩니다. 작은 숫자일수록 먼저 표시됩니다.</p></div></header><div className="admin-tool-list">{ordered.map((tool) => <article key={tool.id}><div><strong>{tool.title}</strong><small>/{tool.slug}</small><p>{tool.description}</p></div><label className="admin-toggle"><input type="checkbox" checked={Boolean(tool.isPopular)} disabled={busy} onChange={(event) => onUpdate(tool.id, { isPopular: event.target.checked })} />홈 인기 도구</label><label>노출 순서<input type="number" min="0" defaultValue={tool.sortOrder} disabled={busy} onBlur={(event) => { const next = Number(event.target.value); if (Number.isFinite(next) && next !== tool.sortOrder) onUpdate(tool.id, { sortOrder: next }); }} /></label><label>검색 별칭<input defaultValue={(tool.searchKeywords ?? []).join(", ")} disabled={busy} onBlur={(event) => { const keywords = event.target.value.split(",").map((item) => item.trim()).filter(Boolean); if (keywords.join(",") !== (tool.searchKeywords ?? []).join(",")) onUpdate(tool.id, { searchKeywords: keywords.length ? keywords : null }); }} placeholder="예: 주담대, 모기지" /></label></article>)}</div></section>;
}

function CategoryEditor({ form, categories, onChange, onCancel, onSave, busy }: { form: CategoryForm; categories: CatalogCategory[]; onChange: (form: CategoryForm) => void; onCancel: () => void; onSave: () => void; busy: boolean }) {
  const field = (key: keyof CategoryForm, label: string, type: "text" | "textarea" = "text") => <label>{label}{type === "textarea" ? <textarea value={String(form[key] ?? "")} onChange={(event) => onChange({ ...form, [key]: event.target.value })} /> : <input value={String(form[key] ?? "")} onChange={(event) => onChange({ ...form, [key]: event.target.value })} />}</label>;
  return <div className="admin-dialog-backdrop" role="presentation"><section className="admin-dialog" role="dialog" aria-modal="true" aria-label="카테고리 편집"><header><div><p className="eyebrow">CATALOG EDITOR</p><h2>{form.id ? "카테고리 수정" : "카테고리 추가"}</h2></div><button onClick={onCancel} aria-label="닫기"><X size={21} /></button></header><div className="editor-fields"><label>상위 카테고리<select value={form.parentId ?? "root"} onChange={(event) => onChange({ ...form, parentId: event.target.value === "root" ? null : Number(event.target.value) })}><option value="root">대분류</option>{categories.filter((item) => item.id !== form.id).map((category) => <option key={category.id} value={category.id}>{category.parentId ? `└ ${category.name}` : category.name}</option>)}</select></label>{field("name", "이름")}{field("slug", "URL 슬러그 (영문 소문자·숫자·하이픈)")}{field("description", "설명", "textarea")}{field("icon", "아이콘 키")}{field("seoTitle", "SEO 제목")}{field("seoDescription", "SEO 설명", "textarea")}<label>공개 상태<select value={form.status} onChange={(event) => onChange({ ...form, status: event.target.value as CategoryForm["status"] })}><option value="active">공개</option><option value="inactive">비공개</option></select></label></div><footer><button className="admin-secondary" onClick={onCancel}>취소</button><button className="admin-primary" disabled={busy || !form.name || !form.slug} onClick={onSave}><Save size={17} />{busy ? "저장 중" : "저장"}</button></footer></section></div>;
}
