import { useState } from "react";
import { CatalogBreadcrumb, CalculatorActions, SeoHead, ToolKnowledge, ToolMetaResolver } from "@/components/CatalogSupport";
import { CommaNumberInput } from "@/components/CommaNumberInput";
import { ToolFrame } from "@/components/ToolLayout";
import { calculateDeposit, calculateLoan, calculateRentConversion, calculateSavings } from "@shared/toolbox";

const won=new Intl.NumberFormat("ko-KR",{maximumFractionDigits:0});
type Kind="rent-conversion"|"jeonse-to-monthly"|"monthly-to-jeonse"|"loan-amortization"|"deposit-interest"|"savings";
const spec:Record<Kind,{title:string;tag:string;index:string;desc:string;category:string;method:string;caution:string}>={
 "rent-conversion":{title:"전월세 전환율 계산기",tag:"REAL ESTATE",index:"13",desc:"보증금·월세·전환율 기준의 실질 월 비용을 계산합니다.",category:"real-estate",method:"보증금에 연 전환율을 적용해 월 환산액을 구한 뒤 월세와 합산합니다.",caution:"계약 시점과 지역별 전환율 기준을 확인하세요."},
 "jeonse-to-monthly":{title:"전세 → 월세 계산기",tag:"REAL ESTATE",index:"14",desc:"전세 보증금을 월세 기준으로 환산합니다.",category:"real-estate",method:"전세 보증금에 연 전환율을 적용해 월 환산액을 계산합니다.",caution:"전환율은 계약 조건에 따라 다를 수 있습니다."},
 "monthly-to-jeonse":{title:"월세 → 전세 계산기",tag:"REAL ESTATE",index:"15",desc:"월세를 전세 보증금 기준으로 환산합니다.",category:"real-estate",method:"월세의 연간 금액을 전환율로 나누어 전세 환산 보증금을 계산합니다.",caution:"실제 계약 전에는 임대인·중개사와 계약 조건을 확인하세요."},
 "loan-amortization":{title:"원리금균등상환 계산기",tag:"FINANCE",index:"16",desc:"원리금균등 방식의 월 상환액과 총 이자를 계산합니다.",category:"finance",method:"월 이자율과 상환 기간을 적용한 원리금균등 상환 공식을 사용합니다.",caution:"금리, 거치기간, 수수료는 금융기관 계약 내용을 확인하세요."},
 "deposit-interest":{title:"예금 이자 계산기",tag:"FINANCE",index:"17",desc:"예치금·금리·기간을 기준으로 단리 예상 이자를 계산합니다.",category:"finance",method:"원금에 연 이자율과 예치 개월 수를 적용합니다.",caution:"세전 단리 기준의 참고용 결과이며 상품 조건과 세금은 반영하지 않습니다."},
 savings:{title:"적금 계산기",tag:"FINANCE",index:"18",desc:"월 납입액·금리·기간으로 만기 예상액을 계산합니다.",category:"finance",method:"매월 말 납입 기준으로 원금 합계와 간이 월 이자를 계산합니다.",caution:"실제 상품의 납입일, 우대금리, 세금에 따라 결과가 달라질 수 있습니다."},
};
export default function AdvancedCalculators({kind}:{kind:Kind}){const s=spec[kind]; const [a,setA]=useState(kind==="savings"?500000:10000000),[b,setB]=useState(kind.includes("rent")||kind.includes("monthly")||kind.includes("jeonse")?700000:3.5),[c,setC]=useState(kind.includes("rent")||kind.includes("monthly")||kind.includes("jeonse")?5.5:12),[applied,setApplied]=useState({a,b,c}); const r:any=kind==="loan-amortization"?calculateLoan(applied.a,applied.b,applied.c,"annuity"):kind==="deposit-interest"?calculateDeposit(applied.a,applied.b,applied.c):kind==="savings"?calculateSavings(applied.a,applied.b,applied.c):calculateRentConversion(applied.a,kind==="jeonse-to-monthly"?0:applied.b,applied.c); const main=kind==="loan-amortization"?r.firstPayment:kind==="deposit-interest"?r.total:kind==="savings"?r.total:kind==="monthly-to-jeonse"?r.jeonseEquivalent:r.monthlyEquivalent; return <ToolMetaResolver slug={kind}>{tool=><ToolFrame index={s.index} tag={s.tag} title={s.title} description={s.desc}><SeoHead title={tool.seoTitle??tool.title} description={tool.seoDescription??tool.description}/><CatalogBreadcrumb toolSlug={tool.slug}/><section className="calculator-layout"><div className="calculator-form"><p className="eyebrow">INPUT</p><label>{kind==="savings"?"월 납입액":kind==="loan-amortization"?"대출금액":"기준 금액"}<div className="input-suffix"><CommaNumberInput ariaLabel="기준 금액" value={a} onValueChange={setA}/><span>원</span></div></label>{kind!=="jeonse-to-monthly"&&<label>{kind==="loan-amortization"||kind==="deposit-interest"||kind==="savings"?"연 이자율":"월세"}<div className="input-suffix"><CommaNumberInput ariaLabel="두번째 값" value={b} onValueChange={setB}/><span>{kind==="loan-amortization"||kind==="deposit-interest"||kind==="savings"?"%":"원"}</span></div></label>}<label>{kind==="loan-amortization"||kind==="deposit-interest"||kind==="savings"?"기간":"전환율"}<div className="input-suffix"><CommaNumberInput ariaLabel="세번째 값" value={c} onValueChange={setC}/><span>{kind==="loan-amortization"||kind==="deposit-interest"||kind==="savings"?"개월":"%"}</span></div></label><CalculatorActions onCalculate={()=>setApplied({a,b,c})} onReset={()=>{setA(kind==="savings"?500000:10000000);setB(kind.includes("rent")||kind.includes("monthly")||kind.includes("jeonse")?700000:3.5);setC(kind.includes("rent")||kind.includes("monthly")||kind.includes("jeonse")?5.5:12);}}/></div><div className="calculator-output black-output"><p className="eyebrow">RESULT</p><h2>예상 결과</h2><strong>{won.format(main)}<small>원</small></strong><div className="result-rows"><p><span>입력 기준</span><b>{won.format(applied.a)}원</b></p><p><span>참고 결과</span><b>{kind==="loan-amortization"?`${won.format(r.totalInterest)}원 이자`:kind==="deposit-interest"?`${won.format(r.interest)}원 이자`:kind==="savings"?`${won.format(r.interest)}원 이자`:"전환율 기준"}</b></p></div></div></section><ToolKnowledge tool={tool} method={s.method} example="기본 입력값을 바꾼 뒤 계산하기를 누르면 결과가 갱신됩니다." caution={s.caution}/></ToolFrame>}</ToolMetaResolver>}
