import { ReactNode, useState } from "react";
import { CatalogBreadcrumb, CalculatorActions, SeoHead, ToolKnowledge, ToolMetaResolver } from "@/components/CatalogSupport";
import { CommaNumberInput } from "@/components/CommaNumberInput";
import { ToolFrame } from "@/components/ToolLayout";
import { calculateAge, calculateDateDifference, calculateDateOperation, calculateDDay, calculateTimeOperation } from "@shared/toolbox";

type DateTimeKind = "date-calculator" | "d-day" | "age" | "man-age" | "date-difference" | "time-calculator";
type Spec = { index: string; tag: string; title: string; description: string; method: string; example: string; caution: string };
const number = new Intl.NumberFormat("ko-KR", { maximumFractionDigits: 0 });

const specs: Record<DateTimeKind, Spec> = {
  "date-calculator": { index: "46", tag: "DATE / OPERATION", title: "날짜 계산기", description: "기준일에서 연·월·일을 더하거나 빼 결과 날짜를 계산합니다.", method: "달력일 기준으로 연·월을 먼저 이동한 뒤 일을 더하거나 뺍니다. 대상 월에 같은 날짜가 없으면 그 달의 마지막 날로 보정합니다.", example: "2024년 1월 31일에서 1개월을 더하면 2024년 2월 29일로 계산됩니다.", caution: "이 도구는 달력일 연산을 제공합니다. 계약·법정기한의 산입·불산입 규칙은 별도 확인하세요." },
  "d-day": { index: "47", tag: "DATE / COUNTDOWN", title: "D-Day 계산기", description: "기준일과 목표일을 입력해 D-Day와 남은 일수를 계산합니다.", method: "목표일에서 기준일을 뺀 달력일 차이로 D-Day를 계산합니다. 오늘이면 D-Day, 미래면 D-숫자, 과거면 D+숫자로 표시합니다.", example: "기준일이 2026년 1월 1일이고 목표일이 2026년 1월 10일이면 D-9입니다.", caution: "기념일의 당일 포함 여부는 목적에 따라 다를 수 있습니다. 이 계산기는 기준일을 제외한 날짜 차이를 기본으로 합니다." },
  "age": { index: "48", tag: "DATE / AGE", title: "나이 계산기", description: "생년월일과 기준일로 만 나이·세는 나이·연 나이를 비교합니다.", method: "기준연도와 출생연도의 차이에 생일 경과 여부를 반영해 만 나이를 계산하고, 세는 나이와 연 나이를 함께 보여 줍니다.", example: "2000년 6월 15일 출생자의 2026년 1월 1일 기준 만 나이는 25세입니다.", caution: "세는 나이는 관습상 정보입니다. 법률·행정·계약의 나이 판단에는 적용 법령의 기준을 확인하세요." },
  "man-age": { index: "49", tag: "DATE / AGE", title: "만 나이 계산기", description: "생년월일과 기준일로 현재 만 나이와 다음 생일까지 남은 날짜를 계산합니다.", method: "기준일의 해당 연도 생일이 지났는지 비교하여 만 나이를 계산하고, 다음 생일까지의 달력일 차이를 표시합니다.", example: "2000년 2월 29일 출생자를 비윤년 2025년 2월 28일 기준으로 계산할 수 있습니다.", caution: "2월 29일 생일은 비윤년 2월의 마지막 날 기준으로 처리합니다. 기관별 세부 기준은 다를 수 있습니다." },
  "date-difference": { index: "50", tag: "DATE / DIFFERENCE", title: "날짜 차이 계산기", description: "시작일과 종료일 사이의 총 일수, 주수와 완전한 개월 수를 계산합니다.", method: "종료일에서 시작일을 뺀 달력일 차이를 기본으로 하며, 포함일 옵션에서는 시작일과 종료일을 모두 포함합니다.", example: "2024년 2월 28일부터 2024년 3월 1일까지는 기본 2일, 양 끝 날짜 포함 3일입니다.", caution: "근로·임대·행정 기한의 산입·불산입은 해당 제도에 따라 다르므로 이 도구의 포함일 옵션과 구분하세요." },
  "time-calculator": { index: "51", tag: "TIME / OPERATION", title: "시간 계산기", description: "기준 시각에 시간과 분을 더하거나 빼 결과 시각을 계산합니다.", method: "기준 시각을 분으로 바꿔 시간·분 증감값을 반영하고 24시간 단위로 정규화합니다. 날짜가 바뀌면 전날·다음 날을 표시합니다.", example: "23:30에서 2시간 45분을 더하면 다음 날 02:15입니다.", caution: "이 도구는 시각 연산만 제공합니다. 휴게·연장·야간근로 판단에는 근무시간 계산기와 계약 기준을 함께 확인하세요." },
};

function NumberField({ label, value, onChange, unit, min = 0 }: { label: string; value: number; onChange: (value: number) => void; unit: string; min?: number }) {
  return <label>{label}<div className="input-suffix"><CommaNumberInput ariaLabel={label} value={value} onValueChange={onChange} min={min} /><span>{unit}</span></div></label>;
}
function ResultRow({ label, value }: { label: string; value: string }) { return <p><span>{label}</span><b>{value}</b></p>; }
function Meta({ kind, children }: { kind: DateTimeKind; children: ReactNode }) {
  const spec = specs[kind];
  return <ToolMetaResolver slug={kind}>{(tool) => <ToolFrame index={spec.index} tag={spec.tag} title={spec.title} description={spec.description}><SeoHead title={tool.seoTitle ?? tool.title} description={tool.seoDescription ?? tool.description} /><CatalogBreadcrumb toolSlug={tool.slug} />{children}<ToolKnowledge tool={tool} method={spec.method} example={spec.example} caution={spec.caution} /></ToolFrame>}</ToolMetaResolver>;
}
function Notice({ children, warning = false }: { children: ReactNode; warning?: boolean }) { return <p className={warning ? "calculator-notice warning" : "calculator-notice"}>{children}</p>; }
function dayText(offset: number) { if (offset === 0) return "당일"; if (offset === 1) return "다음 날"; if (offset === -1) return "전날"; return offset > 0 ? `${offset}일 후` : `${Math.abs(offset)}일 전`; }

function DateCalculator() {
  const [base, setBase] = useState("2024-01-31"); const [mode, setMode] = useState<"add" | "subtract">("add"); const [years, setYears] = useState(0); const [months, setMonths] = useState(1); const [days, setDays] = useState(0); const [applied, setApplied] = useState({ base: "2024-01-31", mode: "add" as "add" | "subtract", years: 0, months: 1, days: 0 }); const result = calculateDateOperation(applied.base, applied.years, applied.months, applied.days, applied.mode);
  const reset = () => { const next = { base: "2024-01-31", mode: "add" as "add" | "subtract", years: 0, months: 1, days: 0 }; setBase(next.base); setMode(next.mode); setYears(next.years); setMonths(next.months); setDays(next.days); setApplied(next); };
  return <Meta kind="date-calculator"><section className="calculator-layout"><div className="calculator-form"><p className="eyebrow">DATE OPERATION SETTINGS</p><label>기준일<input type="date" value={base} onChange={(event) => setBase(event.target.value)} /></label><label>연산<select value={mode} onChange={(event) => setMode(event.target.value as "add" | "subtract")}><option value="add">더하기</option><option value="subtract">빼기</option></select></label><NumberField label="연" value={years} onChange={setYears} unit="년" /><NumberField label="월" value={months} onChange={setMonths} unit="개월" /><NumberField label="일" value={days} onChange={setDays} unit="일" /><CalculatorActions onCalculate={() => setApplied({ base, mode, years, months, days })} onReset={reset} /></div><div className="calculator-output black-output"><p className="eyebrow">DATE RESULT</p><h2>계산 결과 날짜</h2><strong>{result.valid ? result.resultDate : "—"}</strong><div className="result-rows"><ResultRow label="기준일" value={result.valid ? result.baseDate : "—"} /><ResultRow label="연산" value={mode === "add" ? "날짜 더하기" : "날짜 빼기"} /><ResultRow label="날짜 차이" value={result.valid ? `${number.format(Math.abs(result.differenceDays))}일` : "—"} /></div></div></section>{!result.valid && <Notice warning>{result.message}</Notice>}{result.valid && <Notice>월말 날짜는 대상 월의 마지막 날로 자동 보정합니다.</Notice>}</Meta>;
}

function DDayCalculator() {
  const [base, setBase] = useState("2026-01-01"); const [target, setTarget] = useState("2026-01-10"); const [applied, setApplied] = useState({ base: "2026-01-01", target: "2026-01-10" }); const result = calculateDDay(applied.base, applied.target);
  const reset = () => { const next = { base: "2026-01-01", target: "2026-01-10" }; setBase(next.base); setTarget(next.target); setApplied(next); };
  return <Meta kind="d-day"><section className="calculator-layout"><div className="calculator-form"><p className="eyebrow">D-DAY SETTINGS</p><label>기준일<input type="date" value={base} onChange={(event) => setBase(event.target.value)} /></label><label>목표일<input type="date" value={target} onChange={(event) => setTarget(event.target.value)} /></label><CalculatorActions onCalculate={() => setApplied({ base, target })} onReset={reset} /></div><div className="calculator-output black-output"><p className="eyebrow">D-DAY RESULT</p><h2>목표일까지</h2><strong>{result.valid ? result.label : "—"}</strong><div className="result-rows"><ResultRow label="날짜 차이" value={result.valid ? `${number.format(Math.abs(result.days))}일` : "—"} /><ResultRow label="주·일" value={result.valid ? `${result.weeks}주 ${result.remainingDays}일` : "—"} /><ResultRow label="상태" value={result.valid ? (result.days > 0 ? "남은 날짜" : result.days < 0 ? "지난 날짜" : "오늘") : "—"} /></div></div></section>{!result.valid && <Notice warning>{result.message}</Notice>}</Meta>;
}

function AgeCalculator({ kind }: { kind: "age" | "man-age" }) {
  const [birth, setBirth] = useState("2000-06-15"); const [reference, setReference] = useState("2026-01-01"); const [applied, setApplied] = useState({ birth: "2000-06-15", reference: "2026-01-01" }); const result = calculateAge(applied.birth, applied.reference);
  const reset = () => { const next = { birth: "2000-06-15", reference: "2026-01-01" }; setBirth(next.birth); setReference(next.reference); setApplied(next); };
  const manOnly = kind === "man-age";
  return <Meta kind={kind}><section className="calculator-layout"><div className="calculator-form"><p className="eyebrow">AGE SETTINGS</p><label>생년월일<input type="date" value={birth} onChange={(event) => setBirth(event.target.value)} /></label><label>기준일<input type="date" value={reference} onChange={(event) => setReference(event.target.value)} /></label><CalculatorActions onCalculate={() => setApplied({ birth, reference })} onReset={reset} /></div><div className="calculator-output black-output"><p className="eyebrow">AGE RESULT</p><h2>{manOnly ? "현재 만 나이" : "만 나이"}</h2><strong>{result.valid ? `${result.fullAge}세` : "—"}</strong><div className="result-rows">{!manOnly && <><ResultRow label="세는 나이" value={result.valid ? `${result.koreanAge}세` : "—"} /><ResultRow label="연 나이" value={result.valid ? `${result.yearAge}세` : "—"} /></>}<ResultRow label="다음 생일까지" value={result.valid ? `${result.nextBirthdayDays}일` : "—"} /><ResultRow label="올해 생일" value={result.valid ? (result.birthdayPassed ? "지남" : "남음") : "—"} /></div></div></section>{!result.valid && <Notice warning>{result.message}</Notice>}{result.valid && <Notice>{manOnly ? "윤년 2월 29일 출생자는 비윤년의 2월 마지막 날을 생일로 처리합니다." : "세는 나이는 관습상 정보이며, 법적 나이 판단에는 만 나이를 확인하세요."}</Notice>}</Meta>;
}

function DateDifferenceCalculator() {
  const [start, setStart] = useState("2024-02-28"); const [end, setEnd] = useState("2024-03-01"); const [inclusive, setInclusive] = useState(false); const [applied, setApplied] = useState({ start: "2024-02-28", end: "2024-03-01", inclusive: false }); const result = calculateDateDifference(applied.start, applied.end, applied.inclusive);
  const reset = () => { const next = { start: "2024-02-28", end: "2024-03-01", inclusive: false }; setStart(next.start); setEnd(next.end); setInclusive(next.inclusive); setApplied(next); };
  return <Meta kind="date-difference"><section className="calculator-layout"><div className="calculator-form"><p className="eyebrow">DATE DIFFERENCE SETTINGS</p><label>시작일<input type="date" value={start} onChange={(event) => setStart(event.target.value)} /></label><label>종료일<input type="date" value={end} onChange={(event) => setEnd(event.target.value)} /></label><label className="checkbox-field"><input type="checkbox" checked={inclusive} onChange={(event) => setInclusive(event.target.checked)} />시작일·종료일 모두 포함</label><CalculatorActions onCalculate={() => setApplied({ start, end, inclusive })} onReset={reset} /></div><div className="calculator-output black-output"><p className="eyebrow">DATE DIFFERENCE RESULT</p><h2>총 기간</h2><strong>{result.valid ? `${number.format(result.selectedDays ?? 0)}일` : "—"}</strong><div className="result-rows"><ResultRow label="기본 날짜 차이" value={result.valid ? `${number.format(result.days ?? 0)}일` : "—"} /><ResultRow label="주·일" value={result.valid ? `${result.weeks ?? 0}주 ${result.remainingDays ?? 0}일` : "—"} /><ResultRow label="완전한 개월" value={result.valid ? `${result.months ?? 0}개월 ${result.monthRemainingDays ?? 0}일` : "—"} /></div></div></section>{!result.valid && <Notice warning>{result.message}</Notice>}{result.valid && <Notice>{applied.inclusive ? "양 끝 날짜를 모두 포함한 결과입니다." : "시작일을 제외한 날짜 차이 기준 결과입니다."}</Notice>}</Meta>;
}

function TimeCalculator() {
  const [base, setBase] = useState("23:30"); const [mode, setMode] = useState<"add" | "subtract">("add"); const [hours, setHours] = useState(2); const [minutes, setMinutes] = useState(45); const [applied, setApplied] = useState({ base: "23:30", mode: "add" as "add" | "subtract", hours: 2, minutes: 45 }); const result = calculateTimeOperation(applied.base, applied.hours, applied.minutes, applied.mode);
  const reset = () => { const next = { base: "23:30", mode: "add" as "add" | "subtract", hours: 2, minutes: 45 }; setBase(next.base); setMode(next.mode); setHours(next.hours); setMinutes(next.minutes); setApplied(next); };
  return <Meta kind="time-calculator"><section className="calculator-layout"><div className="calculator-form"><p className="eyebrow">TIME OPERATION SETTINGS</p><label>기준 시각<input type="time" value={base} onChange={(event) => setBase(event.target.value)} /></label><label>연산<select value={mode} onChange={(event) => setMode(event.target.value as "add" | "subtract")}><option value="add">더하기</option><option value="subtract">빼기</option></select></label><NumberField label="시간" value={hours} onChange={setHours} unit="시간" /><NumberField label="분" value={minutes} onChange={setMinutes} unit="분" /><CalculatorActions onCalculate={() => setApplied({ base, mode, hours, minutes })} onReset={reset} /></div><div className="calculator-output black-output"><p className="eyebrow">TIME RESULT</p><h2>계산 결과 시각</h2><strong>{result.valid ? result.resultTime : "—"}</strong><div className="result-rows"><ResultRow label="날짜 상태" value={result.valid ? dayText(result.dayOffset) : "—"} /><ResultRow label="연산" value={mode === "add" ? "시간 더하기" : "시간 빼기"} /><ResultRow label="증감 시간" value={result.valid ? `${number.format(Math.abs(result.totalMinutes))}분` : "—"} /></div></div></section>{!result.valid && <Notice warning>{result.message}</Notice>}</Meta>;
}

export default function DateTimeCalculators({ kind }: { kind: DateTimeKind }) {
  if (kind === "date-calculator") return <DateCalculator />;
  if (kind === "d-day") return <DDayCalculator />;
  if (kind === "age" || kind === "man-age") return <AgeCalculator kind={kind} />;
  if (kind === "date-difference") return <DateDifferenceCalculator />;
  return <TimeCalculator />;
}
