import { useState } from "react";
import { CatalogBreadcrumb, CalculatorActions, SeoHead, ToolKnowledge, ToolMetaResolver } from "@/components/CatalogSupport";
import { CommaNumberInput } from "@/components/CommaNumberInput";
import { ToolFrame } from "@/components/ToolLayout";
import { calculateRetirementPay, calculateServicePeriod } from "@shared/toolbox";

const won = new Intl.NumberFormat("ko-KR", { maximumFractionDigits: 0 });
export default function RetirementPayCalculator() {
  const [wages, setWages] = useState(9_000_000); const [days, setDays] = useState(90); const [years, setYears] = useState(3); const [startDate, setStartDate] = useState(""); const [endDate, setEndDate] = useState(""); const [dateError, setDateError] = useState(""); const [applied, setApplied] = useState({ wages: 9_000_000, days: 90, years: 3 });
  const result = calculateRetirementPay(applied.wages, applied.days, applied.years); const apply = () => { const period = startDate || endDate ? calculateServicePeriod(startDate, endDate) : null; if (period && !period.valid) { setDateError(period.message); return; } setDateError(""); setApplied({ wages, days, years: period?.years ?? years }); }; const reset = () => { setWages(9_000_000); setDays(90); setYears(3); setStartDate(""); setEndDate(""); setDateError(""); setApplied({ wages: 9_000_000, days: 90, years: 3 }); };
  return <ToolMetaResolver slug="retirement-pay">{(tool) => <ToolFrame index="12" tag="RETIREMENT CALCULATOR" title="퇴직금 계산기" description="최근 3개월 임금, 일수, 계속 근로연수를 기준으로 예상 퇴직금을 계산합니다."><SeoHead title={tool.seoTitle ?? tool.title} description={tool.seoDescription ?? tool.description} /><CatalogBreadcrumb toolSlug={tool.slug} /><section className="calculator-layout"><div className="calculator-form"><p className="eyebrow">INPUT / RETIREMENT</p><label>최근 3개월 임금 합계<div className="input-suffix"><CommaNumberInput ariaLabel="최근 3개월 임금 합계" value={wages} onValueChange={setWages} /><span>원</span></div></label><label>최근 3개월 총일수<div className="input-suffix"><CommaNumberInput ariaLabel="최근 3개월 총일수" value={days} onValueChange={setDays} min={1} /><span>일</span></div></label><div className="date-pair"><label>입사일 (선택)<input type="date" value={startDate} onChange={(event) => setStartDate(event.target.value)} /></label><label>퇴사일 (선택)<input type="date" value={endDate} onChange={(event) => setEndDate(event.target.value)} /></label></div><label>계속 근로연수 (날짜 미입력 시)<div className="input-suffix"><CommaNumberInput ariaLabel="계속 근로연수" value={years} onValueChange={setYears} /><span>년</span></div></label>{dateError && <p className="input-error">{dateError}</p>}<CalculatorActions onCalculate={apply} onReset={reset} /></div><div className="calculator-output black-output"><p className="eyebrow">ESTIMATED RETIREMENT PAY</p><h2>예상 퇴직금</h2><strong>{won.format(result.retirementPay)}<small>원</small></strong><div className="result-rows"><p><span>1일 평균임금</span><b>{won.format(result.dailyAverageWage)}원</b></p><p><span>계속 근로연수</span><b>{applied.years.toFixed(2)}년</b></p></div></div></section><ToolKnowledge tool={tool} method="최근 3개월 임금 합계를 해당 기간 총일수로 나누어 1일 평균임금을 구한 뒤, 30일과 계속 근로연수를 곱합니다." example="최근 3개월 임금 900만원, 90일, 근속 3년을 입력해 예상 퇴직금을 확인합니다." caution="상여금, 연차수당, 실제 입사·퇴사일, 평균임금과 통상임금 산정 기준에 따라 결과가 달라질 수 있습니다. 입력 날짜는 단순 근속기간 계산 보조값입니다." /></ToolFrame>}</ToolMetaResolver>;
}
