import { useState, type ReactNode } from "react";
import { CatalogBreadcrumb, CalculatorActions, SeoHead, ToolKnowledge, ToolMetaResolver } from "@/components/CatalogSupport";
import { CommaNumberInput } from "@/components/CommaNumberInput";
import { ToolFrame } from "@/components/ToolLayout";
import {
  HourlyWageMode,
  PAYROLL_2026,
  calculateAnnualLeavePay,
  calculateFourInsurance,
  calculateHourlyWage,
  calculatePayrollTakeHome,
  calculateRetirementIncomeTax,
  calculateUnemploymentBenefit,
  calculateWeeklyHolidayPay,
  calculateWorkHours,
} from "@shared/toolbox";

const won = new Intl.NumberFormat("ko-KR", { maximumFractionDigits: 0 });
const number = new Intl.NumberFormat("ko-KR", { maximumFractionDigits: 2 });

type SalaryCalculatorKind = "annual-take-home" | "monthly-take-home" | "retirement-income-tax" | "weekly-holiday-pay" | "annual-leave-pay" | "hourly-wage" | "work-hours" | "four-insurance" | "unemployment-benefit";
type ToolSpec = { index: string; tag: string; title: string; description: string; method: string; example: string; caution: string; useCase: string; interpretation: string };

const specs: Record<SalaryCalculatorKind, ToolSpec> = {
  "annual-take-home": { index: "29", tag: "SALARY / PAYROLL", title: "연봉 실수령액 계산기", description: "연봉, 부양가족·자녀 수와 비과세 급여를 반영해 월·연 예상 실수령액을 계산합니다.", method: "연봉을 월 급여로 바꾼 뒤 2026년 일반 직장가입자의 4대보험 근로자 부담분과 근로소득 세액의 간이 추정치를 공제합니다.", example: "연봉 5,000만원, 부양가족 1명, 비과세 급여 20만원을 입력하면 월 공제 항목과 연 예상 실수령액을 확인할 수 있습니다.", caution: "실제 원천징수는 국세청 간이세액표 선택비율, 가족의 공제요건, 비과세 항목·회사 급여구성 및 연말정산에 따라 달라집니다.", useCase: "연봉 협상이나 이직 제안 비교 전에 월 현금흐름을 가늠할 때 사용합니다.", interpretation: "표시 금액은 일반 직장가입자 기준의 월 예상치입니다. 실제 급여명세서의 원천징수액과는 차이가 날 수 있습니다." },
  "monthly-take-home": { index: "30", tag: "SALARY / PAYROLL", title: "월급 실수령액 계산기", description: "월 세전 급여와 비과세액을 입력해 공제 항목별 월 예상 실수령액을 계산합니다.", method: "월 급여에서 비과세액을 구분한 뒤 연금·건강·장기요양·고용보험과 연 환산 소득세의 월 추정액을 합산합니다.", example: "월 급여 350만원, 비과세 20만원을 입력하면 각 공제액과 월 예상 실수령액을 확인할 수 있습니다.", caution: "보수월액, 연금 상·하한, 비과세 항목, 원천징수 선택비율 및 연말정산 공제는 개인과 회사마다 다릅니다.", useCase: "월 급여 제안이나 급여명세서의 주요 공제 구조를 이해할 때 사용합니다.", interpretation: "비과세 급여는 이 계산의 보험·소득세 산정 대상에서 제외하는 간이 가정입니다." },
  "retirement-income-tax": { index: "31", tag: "SALARY / RETIREMENT", title: "퇴직소득세 계산기", description: "퇴직급여와 근속연수를 기준으로 퇴직소득세·지방소득세와 예상 수령액을 간이 계산합니다.", method: "퇴직소득금액에서 근속연수공제를 차감해 환산급여를 구하고, 환산급여공제·기본세율·근속연수 환산 절차를 적용합니다.", example: "퇴직급여 5,000만원, 근속 8년을 입력하면 근속연수공제와 추정 세액을 확인할 수 있습니다.", caution: "비과세소득, 중간정산, 과세이연, 임원 여부와 귀속연도별 특례는 반영하지 않습니다. 실제 세액은 국세청 프로그램으로 최종 확인하세요.", useCase: "퇴직금 수령 전 세후 금액을 거칠게 추정할 때 사용합니다.", interpretation: "근속연수가 길수록 근속연수공제와 환산 방식이 반영되어 과세표준이 낮아질 수 있습니다." },
  "weekly-holiday-pay": { index: "32", tag: "SALARY / ALLOWANCE", title: "주휴수당 계산기", description: "시급과 주당 소정근로시간, 근무일수로 주휴수당·예상 주급을 계산합니다.", method: "주 15시간 이상이며 해당 주를 개근한 경우, 1일 소정근로시간에 시급을 곱해 주휴수당을 추정합니다.", example: "시급 10,320원, 주 20시간, 주 5일을 입력하면 1일 4시간 기준 주휴수당을 확인할 수 있습니다.", caution: "주휴수당은 실제 소정근로일의 개근, 계약형태, 결근·휴직 여부 등에 따라 달라집니다. 월급제의 중복 산정 여부도 근로계약을 확인하세요.", useCase: "단시간·아르바이트 근로의 주급 구조를 확인할 때 사용합니다.", interpretation: "주 15시간 또는 개근 요건을 충족하지 않으면 이 도구는 주휴수당을 0원으로 표시합니다." },
  "annual-leave-pay": { index: "33", tag: "SALARY / ALLOWANCE", title: "연차수당 계산기", description: "통상시급, 1일 소정근로시간과 미사용 연차일수로 예상 연차수당을 계산합니다.", method: "통상시급에 1일 소정근로시간을 곱해 1일 통상임금을 계산하고, 미사용 연차일수를 곱합니다.", example: "통상시급 15,000원, 1일 8시간, 미사용 연차 5일이면 예상 연차수당은 60만원입니다.", caution: "연차 발생·사용촉진·소멸, 통상임금 범위, 근로계약과 회사의 운영 방식에 따라 실제 지급 여부와 금액이 달라질 수 있습니다.", useCase: "퇴직 또는 연차 정산 전 미사용 연차의 금액을 확인할 때 사용합니다.", interpretation: "이 도구는 수당 산정 기준이 되는 통상임금만 반영한 단순 추정치입니다." },
  "hourly-wage": { index: "34", tag: "SALARY / ALLOWANCE", title: "시급 계산기", description: "월급에서 시급을 계산하거나 시급에서 월급을 환산합니다.", method: "월급을 월 환산 근로시간으로 나누거나, 시급에 월 환산 근로시간을 곱해 계산합니다.", example: "월급 250만원과 월 209시간을 입력하면 환산 시급을, 시급 12,000원과 209시간을 입력하면 월급을 볼 수 있습니다.", caution: "월 환산시간에는 유급주휴, 연장·야간·휴일근로수당 포함 여부가 달라질 수 있습니다. 근로계약서의 임금 산정 기준을 확인하세요.", useCase: "급여 제안이나 아르바이트 조건을 시급 기준으로 비교할 때 사용합니다.", interpretation: "2026년 최저임금은 시간급 10,320원입니다. 이 도구는 입력값을 검증하지 않고 환산합니다." },
  "work-hours": { index: "35", tag: "SALARY / WORK TIME", title: "근무시간 계산기", description: "시작·종료시간과 휴게시간을 입력해 전체 근무시간과 실근무시간을 계산합니다.", method: "종료시간에서 시작시간을 빼고 휴게시간을 차감합니다. 종료시간이 같거나 이르면 자정을 넘는 근무로 처리합니다.", example: "22:00부터 다음 날 06:00까지, 휴게 60분이면 전체 8시간·실근무 7시간입니다.", caution: "휴게시간 부여·연장·야간근로 판단은 근로계약과 법정 요건을 별도로 확인해야 합니다. 이 도구는 시간 합산만 제공합니다.", useCase: "교대근무·야간근무의 실근무시간을 빠르게 확인할 때 사용합니다.", interpretation: "자정을 넘는 경우에는 종료시간을 다음 날로 간주해 계산합니다." },
  "four-insurance": { index: "36", tag: "SALARY / INSURANCE", title: "4대보험 계산기", description: "월 보수를 기준으로 국민연금·건강·장기요양·고용보험의 근로자·사업주 기본 부담액을 계산합니다.", method: "2026년 일반 직장가입자 기준의 국민연금 4.75%, 건강보험 3.595%, 장기요양보험 건강보험료 연동분, 고용보험 0.9%를 적용합니다.", example: "월 보수 350만원을 입력하면 근로자 공제 예상액과 사업주 기본 부담액을 항목별로 확인할 수 있습니다.", caution: "사업주 부담에는 사업장 규모별 고용안정·직업능력개발 부담분과 업종별 산재보험료가 추가될 수 있습니다. 감면·보수월액 조정도 반영하지 않습니다.", useCase: "급여명세서의 4대보험 공제와 고용 비용의 기본 구조를 확인할 때 사용합니다.", interpretation: "국민연금은 2026년 7월 기준소득월액 상·하한을 적용하며, 기타 보험료는 입력한 월 보수를 기준으로 합니다." },
  "unemployment-benefit": { index: "37", tag: "SALARY / EMPLOYMENT", title: "실업급여 계산기", description: "퇴직 전 월급, 나이와 고용보험 가입기간을 기준으로 예상 1일 지급액·지급일수·총액을 계산합니다.", method: "평균 1일 임금의 60%에 2026년 일 상·하한을 적용하고, 연령과 피보험기간 구간별 소정급여일수를 곱합니다.", example: "월급 300만원, 만 35세, 고용보험 24개월이면 추정 1일 지급액과 예상 지급기간을 확인할 수 있습니다.", caution: "비자발적 이직, 피보험단위기간, 재취업활동, 연령·장애 여부와 실제 퇴사사유에 따라 수급자격·일수·금액이 달라집니다. 최종 판단은 고용센터에 확인하세요.", useCase: "퇴직 후 구직기간의 현금흐름을 사전 추정할 때 사용합니다.", interpretation: "가입기간이 180일 미만이면 이 도구는 예상 지급액을 0원으로 표시하지만, 실제 수급자격은 별도 심사를 거칩니다." },
};

function NumberField({ label, value, onChange, unit, min = 0 }: { label: string; value: number; onChange: (value: number) => void; unit: string; min?: number }) { return <label>{label}<div className="input-suffix"><CommaNumberInput ariaLabel={label} value={value} onValueChange={onChange} min={min} /><span>{unit}</span></div></label>; }
function ResultRow({ label, value }: { label: string; value: string }) { return <p><span>{label}</span><b>{value}</b></p>; }
function Meta({ kind, children }: { kind: SalaryCalculatorKind; children: ReactNode }) { const spec = specs[kind]; return <ToolMetaResolver slug={kind}>{(tool) => <ToolFrame index={spec.index} tag={spec.tag} title={spec.title} description={spec.description}><SeoHead title={tool.seoTitle ?? tool.title} description={tool.seoDescription ?? tool.description} /><CatalogBreadcrumb toolSlug={tool.slug} />{children}<ToolKnowledge tool={tool} method={spec.method} example={spec.example} caution={spec.caution}><section className="tool-knowledge"><div className="knowledge-grid"><article><p className="eyebrow">WHEN TO USE</p><h2>어떤 경우에 사용하나요?</h2><p>{spec.useCase}</p></article><article><p className="eyebrow">RESULT GUIDE</p><h2>결과 해석</h2><p>{spec.interpretation}</p></article></div></section></ToolKnowledge></ToolFrame>}</ToolMetaResolver>; }

function PayrollCalculator({ kind }: { kind: "annual-take-home" | "monthly-take-home" }) {
  const annual = kind === "annual-take-home"; const [amount, setAmount] = useState(annual ? 50_000_000 : 3_500_000); const [dependents, setDependents] = useState(1); const [children, setChildren] = useState(0); const [nonTaxable, setNonTaxable] = useState(200_000); const [applied, setApplied] = useState({ amount: annual ? 50_000_000 : 3_500_000, dependents: 1, children: 0, nonTaxable: 200_000 });
  const monthlyGross = annual ? applied.amount / 12 : applied.amount; const result = calculatePayrollTakeHome(monthlyGross, applied.dependents, applied.children, applied.nonTaxable);
  const reset = () => { const next = annual ? 50_000_000 : 3_500_000; setAmount(next); setDependents(1); setChildren(0); setNonTaxable(200_000); setApplied({ amount: next, dependents: 1, children: 0, nonTaxable: 200_000 }); };
  return <Meta kind={kind}><section className="calculator-layout salary-layout"><div className="calculator-form"><p className="eyebrow">PAYROLL SETTINGS</p><NumberField label={annual ? "연봉 (세전)" : "월 급여 (세전)"} value={amount} onChange={setAmount} unit="원" /><NumberField label="부양가족 수 (본인 포함)" value={dependents} onChange={setDependents} unit="명" min={1} /><NumberField label="자녀 수" value={children} onChange={setChildren} unit="명" /><NumberField label="월 비과세 급여" value={nonTaxable} onChange={setNonTaxable} unit="원" /><CalculatorActions onCalculate={() => setApplied({ amount, dependents, children, nonTaxable })} onReset={reset} /></div><div className="calculator-output black-output"><p className="eyebrow">ESTIMATED TAKE-HOME</p><h2>월 예상 실수령액</h2><strong>{won.format(result.monthlyNet)}<small>원</small></strong><div className="result-rows"><ResultRow label="월 세전 급여" value={`${won.format(result.monthlyGross)}원`} /><ResultRow label="월 공제 예상액" value={`${won.format(result.totalDeductions)}원`} /><ResultRow label="연 예상 실수령액" value={`${won.format(result.annualNet)}원`} /></div></div></section><section className="salary-breakdown"><p className="eyebrow">MONTHLY DEDUCTION DETAIL</p><h2>월 공제 항목</h2><div className="salary-breakdown-grid"><ResultRow label="국민연금" value={`${won.format(result.pension)}원`} /><ResultRow label="건강보험" value={`${won.format(result.health)}원`} /><ResultRow label="장기요양보험" value={`${won.format(result.longTermCare)}원`} /><ResultRow label="고용보험" value={`${won.format(result.employment)}원`} /><ResultRow label="소득세 (간이 추정)" value={`${won.format(result.incomeTax)}원`} /><ResultRow label="지방소득세" value={`${won.format(result.localIncomeTax)}원`} /></div></section></Meta>;
}

function RetirementIncomeTaxCalculator() {
  const [pay, setPay] = useState(50_000_000); const [years, setYears] = useState(8); const [nonTaxable, setNonTaxable] = useState(0); const [applied, setApplied] = useState({ pay: 50_000_000, years: 8, nonTaxable: 0 }); const result = calculateRetirementIncomeTax(applied.pay, applied.years, applied.nonTaxable);
  const reset = () => { setPay(50_000_000); setYears(8); setNonTaxable(0); setApplied({ pay: 50_000_000, years: 8, nonTaxable: 0 }); };
  return <Meta kind="retirement-income-tax"><section className="calculator-layout"><div className="calculator-form"><p className="eyebrow">RETIREMENT TAX SETTINGS</p><NumberField label="퇴직급여" value={pay} onChange={setPay} unit="원" /><NumberField label="근속연수" value={years} onChange={setYears} unit="년" min={1} /><NumberField label="비과세 퇴직소득" value={nonTaxable} onChange={setNonTaxable} unit="원" /><CalculatorActions onCalculate={() => setApplied({ pay, years, nonTaxable })} onReset={reset} /></div><div className="calculator-output black-output"><p className="eyebrow">ESTIMATED TAX</p><h2>예상 실수령액</h2><strong>{won.format(result.estimatedNet)}<small>원</small></strong><div className="result-rows"><ResultRow label="퇴직소득세" value={`${won.format(result.incomeTax)}원`} /><ResultRow label="지방소득세" value={`${won.format(result.localIncomeTax)}원`} /><ResultRow label="총 예상 세액" value={`${won.format(result.totalTax)}원`} /></div></div></section><section className="salary-breakdown"><p className="eyebrow">RETIREMENT TAX DETAIL</p><h2>과세표준 산정</h2><div className="salary-breakdown-grid"><ResultRow label="퇴직소득금액" value={`${won.format(result.retirementIncome)}원`} /><ResultRow label="근속연수공제" value={`${won.format(result.serviceDeduction)}원`} /><ResultRow label="환산급여" value={`${won.format(result.convertedIncome)}원`} /><ResultRow label="환산급여공제" value={`${won.format(result.conversionDeduction)}원`} /><ResultRow label="퇴직소득 과세표준" value={`${won.format(result.taxBase)}원`} /><ResultRow label="근속연수" value={`${result.years}년`} /></div></section></Meta>;
}

function WeeklyHolidayCalculator() {
  const [hourly, setHourly] = useState<number>(PAYROLL_2026.minimumHourlyWage); const [hours, setHours] = useState(20); const [days, setDays] = useState(5); const [completed, setCompleted] = useState(true); const [applied, setApplied] = useState<{ hourly: number; hours: number; days: number; completed: boolean }>({ hourly: PAYROLL_2026.minimumHourlyWage, hours: 20, days: 5, completed: true }); const result = calculateWeeklyHolidayPay(applied.hourly, applied.hours, applied.days, applied.completed);
  const reset = () => { setHourly(PAYROLL_2026.minimumHourlyWage); setHours(20); setDays(5); setCompleted(true); setApplied({ hourly: PAYROLL_2026.minimumHourlyWage, hours: 20, days: 5, completed: true }); };
  return <Meta kind="weekly-holiday-pay"><section className="calculator-layout"><div className="calculator-form"><p className="eyebrow">WEEKLY HOLIDAY SETTINGS</p><NumberField label="시급" value={hourly} onChange={setHourly} unit="원" /><NumberField label="주당 소정근로시간" value={hours} onChange={setHours} unit="시간" /><NumberField label="주당 근무일수" value={days} onChange={setDays} unit="일" min={1} /><label className="checkbox-field"><input type="checkbox" checked={completed} onChange={(event) => setCompleted(event.target.checked)} />해당 주 소정근로일 개근</label><CalculatorActions onCalculate={() => setApplied({ hourly, hours, days, completed })} onReset={reset} /></div><div className="calculator-output black-output"><p className="eyebrow">WEEKLY PAY</p><h2>예상 주급</h2><strong>{won.format(result.weeklyPay)}<small>원</small></strong><div className="result-rows"><ResultRow label="기본 임금" value={`${won.format(result.basicWage)}원`} /><ResultRow label="주휴수당" value={`${won.format(result.holidayPay)}원`} /><ResultRow label="월 예상액" value={`${won.format(result.monthlyEstimate)}원`} /></div></div></section><p className={result.eligible ? "calculator-notice" : "calculator-notice warning"}>{result.eligible ? `주 15시간 이상·개근 가정으로 1일 ${number.format(result.dailyHours)}시간의 주휴수당을 반영했습니다.` : "주휴수당은 주 15시간 이상 및 개근 요건을 충족해야 발생할 수 있습니다."}</p></Meta>;
}

function AnnualLeaveCalculator() {
  const [hourly, setHourly] = useState(15_000); const [hours, setHours] = useState(8); const [days, setDays] = useState(5); const [applied, setApplied] = useState({ hourly: 15_000, hours: 8, days: 5 }); const result = calculateAnnualLeavePay(applied.hourly, applied.hours, applied.days);
  const reset = () => { setHourly(15_000); setHours(8); setDays(5); setApplied({ hourly: 15_000, hours: 8, days: 5 }); };
  return <Meta kind="annual-leave-pay"><section className="calculator-layout"><div className="calculator-form"><p className="eyebrow">ANNUAL LEAVE SETTINGS</p><NumberField label="통상시급" value={hourly} onChange={setHourly} unit="원" /><NumberField label="1일 소정근로시간" value={hours} onChange={setHours} unit="시간" /><NumberField label="미사용 연차일수" value={days} onChange={setDays} unit="일" /><CalculatorActions onCalculate={() => setApplied({ hourly, hours, days })} onReset={reset} /></div><div className="calculator-output black-output"><p className="eyebrow">ESTIMATED ANNUAL LEAVE PAY</p><h2>예상 연차수당</h2><strong>{won.format(result.annualLeavePay)}<small>원</small></strong><div className="result-rows"><ResultRow label="1일 통상임금" value={`${won.format(result.dailyOrdinaryWage)}원`} /><ResultRow label="미사용 연차" value={`${number.format(result.unusedDays)}일`} /></div></div></section></Meta>;
}

function HourlyWageCalculator() {
  const [mode, setMode] = useState<HourlyWageMode>("from-monthly"); const [amount, setAmount] = useState(2_500_000); const [hours, setHours] = useState(209); const [applied, setApplied] = useState({ mode: "from-monthly" as HourlyWageMode, amount: 2_500_000, hours: 209 }); const result = calculateHourlyWage(applied.mode, applied.amount, applied.hours);
  const reset = () => { setMode("from-monthly"); setAmount(2_500_000); setHours(209); setApplied({ mode: "from-monthly", amount: 2_500_000, hours: 209 }); };
  const updateMode = (next: HourlyWageMode) => { setMode(next); setAmount(next === "from-monthly" ? 2_500_000 : PAYROLL_2026.minimumHourlyWage); };
  return <Meta kind="hourly-wage"><section className="calculator-layout"><div className="calculator-form"><p className="eyebrow">HOURLY WAGE SETTINGS</p><label>계산 기준<select value={mode} onChange={(event) => updateMode(event.target.value as HourlyWageMode)}><option value="from-monthly">월급에서 시급 계산</option><option value="from-hourly">시급에서 월급 계산</option></select></label><NumberField label={mode === "from-monthly" ? "월급 (세전)" : "시급"} value={amount} onChange={setAmount} unit="원" /><NumberField label="월 환산 근로시간" value={hours} onChange={setHours} unit="시간" min={1} /><CalculatorActions onCalculate={() => setApplied({ mode, amount, hours })} onReset={reset} /></div><div className="calculator-output black-output"><p className="eyebrow">WAGE CONVERSION</p><h2>{mode === "from-monthly" ? "환산 시급" : "환산 월급"}</h2><strong>{won.format(mode === "from-monthly" ? result.hourlyWage : result.monthlyWage)}<small>원</small></strong><div className="result-rows"><ResultRow label="환산 시급" value={`${won.format(result.hourlyWage)}원`} /><ResultRow label="환산 월급" value={`${won.format(result.monthlyWage)}원`} /><ResultRow label="월 환산시간" value={`${number.format(result.monthlyHours)}시간`} /></div></div></section></Meta>;
}

function WorkHoursCalculator() {
  const [start, setStart] = useState("22:00"); const [end, setEnd] = useState("06:00"); const [breakMinutes, setBreakMinutes] = useState(60); const [applied, setApplied] = useState({ start: "22:00", end: "06:00", breakMinutes: 60 }); const result = calculateWorkHours(applied.start, applied.end, applied.breakMinutes);
  const reset = () => { setStart("22:00"); setEnd("06:00"); setBreakMinutes(60); setApplied({ start: "22:00", end: "06:00", breakMinutes: 60 }); };
  const hours = (minutes: number) => `${Math.floor(minutes / 60)}시간 ${minutes % 60}분`;
  return <Meta kind="work-hours"><section className="calculator-layout"><div className="calculator-form"><p className="eyebrow">WORK HOURS SETTINGS</p><label>시작시간<input type="time" value={start} onChange={(event) => setStart(event.target.value)} aria-label="시작시간" /></label><label>종료시간<input type="time" value={end} onChange={(event) => setEnd(event.target.value)} aria-label="종료시간" /></label><NumberField label="휴게시간" value={breakMinutes} onChange={setBreakMinutes} unit="분" /><CalculatorActions onCalculate={() => setApplied({ start, end, breakMinutes })} onReset={reset} /></div><div className="calculator-output black-output"><p className="eyebrow">WORK TIME RESULT</p><h2>실근무시간</h2><strong>{result.valid ? hours(result.workMinutes) : "—"}</strong><div className="result-rows"><ResultRow label="전체 근무시간" value={result.valid ? hours(result.totalMinutes) : "—"} /><ResultRow label="휴게시간" value={result.valid ? hours(result.breakMinutes) : "—"} /><ResultRow label="자정 경과" value={result.crossesMidnight ? "예" : "아니오"} /></div></div></section>{!result.valid && <p className="calculator-notice warning">{result.message}</p>}{result.valid && <p className="calculator-notice">{result.crossesMidnight ? "종료시간을 다음 날로 처리했습니다." : "같은 날짜 안의 근무로 처리했습니다."}</p>}</Meta>;
}

function FourInsuranceCalculator() {
  const [pay, setPay] = useState(3_500_000); const [applied, setApplied] = useState({ pay: 3_500_000 }); const result = calculateFourInsurance(applied.pay); const reset = () => { setPay(3_500_000); setApplied({ pay: 3_500_000 }); };
  const rows = [["국민연금", result.pensionEmployee, result.pensionEmployer], ["건강보험", result.healthEmployee, result.healthEmployer], ["장기요양보험", result.careEmployee, result.careEmployer], ["고용보험", result.employmentEmployee, result.employmentEmployer]];
  return <Meta kind="four-insurance"><section className="calculator-layout"><div className="calculator-form"><p className="eyebrow">SOCIAL INSURANCE SETTINGS</p><NumberField label="월 보수 (세전)" value={pay} onChange={setPay} unit="원" /><CalculatorActions onCalculate={() => setApplied({ pay })} onReset={reset} /></div><div className="calculator-output black-output"><p className="eyebrow">EMPLOYEE CONTRIBUTION</p><h2>근로자 부담 예상액</h2><strong>{won.format(result.employeeTotal)}<small>원</small></strong><div className="result-rows"><ResultRow label="사업주 기본 부담액" value={`${won.format(result.employerBaseTotal)}원`} /><ResultRow label="국민연금 기준소득" value={`${won.format(result.pensionBase)}원`} /></div></div></section><section className="insurance-table-wrap"><table><thead><tr><th>항목</th><th>근로자 부담</th><th>사업주 기본 부담</th></tr></thead><tbody>{rows.map(([label, employee, employer]) => <tr key={label as string}><td>{label}</td><td>{won.format(employee as number)}원</td><td>{won.format(employer as number)}원</td></tr>)}<tr className="total"><td>합계</td><td>{won.format(result.employeeTotal)}원</td><td>{won.format(result.employerBaseTotal)}원</td></tr></tbody></table></section></Meta>;
}

function UnemploymentBenefitCalculator() {
  const [wage, setWage] = useState(3_000_000); const [age, setAge] = useState(35); const [months, setMonths] = useState(24); const [applied, setApplied] = useState({ wage: 3_000_000, age: 35, months: 24 }); const result = calculateUnemploymentBenefit(applied.wage, applied.age, applied.months);
  const reset = () => { setWage(3_000_000); setAge(35); setMonths(24); setApplied({ wage: 3_000_000, age: 35, months: 24 }); };
  return <Meta kind="unemployment-benefit"><section className="calculator-layout"><div className="calculator-form"><p className="eyebrow">UNEMPLOYMENT BENEFIT SETTINGS</p><NumberField label="퇴직 전 월 급여 (세전)" value={wage} onChange={setWage} unit="원" /><NumberField label="퇴직 당시 만 나이" value={age} onChange={setAge} unit="세" /><NumberField label="고용보험 가입기간" value={months} onChange={setMonths} unit="개월" /><CalculatorActions onCalculate={() => setApplied({ wage, age, months })} onReset={reset} /></div><div className="calculator-output black-output"><p className="eyebrow">ESTIMATED JOB-SEEKING BENEFIT</p><h2>예상 총 지급액</h2><strong>{won.format(result.totalBenefit)}<small>원</small></strong><div className="result-rows"><ResultRow label="예상 1일 지급액" value={`${won.format(result.dailyBenefit)}원`} /><ResultRow label="예상 지급일수" value={`${result.payableDays}일`} /><ResultRow label="1일 평균임금" value={`${won.format(result.averageDailyWage)}원`} /></div></div></section><p className={result.eligibleByMonths ? "calculator-notice" : "calculator-notice warning"}>{result.eligibleByMonths ? "가입기간 요건만으로 추정한 결과입니다. 실제 수급자격은 퇴사사유와 피보험단위기간 등을 고용센터가 판단합니다." : "가입기간이 180일 미만으로 입력되어 예상 지급액을 0원으로 표시합니다. 실제 피보험단위기간은 고용센터에서 확인하세요."}</p></Meta>;
}

export default function SalaryEmploymentCalculators({ kind }: { kind: SalaryCalculatorKind }) {
  if (kind === "annual-take-home" || kind === "monthly-take-home") return <PayrollCalculator kind={kind} />;
  if (kind === "retirement-income-tax") return <RetirementIncomeTaxCalculator />;
  if (kind === "weekly-holiday-pay") return <WeeklyHolidayCalculator />;
  if (kind === "annual-leave-pay") return <AnnualLeaveCalculator />;
  if (kind === "hourly-wage") return <HourlyWageCalculator />;
  if (kind === "work-hours") return <WorkHoursCalculator />;
  if (kind === "four-insurance") return <FourInsuranceCalculator />;
  return <UnemploymentBenefitCalculator />;
}
