import { ReactNode, useState } from "react";
import { CatalogBreadcrumb, CalculatorActions, SeoHead, ToolKnowledge, ToolMetaResolver } from "@/components/CatalogSupport";
import { CommaNumberInput } from "@/components/CommaNumberInput";
import { ToolFrame } from "@/components/ToolLayout";
import {
  GiftRelation,
  HealthInsuranceType,
  POLICY_2026,
  calculateCapitalGainsTax,
  calculateComprehensiveIncomeTax,
  calculateGiftTax,
  calculateHealthInsurance,
  calculateInheritanceTax,
  calculateMinimumWageMonthly,
  calculateNationalPensionEstimate,
  calculateYearEndRefund,
} from "@shared/toolbox";

const won = new Intl.NumberFormat("ko-KR", { maximumFractionDigits: 0 });
const number = new Intl.NumberFormat("ko-KR", { maximumFractionDigits: 2 });

type TaxSocialKind = "comprehensive-income-tax" | "capital-gains-tax" | "gift-tax" | "inheritance-tax" | "year-end-tax-refund" | "national-pension" | "health-insurance" | "minimum-wage";
type Spec = { index: string; tag: string; title: string; description: string; method: string; example: string; caution: string };

const specs: Record<TaxSocialKind, Spec> = {
  "comprehensive-income-tax": { index: "38", tag: "TAX / INCOME", title: "종합소득세 계산기", description: "수입금액, 필요경비와 공제를 기준으로 종합소득세를 간이 계산합니다.", method: "수입금액에서 필요경비와 소득공제를 차감해 과세표준을 구하고, 누진세율·세액공제·지방소득세·기납부세액을 차례로 반영합니다.", example: "수입 6,000만원, 필요경비 2,000만원, 소득공제 500만원을 입력해 예상 세액을 확인합니다.", caution: "분리과세, 각 소득별 합산 방식, 결손금, 특별공제와 가산세는 반영하지 않은 참고용 간이 계산입니다." },
  "capital-gains-tax": { index: "39", tag: "TAX / ASSET", title: "양도소득세 계산기", description: "양도가액, 취득가액, 필요경비와 보유기간으로 양도소득세를 간이 계산합니다.", method: "양도가액에서 취득가액·필요경비·기본공제를 차감한 과세표준에 보유기간별 간이 세율 또는 기본 누진세율을 적용합니다.", example: "취득가 5억원, 양도가 7억원, 필요경비 2,000만원, 3년 보유를 입력합니다.", caution: "1세대 1주택 비과세, 다주택 중과, 조정대상지역, 감면·장기보유특별공제와 자산별 특례는 반영하지 않습니다." },
  "gift-tax": { index: "40", tag: "TAX / ASSET", title: "증여세 계산기", description: "증여재산, 관계별 공제와 이전 증여액을 기준으로 증여세를 간이 계산합니다.", method: "증여재산에서 인수 채무를 차감하고 이전 증여액을 합산한 뒤, 관계별 공제와 누진세율·신고세액공제를 반영합니다.", example: "성년 자녀에게 1억원을 증여하는 경우 관계별 공제와 예상 납부세액을 확인합니다.", caution: "특례세율, 세대생략 할증, 재산평가, 비과세·불산입·합산의 세부 요건은 반영하지 않습니다." },
  "inheritance-tax": { index: "41", tag: "TAX / ASSET", title: "상속세 계산기", description: "상속재산, 채무·비용과 공제를 기준으로 상속세를 간이 계산합니다.", method: "상속재산에서 채무·공과·장례비 등 사용자가 입력한 차감액을 빼고 사전증여액을 더한 후 공제·누진세율을 적용합니다.", example: "상속재산 10억원, 채무·비용 5,000만원, 공제 5억원을 입력해 예상 세액을 확인합니다.", caution: "배우자·금융재산·동거주택·가업상속 공제의 요건과 한도, 재산평가·배분은 별도로 확인해야 합니다." },
  "year-end-tax-refund": { index: "42", tag: "TAX / YEAR END", title: "연말정산 환급금 계산기", description: "총급여, 공제와 기납부세액을 바탕으로 환급 또는 추가납부액을 간이 계산합니다.", method: "총급여에서 비과세소득·근로소득공제·인적공제·추가공제를 반영한 과세표준에 세율과 세액공제를 적용하고 기납부세액과 비교합니다.", example: "총급여 5,000만원, 인적공제 1명, 추가공제 300만원, 기납부세액을 입력합니다.", caution: "간소화 자료, 가족공제 중복, 공제 요건·한도, 회사별 원천징수 선택비율에 따라 실제 정산과 달라질 수 있습니다." },
  "national-pension": { index: "43", tag: "LIFE / INSURANCE", title: "국민연금 예상수령액 계산기", description: "기준소득월액과 가입기간으로 노령연금 예상액을 간이 추정합니다.", method: "입력한 기준소득월액과 현재·추가 가입기간을 이용해 간이 소득대체율과 40년 가입기간 기준을 적용합니다.", example: "기준소득월액 350만원, 가입 120개월, 추가 가입 240개월을 입력합니다.", caution: "공단의 실제 가입이력, A값·재평가율, 수급개시연령과 감액·가산이 반영되지 않는 설명용 추정치입니다." },
  "health-insurance": { index: "44", tag: "LIFE / INSURANCE", title: "건강보험료 계산기", description: "직장·지역가입자 기준의 건강보험료와 장기요양보험료를 간이 계산합니다.", method: "직장가입자는 보수월액에 건강보험료율을 적용해 가입자·사용자 부담을 나누고, 지역가입자는 입력한 소득월액과 재산점수를 더해 계산합니다.", example: "직장가입자 보수월액 350만원 또는 지역가입자 소득월액·재산점수를 입력합니다.", caution: "피부양자 자격, 자동차·재산 산정, 경감, 정산과 자격 변동은 반영하지 않습니다." },
  "minimum-wage": { index: "45", tag: "SALARY / MINIMUM WAGE", title: "최저임금 월급 계산기", description: "시급·근로시간·주휴 여부로 주급과 월 예상액을 계산합니다.", method: "1일 근로시간과 주 근무일수로 기본 주급을 계산하고, 주 15시간 이상 및 주휴 포함 조건에서 주휴수당을 더해 월 환산합니다.", example: "2026년 최저시급 10,320원, 1일 8시간, 주 5일, 주휴 포함을 입력합니다.", caution: "수습·적용 제외, 월급제 임금 구성, 연장·야간·휴일근로수당은 근로계약과 최신 법령을 확인해야 합니다." },
};

function NumberField({ label, value, onChange, unit, min = 0 }: { label: string; value: number; onChange: (value: number) => void; unit: string; min?: number }) {
  return <label>{label}<div className="input-suffix"><CommaNumberInput ariaLabel={label} value={value} onValueChange={onChange} min={min} /><span>{unit}</span></div></label>;
}
function ResultRow({ label, value }: { label: string; value: string }) { return <p><span>{label}</span><b>{value}</b></p>; }
function Meta({ kind, children }: { kind: TaxSocialKind; children: ReactNode }) {
  const spec = specs[kind];
  return <ToolMetaResolver slug={kind}>{(tool) => <ToolFrame index={spec.index} tag={spec.tag} title={spec.title} description={spec.description}><SeoHead title={tool.seoTitle ?? tool.title} description={tool.seoDescription ?? tool.description} /><CatalogBreadcrumb toolSlug={tool.slug} />{children}<ToolKnowledge tool={tool} method={spec.method} example={spec.example} caution={spec.caution} /></ToolFrame>}</ToolMetaResolver>;
}
function Notice({ children, warning = false }: { children: ReactNode; warning?: boolean }) { return <p className={warning ? "calculator-notice warning" : "calculator-notice"}>{children}</p>; }

function ComprehensiveIncomeTaxCalculator() {
  const [revenue, setRevenue] = useState(60_000_000); const [expenses, setExpenses] = useState(20_000_000); const [deductions, setDeductions] = useState(5_000_000); const [credits, setCredits] = useState(0); const [prepaid, setPrepaid] = useState(0);
  const [applied, setApplied] = useState({ revenue: 60_000_000, expenses: 20_000_000, deductions: 5_000_000, credits: 0, prepaid: 0 }); const result = calculateComprehensiveIncomeTax(applied.revenue, applied.expenses, applied.deductions, applied.credits, applied.prepaid);
  const reset = () => { const next = { revenue: 60_000_000, expenses: 20_000_000, deductions: 5_000_000, credits: 0, prepaid: 0 }; setRevenue(next.revenue); setExpenses(next.expenses); setDeductions(next.deductions); setCredits(next.credits); setPrepaid(next.prepaid); setApplied(next); };
  return <Meta kind="comprehensive-income-tax"><section className="calculator-layout"><div className="calculator-form"><p className="eyebrow">INCOME TAX SETTINGS</p><NumberField label="수입금액" value={revenue} onChange={setRevenue} unit="원" /><NumberField label="필요경비" value={expenses} onChange={setExpenses} unit="원" /><NumberField label="소득공제 합계" value={deductions} onChange={setDeductions} unit="원" /><NumberField label="세액공제 합계" value={credits} onChange={setCredits} unit="원" /><NumberField label="기납부세액" value={prepaid} onChange={setPrepaid} unit="원" /><CalculatorActions onCalculate={() => setApplied({ revenue, expenses, deductions, credits, prepaid })} onReset={reset} /></div><div className="calculator-output black-output"><p className="eyebrow">ESTIMATED RESULT</p><h2>{result.refund > 0 ? "예상 환급액" : "예상 추가납부액"}</h2><strong>{won.format(result.refund > 0 ? result.refund : result.additionalPayment)}<small>원</small></strong><div className="result-rows"><ResultRow label="총 예상세액" value={`${won.format(result.totalTax)}원`} /><ResultRow label="과세표준" value={`${won.format(result.taxableIncome)}원`} /><ResultRow label="적용 세율" value={`${number.format(result.appliedRate * 100)}%`} /></div></div></section><section className="salary-breakdown"><p className="eyebrow">CALCULATION DETAIL</p><h2>계산 과정</h2><div className="salary-breakdown-grid"><ResultRow label="소득금액" value={`${won.format(result.incomeAmount)}원`} /><ResultRow label="소득공제" value={`${won.format(result.incomeDeductions)}원`} /><ResultRow label="산출 소득세" value={`${won.format(result.calculatedIncomeTax)}원`} /><ResultRow label="세액공제" value={`${won.format(result.taxCredits)}원`} /><ResultRow label="지방소득세" value={`${won.format(result.localIncomeTax)}원`} /><ResultRow label="기납부세액" value={`${won.format(result.prepaidTax)}원`} /></div></section><Notice>입력값이 비어 있거나 음수인 금액은 0원으로 정규화합니다. 실제 신고 전에는 국세청 기준을 확인하세요.</Notice></Meta>;
}

function CapitalGainsTaxCalculator() {
  const [sale, setSale] = useState(700_000_000); const [purchase, setPurchase] = useState(500_000_000); const [expenses, setExpenses] = useState(20_000_000); const [acquired, setAcquired] = useState("2021-01-01"); const [transferred, setTransferred] = useState("2025-01-01");
  const [applied, setApplied] = useState({ sale: 700_000_000, purchase: 500_000_000, expenses: 20_000_000, acquired: "2021-01-01", transferred: "2025-01-01" }); const result = calculateCapitalGainsTax(applied.sale, applied.purchase, applied.expenses, applied.acquired, applied.transferred);
  const reset = () => { const next = { sale: 700_000_000, purchase: 500_000_000, expenses: 20_000_000, acquired: "2021-01-01", transferred: "2025-01-01" }; setSale(next.sale); setPurchase(next.purchase); setExpenses(next.expenses); setAcquired(next.acquired); setTransferred(next.transferred); setApplied(next); };
  return <Meta kind="capital-gains-tax"><section className="calculator-layout"><div className="calculator-form"><p className="eyebrow">CAPITAL GAINS SETTINGS</p><NumberField label="양도가액" value={sale} onChange={setSale} unit="원" /><NumberField label="취득가액" value={purchase} onChange={setPurchase} unit="원" /><NumberField label="필요경비·양도비" value={expenses} onChange={setExpenses} unit="원" /><label>취득일<input type="date" value={acquired} onChange={(event) => setAcquired(event.target.value)} /></label><label>양도일<input type="date" value={transferred} onChange={(event) => setTransferred(event.target.value)} /></label><CalculatorActions onCalculate={() => setApplied({ sale, purchase, expenses, acquired, transferred })} onReset={reset} /></div><div className="calculator-output black-output"><p className="eyebrow">ESTIMATED CAPITAL GAINS TAX</p><h2>총 예상 세액</h2><strong>{result.valid ? `${won.format(result.totalTax)}원` : "—"}</strong><div className="result-rows"><ResultRow label="양도차익" value={result.valid ? `${won.format(result.gain)}원` : "—"} /><ResultRow label="과세표준" value={result.valid ? `${won.format(result.taxBase)}원` : "—"} /><ResultRow label="보유기간" value={result.valid ? `${number.format(result.holdingYears)}년` : "—"} /></div></div></section><Notice warning={!result.valid}>{result.message || `적용 세율 ${number.format(result.rate * 100)}%, 지방소득세 ${won.format(result.localIncomeTax)}원이 포함되었습니다.`}</Notice></Meta>;
}

function GiftTaxCalculator() {
  const [asset, setAsset] = useState(100_000_000); const [debt, setDebt] = useState(0); const [relation, setRelation] = useState<GiftRelation>("ascendant"); const [minor, setMinor] = useState(false); const [previous, setPrevious] = useState(0);
  const [applied, setApplied] = useState({ asset: 100_000_000, debt: 0, relation: "ascendant" as GiftRelation, minor: false, previous: 0 }); const result = calculateGiftTax(applied.asset, applied.debt, applied.relation, applied.minor, applied.previous);
  const reset = () => { const next = { asset: 100_000_000, debt: 0, relation: "ascendant" as GiftRelation, minor: false, previous: 0 }; setAsset(next.asset); setDebt(next.debt); setRelation(next.relation); setMinor(next.minor); setPrevious(next.previous); setApplied(next); };
  return <Meta kind="gift-tax"><section className="calculator-layout"><div className="calculator-form"><p className="eyebrow">GIFT TAX SETTINGS</p><NumberField label="증여재산가액" value={asset} onChange={setAsset} unit="원" /><NumberField label="인수 채무" value={debt} onChange={setDebt} unit="원" /><label>증여자와의 관계<select value={relation} onChange={(event) => setRelation(event.target.value as GiftRelation)}><option value="spouse">배우자</option><option value="ascendant">직계존속</option><option value="descendant">직계비속</option><option value="relative">기타 친족</option><option value="other">그 외</option></select></label><label className="checkbox-field"><input type="checkbox" checked={minor} onChange={(event) => setMinor(event.target.checked)} />수증자는 미성년자</label><NumberField label="10년 내 이전 증여액" value={previous} onChange={setPrevious} unit="원" /><CalculatorActions onCalculate={() => setApplied({ asset, debt, relation, minor, previous })} onReset={reset} /></div><div className="calculator-output black-output"><p className="eyebrow">ESTIMATED GIFT TAX</p><h2>예상 납부세액</h2><strong>{won.format(result.estimatedPayment)}<small>원</small></strong><div className="result-rows"><ResultRow label="과세표준" value={`${won.format(result.taxBase)}원`} /><ResultRow label="관계별 공제" value={`${won.format(result.allowance)}원`} /><ResultRow label="적용 세율" value={`${number.format(result.appliedRate * 100)}%`} /></div></div></section><section className="salary-breakdown"><p className="eyebrow">CALCULATION DETAIL</p><h2>계산 과정</h2><div className="salary-breakdown-grid"><ResultRow label="순증여재산" value={`${won.format(result.assetValue - result.assumedDebt)}원`} /><ResultRow label="이전 증여 합산" value={`${won.format(result.previousGifts)}원`} /><ResultRow label="산출세액" value={`${won.format(result.calculatedTax)}원`} /><ResultRow label="신고세액공제(3%)" value={`${won.format(result.filingCredit)}원`} /></div></section></Meta>;
}

function InheritanceTaxCalculator() {
  const [asset, setAsset] = useState(1_000_000_000); const [debts, setDebts] = useState(50_000_000); const [deductions, setDeductions] = useState(500_000_000); const [previous, setPrevious] = useState(0);
  const [applied, setApplied] = useState({ asset: 1_000_000_000, debts: 50_000_000, deductions: 500_000_000, previous: 0 }); const result = calculateInheritanceTax(applied.asset, applied.debts, applied.deductions, applied.previous);
  const reset = () => { const next = { asset: 1_000_000_000, debts: 50_000_000, deductions: 500_000_000, previous: 0 }; setAsset(next.asset); setDebts(next.debts); setDeductions(next.deductions); setPrevious(next.previous); setApplied(next); };
  return <Meta kind="inheritance-tax"><section className="calculator-layout"><div className="calculator-form"><p className="eyebrow">INHERITANCE TAX SETTINGS</p><NumberField label="상속재산가액" value={asset} onChange={setAsset} unit="원" /><NumberField label="채무·공과·장례비 등" value={debts} onChange={setDebts} unit="원" /><NumberField label="상속공제 합계" value={deductions} onChange={setDeductions} unit="원" /><NumberField label="사전증여 합산액" value={previous} onChange={setPrevious} unit="원" /><CalculatorActions onCalculate={() => setApplied({ asset, debts, deductions, previous })} onReset={reset} /></div><div className="calculator-output black-output"><p className="eyebrow">ESTIMATED INHERITANCE TAX</p><h2>예상 납부세액</h2><strong>{won.format(result.estimatedPayment)}<small>원</small></strong><div className="result-rows"><ResultRow label="순상속 과세가액" value={`${won.format(result.taxableEstate)}원`} /><ResultRow label="과세표준" value={`${won.format(result.taxBase)}원`} /><ResultRow label="적용 세율" value={`${number.format(result.appliedRate * 100)}%`} /></div></div></section><Notice>신고세액공제 3%를 반영한 간이 결과입니다. 상속재산의 평가와 공제의 법정 요건은 별도로 확인하세요.</Notice></Meta>;
}

function YearEndRefundCalculator() {
  const [gross, setGross] = useState(50_000_000); const [nonTaxable, setNonTaxable] = useState(2_400_000); const [dependents, setDependents] = useState(1); const [deductions, setDeductions] = useState(3_000_000); const [credits, setCredits] = useState(500_000); const [incomePrepaid, setIncomePrepaid] = useState(2_000_000); const [localPrepaid, setLocalPrepaid] = useState(200_000);
  const [applied, setApplied] = useState({ gross: 50_000_000, nonTaxable: 2_400_000, dependents: 1, deductions: 3_000_000, credits: 500_000, incomePrepaid: 2_000_000, localPrepaid: 200_000 }); const result = calculateYearEndRefund(applied.gross, applied.nonTaxable, applied.dependents, applied.deductions, applied.credits, applied.incomePrepaid, applied.localPrepaid);
  const reset = () => { const next = { gross: 50_000_000, nonTaxable: 2_400_000, dependents: 1, deductions: 3_000_000, credits: 500_000, incomePrepaid: 2_000_000, localPrepaid: 200_000 }; setGross(next.gross); setNonTaxable(next.nonTaxable); setDependents(next.dependents); setDeductions(next.deductions); setCredits(next.credits); setIncomePrepaid(next.incomePrepaid); setLocalPrepaid(next.localPrepaid); setApplied(next); };
  return <Meta kind="year-end-tax-refund"><section className="calculator-layout"><div className="calculator-form"><p className="eyebrow">YEAR-END SETTINGS</p><NumberField label="총급여" value={gross} onChange={setGross} unit="원" /><NumberField label="비과세 급여" value={nonTaxable} onChange={setNonTaxable} unit="원" /><NumberField label="부양가족 수(본인 포함)" value={dependents} onChange={setDependents} unit="명" min={1} /><NumberField label="추가 소득공제" value={deductions} onChange={setDeductions} unit="원" /><NumberField label="세액공제 합계" value={credits} onChange={setCredits} unit="원" /><NumberField label="기납부 소득세" value={incomePrepaid} onChange={setIncomePrepaid} unit="원" /><NumberField label="기납부 지방소득세" value={localPrepaid} onChange={setLocalPrepaid} unit="원" /><CalculatorActions onCalculate={() => setApplied({ gross, nonTaxable, dependents, deductions, credits, incomePrepaid, localPrepaid })} onReset={reset} /></div><div className="calculator-output black-output"><p className="eyebrow">YEAR-END RESULT</p><h2>{result.refund > 0 ? "예상 환급액" : "예상 추가납부액"}</h2><strong>{won.format(result.refund > 0 ? result.refund : result.additionalPayment)}<small>원</small></strong><div className="result-rows"><ResultRow label="결정세액" value={`${won.format(result.finalTax)}원`} /><ResultRow label="기납부세액" value={`${won.format(result.prepaid)}원`} /><ResultRow label="과세표준" value={`${won.format(result.taxBase)}원`} /></div></div></section></Meta>;
}

function NationalPensionCalculator() {
  const [income, setIncome] = useState(3_500_000); const [insured, setInsured] = useState(120); const [additional, setAdditional] = useState(240); const [applied, setApplied] = useState({ income: 3_500_000, insured: 120, additional: 240 }); const result = calculateNationalPensionEstimate(applied.income, applied.insured, applied.additional);
  const reset = () => { const next = { income: 3_500_000, insured: 120, additional: 240 }; setIncome(next.income); setInsured(next.insured); setAdditional(next.additional); setApplied(next); };
  return <Meta kind="national-pension"><section className="calculator-layout"><div className="calculator-form"><p className="eyebrow">NATIONAL PENSION SETTINGS</p><NumberField label="기준소득월액" value={income} onChange={setIncome} unit="원" /><NumberField label="현재 가입기간" value={insured} onChange={setInsured} unit="개월" /><NumberField label="예상 추가 가입기간" value={additional} onChange={setAdditional} unit="개월" /><CalculatorActions onCalculate={() => setApplied({ income, insured, additional })} onReset={reset} /></div><div className="calculator-output black-output"><p className="eyebrow">SIMPLIFIED PENSION ESTIMATE</p><h2>월 예상 노령연금</h2><strong>{result.eligible ? won.format(result.estimatedMonthlyPension) : "수급요건 확인"}<small>{result.eligible ? "원" : ""}</small></strong><div className="result-rows"><ResultRow label="총 가입기간" value={`${number.format(result.totalYears)}년`} /><ResultRow label="가입요건" value={result.eligible ? "10년 이상 충족" : `10년까지 ${result.requiredMonths - result.totalMonths}개월 부족`} /><ResultRow label="연 예상액" value={`${won.format(result.estimatedAnnualPension)}원`} /></div></div></section><Notice warning={!result.eligible}>{result.eligible ? "2026년 기준소득월액 상한을 적용한 간이 추정입니다. 실제 예상연금은 국민연금공단 조회로 확인하세요." : "노령연금은 일반적으로 가입기간 10년 이상 요건을 확인해야 합니다. 이 결과는 수급자격 판정이 아닙니다."}</Notice></Meta>;
}

function HealthInsuranceCalculator() {
  const [type, setType] = useState<HealthInsuranceType>("workplace"); const [income, setIncome] = useState(3_500_000); const [points, setPoints] = useState(0); const [applied, setApplied] = useState({ type: "workplace" as HealthInsuranceType, income: 3_500_000, points: 0 }); const result = calculateHealthInsurance(applied.type, applied.income, applied.points);
  const reset = () => { const next = { type: "workplace" as HealthInsuranceType, income: 3_500_000, points: 0 }; setType(next.type); setIncome(next.income); setPoints(next.points); setApplied(next); };
  return <Meta kind="health-insurance"><section className="calculator-layout"><div className="calculator-form"><p className="eyebrow">HEALTH INSURANCE SETTINGS</p><label>가입 유형<select value={type} onChange={(event) => setType(event.target.value as HealthInsuranceType)}><option value="workplace">직장가입자</option><option value="regional">지역가입자</option></select></label><NumberField label={type === "workplace" ? "보수월액" : "소득월액"} value={income} onChange={setIncome} unit="원" />{type === "regional" && <NumberField label="재산 보험료부과점수" value={points} onChange={setPoints} unit="점" />}<CalculatorActions onCalculate={() => setApplied({ type, income, points })} onReset={reset} /></div><div className="calculator-output black-output"><p className="eyebrow">MONTHLY CONTRIBUTION</p><h2>월 예상 부담액</h2><strong>{won.format(result.totalContribution)}<small>원</small></strong><div className="result-rows"><ResultRow label="건강보험료" value={`${won.format(result.healthContribution)}원`} /><ResultRow label="장기요양보험료" value={`${won.format(result.careContribution)}원`} /><ResultRow label="가입 유형" value={result.type === "workplace" ? "직장가입자" : "지역가입자"} /></div></div></section>{result.type === "workplace" && <Notice>사용자 부담 참고액은 건강보험료 {won.format(result.employerHealth)}원, 장기요양보험료 {won.format(result.employerCare)}원입니다.</Notice>}<Notice>2026년 건강보험료율과 장기요양보험료율을 적용한 간이 결과입니다.</Notice></Meta>;
}

function MinimumWageCalculator() {
  const [hourly, setHourly] = useState<number>(POLICY_2026.minimumHourlyWage); const [hours, setHours] = useState(8); const [days, setDays] = useState(5); const [weeklyHoliday, setWeeklyHoliday] = useState(true); const [applied, setApplied] = useState<{ hourly: number; hours: number; days: number; weeklyHoliday: boolean }>({ hourly: POLICY_2026.minimumHourlyWage, hours: 8, days: 5, weeklyHoliday: true }); const result = calculateMinimumWageMonthly(applied.hourly, applied.hours, applied.days, applied.weeklyHoliday);
  const reset = () => { const next = { hourly: POLICY_2026.minimumHourlyWage, hours: 8, days: 5, weeklyHoliday: true }; setHourly(next.hourly); setHours(next.hours); setDays(next.days); setWeeklyHoliday(next.weeklyHoliday); setApplied(next); };
  return <Meta kind="minimum-wage"><section className="calculator-layout"><div className="calculator-form"><p className="eyebrow">MINIMUM WAGE SETTINGS</p><NumberField label="시급" value={hourly} onChange={setHourly} unit="원" /><NumberField label="1일 소정근로시간" value={hours} onChange={setHours} unit="시간" /><NumberField label="주 근무일수" value={days} onChange={setDays} unit="일" min={1} /><label className="checkbox-field"><input type="checkbox" checked={weeklyHoliday} onChange={(event) => setWeeklyHoliday(event.target.checked)} />유급 주휴 포함</label><CalculatorActions onCalculate={() => setApplied({ hourly, hours, days, weeklyHoliday })} onReset={reset} /></div><div className="calculator-output black-output"><p className="eyebrow">MONTHLY WAGE ESTIMATE</p><h2>월 예상 급여</h2><strong>{won.format(result.estimatedMonthlyPay)}<small>원</small></strong><div className="result-rows"><ResultRow label="기본 주급" value={`${won.format(result.weeklyBasic)}원`} /><ResultRow label="주휴수당" value={`${won.format(result.weeklyHoliday)}원`} /><ResultRow label="월 환산시간" value={`${number.format(result.monthlyHours)}시간`} /></div></div></section><Notice warning={!result.meetsMinimum}>{result.meetsMinimum ? `입력 시급은 2026년 최저시급 ${won.format(result.legalMinimumHourly)}원 이상입니다.` : `입력 시급은 2026년 최저시급 ${won.format(result.legalMinimumHourly)}원보다 낮습니다.`}</Notice></Meta>;
}

export default function TaxSocialCalculators({ kind }: { kind: TaxSocialKind }) {
  if (kind === "comprehensive-income-tax") return <ComprehensiveIncomeTaxCalculator />;
  if (kind === "capital-gains-tax") return <CapitalGainsTaxCalculator />;
  if (kind === "gift-tax") return <GiftTaxCalculator />;
  if (kind === "inheritance-tax") return <InheritanceTaxCalculator />;
  if (kind === "year-end-tax-refund") return <YearEndRefundCalculator />;
  if (kind === "national-pension") return <NationalPensionCalculator />;
  if (kind === "health-insurance") return <HealthInsuranceCalculator />;
  return <MinimumWageCalculator />;
}
