export type CatalogStatus = "active" | "inactive" | "draft";
export type CatalogKind = "calculator" | "converter" | "unit";

export type CatalogCategory = {
  id: number;
  parentId: number | null;
  name: string;
  slug: string;
  description: string | null;
  icon: string | null;
  sortOrder: number;
  status: CatalogStatus;
  seoTitle: string | null;
  seoDescription: string | null;
};

export type CatalogTool = {
  id: number;
  categoryId: number;
  slug: string;
  title: string;
  description: string;
  kind: CatalogKind;
  inputs: Record<string, unknown> | null;
  formula: string | null;
  faq: Array<{ question: string; answer: string }> | null;
  relatedToolIds: number[] | null;
  seoTitle: string | null;
  seoDescription: string | null;
  status: CatalogStatus;
  sortOrder: number;
  logicKey: string | null;
  isPopular?: boolean;
  searchKeywords?: string[] | null;
};

export type CatalogSnapshot = { categories: CatalogCategory[]; tools: CatalogTool[] };

export const rootPathBySlug: Record<string, string> = {
  calculator: "/calculator",
  convert: "/convert",
  units: "/units",
};

export const legacyToolPaths: Record<string, string> = {
  "monthly-rent": "/rent",
  "loan-interest": "/loan",
  "vat-calculator": "/vat",
  "pdf-convert": "/pdf",
  "image-convert": "/image",
  "unit-convert": "/unit",
};

function findCategory(id: number | null, categories: CatalogCategory[]) {
  return id === null ? undefined : categories.find((item) => item.id === id);
}

export function getCategoryLineage(category: CatalogCategory, categories: CatalogCategory[]) {
  const lineage: CatalogCategory[] = [];
  let current: CatalogCategory | undefined = category;
  while (current) {
    lineage.unshift(current);
    current = findCategory(current.parentId, categories);
  }
  return lineage;
}

export function getRootCategory(category: CatalogCategory, categories: CatalogCategory[]) {
  return getCategoryLineage(category, categories)[0];
}

export function getRootPath(root: CatalogCategory) {
  return rootPathBySlug[root.slug] ?? `/catalog/${root.slug}`;
}

export function getToolPath(tool: CatalogTool, categories: CatalogCategory[]) {
  const category = findCategory(tool.categoryId, categories);
  if (!category) return "/";
  const lineage = getCategoryLineage(category, categories);
  const root = lineage[0];
  const firstBranch = lineage[1];
  if (!root) return "/";
  return firstBranch ? `${getRootPath(root)}/${firstBranch.slug}/${tool.slug}` : `${getRootPath(root)}/${tool.slug}`;
}

export function getCategoryPath(category: CatalogCategory, categories: CatalogCategory[]) {
  const lineage = getCategoryLineage(category, categories);
  const root = lineage[0];
  const firstBranch = lineage[1];
  if (!root) return "/";
  return firstBranch ? `${getRootPath(root)}/${firstBranch.slug}` : getRootPath(root);
}

const tool = (values: Omit<CatalogTool, "isPopular" | "searchKeywords"> & { isPopular?: boolean; searchKeywords?: string[] }): CatalogTool => values;

export const defaultCatalog: CatalogSnapshot = {
  categories: [
    { id: 1, parentId: null, name: "계산기", slug: "calculator", description: "생활과 업무에 필요한 계산기", icon: "Calculator", sortOrder: 1, status: "active", seoTitle: "실용 계산기 모음", seoDescription: "금융, 부동산, 급여, 세금 계산기를 제공합니다." },
    { id: 2, parentId: 1, name: "금융 계산기", slug: "finance", description: "대출, 이자와 비율 관련 계산", icon: "Landmark", sortOrder: 1, status: "active", seoTitle: "금융 계산기", seoDescription: "대출 상환, 이자, 수익과 비율을 계산합니다." },
    { id: 3, parentId: 1, name: "부동산 계산기", slug: "real-estate", description: "전월세, 대출, 비용과 세금 계산", icon: "Building2", sortOrder: 2, status: "active", seoTitle: "부동산 계산기", seoDescription: "전월세, 주택 대출, 부동산 비용과 세금을 계산합니다." },
    { id: 4, parentId: 1, name: "급여·직장인 계산기", slug: "salary", description: "급여와 퇴직금 추정", icon: "WalletCards", sortOrder: 3, status: "active", seoTitle: "급여 계산기", seoDescription: "연봉 실수령액과 퇴직금을 추정합니다." },
    { id: 5, parentId: 1, name: "세금 계산기", slug: "tax", description: "사업과 생활 세금 계산", icon: "ReceiptText", sortOrder: 4, status: "active", seoTitle: "세금 계산기", seoDescription: "부가세를 간편하게 계산합니다." },
    { id: 6, parentId: 1, name: "생활 계산기", slug: "lifestyle", description: "일상에서 쓰는 계산", icon: "Clock3", sortOrder: 5, status: "active", seoTitle: "생활 계산기", seoDescription: "일상 생활 계산 도구를 제공합니다." },
    { id: 7, parentId: 1, name: "건강 계산기", slug: "health", description: "건강 지표 계산", icon: "HeartPulse", sortOrder: 6, status: "active", seoTitle: "건강 계산기", seoDescription: "건강 관련 계산 도구입니다." },
    { id: 8, parentId: null, name: "파일 변환", slug: "convert", description: "브라우저 안에서 처리하는 파일 도구", icon: "FileOutput", sortOrder: 2, status: "active", seoTitle: "파일 변환 도구", seoDescription: "PDF와 이미지를 브라우저에서 변환합니다." },
    { id: 9, parentId: 8, name: "PDF 변환", slug: "pdf", description: "PDF와 이미지 변환", icon: "FileText", sortOrder: 1, status: "active", seoTitle: "PDF 변환", seoDescription: "PDF 페이지를 PNG 또는 JPG 이미지로 변환하고 이미지를 PDF로 만듭니다." },
    { id: 10, parentId: 8, name: "PDF 편집", slug: "pdf-edit", description: "PDF 편집 도구", icon: "FilePenLine", sortOrder: 2, status: "active", seoTitle: "PDF 편집", seoDescription: "PDF 합치기, 분할, 페이지 추출·삭제·순서 변경·회전을 브라우저에서 처리합니다." },
    { id: 11, parentId: 8, name: "이미지 변환", slug: "image", description: "이미지 포맷과 크기 변환", icon: "Image", sortOrder: 3, status: "active", seoTitle: "이미지 변환", seoDescription: "JPG, PNG, WebP를 변환합니다." },
    { id: 12, parentId: 8, name: "문서 변환", slug: "document", description: "문서 파일 변환", icon: "Files", sortOrder: 4, status: "active", seoTitle: "문서 변환", seoDescription: "CSV, Excel, JSON, TXT를 브라우저에서 변환합니다." },
    { id: 13, parentId: 8, name: "파일 압축", slug: "compression", description: "파일 크기 최적화", icon: "Archive", sortOrder: 5, status: "active", seoTitle: "파일 압축", seoDescription: "PDF와 이미지를 브라우저에서 실제로 재인코딩해 용량을 줄입니다." },
    { id: 14, parentId: null, name: "단위 변환", slug: "units", description: "자주 쓰는 단위 환산", icon: "Ruler", sortOrder: 3, status: "active", seoTitle: "단위 변환기", seoDescription: "길이, 면적, 무게, 온도를 변환합니다." },
    { id: 15, parentId: 14, name: "길이", slug: "length", description: "길이 단위 변환", icon: "MoveHorizontal", sortOrder: 1, status: "active", seoTitle: "길이 단위 변환", seoDescription: "길이 단위를 빠르게 변환합니다." },
    { id: 16, parentId: 14, name: "면적", slug: "area", description: "면적과 평수 변환", icon: "SquareDashed", sortOrder: 2, status: "active", seoTitle: "면적 단위 변환", seoDescription: "면적과 평수를 변환합니다." },
    { id: 17, parentId: 14, name: "무게", slug: "weight", description: "무게 단위 변환", icon: "Weight", sortOrder: 3, status: "active", seoTitle: "무게 단위 변환", seoDescription: "무게 단위를 변환합니다." },
    { id: 18, parentId: 14, name: "부피", slug: "volume", description: "부피 단위 변환", icon: "FlaskConical", sortOrder: 4, status: "active", seoTitle: "부피 단위 변환", seoDescription: "부피 단위를 변환합니다." },
    { id: 19, parentId: 14, name: "온도", slug: "temperature", description: "온도 단위 변환", icon: "Thermometer", sortOrder: 5, status: "active", seoTitle: "온도 단위 변환", seoDescription: "온도 단위를 변환합니다." },
    { id: 20, parentId: 14, name: "속도", slug: "speed", description: "속도 단위 변환", icon: "Gauge", sortOrder: 6, status: "active", seoTitle: "속도 단위 변환", seoDescription: "속도 단위를 변환합니다." },
    { id: 21, parentId: 14, name: "데이터", slug: "data", description: "데이터 용량 변환", icon: "Database", sortOrder: 7, status: "active", seoTitle: "데이터 단위 변환", seoDescription: "데이터 단위를 변환합니다." },
    { id: 22, parentId: 3, name: "대출", slug: "real-estate-loan", description: "전세·주택담보 대출 비용", icon: "Landmark", sortOrder: 1, status: "active", seoTitle: "부동산 대출 계산기", seoDescription: "전세대출 이자와 주택담보대출 상환액을 계산합니다." },
    { id: 23, parentId: 3, name: "부동산 비용", slug: "real-estate-cost", description: "중도상환·중개보수 비용", icon: "BadgeDollarSign", sortOrder: 2, status: "active", seoTitle: "부동산 비용 계산기", seoDescription: "중도상환수수료와 부동산 중개보수를 계산합니다." },
    { id: 24, parentId: 3, name: "부동산 세금", slug: "real-estate-tax", description: "주택 취득·보유 세금", icon: "Landmark", sortOrder: 3, status: "active", seoTitle: "부동산 세금 계산기", seoDescription: "취득세와 재산세의 기본 계산을 제공합니다." },
    { id: 25, parentId: 2, name: "이자·수익", slug: "finance-return", description: "복리 수익 계산", icon: "ChartNoAxesCombined", sortOrder: 1, status: "active", seoTitle: "이자 수익 계산기", seoDescription: "복리 기준의 원금과 이자를 계산합니다." },
    { id: 26, parentId: 2, name: "대출", slug: "finance-loan", description: "상환 방식별 대출 계산", icon: "CircleDollarSign", sortOrder: 2, status: "active", seoTitle: "대출 상환 계산기", seoDescription: "원금균등과 만기일시상환을 계산합니다." },
    { id: 27, parentId: 2, name: "퍼센트·비율", slug: "finance-percentage", description: "비율과 증감 계산", icon: "Percent", sortOrder: 3, status: "active", seoTitle: "퍼센트 계산기", seoDescription: "퍼센트 값과 증감률을 계산합니다." },
    { id: 28, parentId: 4, name: "급여", slug: "salary-pay", description: "연봉·월급 실수령액과 4대보험", icon: "WalletCards", sortOrder: 1, status: "active", seoTitle: "급여 계산기", seoDescription: "연봉과 월급의 예상 실수령액, 4대보험을 계산합니다." },
    { id: 29, parentId: 4, name: "근로·수당", slug: "salary-allowance", description: "주휴·연차·시급·근무시간", icon: "Clock3", sortOrder: 2, status: "active", seoTitle: "근로 수당 계산기", seoDescription: "주휴수당, 연차수당, 시급과 근무시간을 계산합니다." },
    { id: 30, parentId: 4, name: "퇴직·고용", slug: "salary-retirement", description: "퇴직금·퇴직소득세·실업급여", icon: "BriefcaseBusiness", sortOrder: 3, status: "active", seoTitle: "퇴직 및 고용 계산기", seoDescription: "퇴직금, 퇴직소득세와 실업급여를 추정합니다." },
    { id: 31, parentId: 5, name: "소득·신고", slug: "tax-income", description: "종합소득세와 신고 전 예상 세액", icon: "FileText", sortOrder: 1, status: "active", seoTitle: "소득·신고 세금 계산기", seoDescription: "종합소득세와 연말정산 예상 세액을 간이 계산합니다." },
    { id: 32, parentId: 5, name: "자산·부동산 세금", slug: "tax-assets", description: "양도·증여·상속 관련 간이 세금 계산", icon: "Landmark", sortOrder: 2, status: "active", seoTitle: "자산 세금 계산기", seoDescription: "양도소득세, 증여세, 상속세의 예상 세액을 계산합니다." },
    { id: 33, parentId: 5, name: "연말정산", slug: "tax-year-end", description: "근로소득 연말정산 예상 환급", icon: "ReceiptText", sortOrder: 3, status: "active", seoTitle: "연말정산 계산기", seoDescription: "기납부세액과 공제를 기준으로 환급 또는 추가납부를 추정합니다." },
    { id: 34, parentId: 6, name: "사회보험", slug: "lifestyle-insurance", description: "국민연금과 건강보험료", icon: "HeartPulse", sortOrder: 1, status: "active", seoTitle: "사회보험 계산기", seoDescription: "국민연금 예상액과 건강보험료를 간이 계산합니다." },
    { id: 35, parentId: 1, name: "날짜·시간 계산기", slug: "date", description: "날짜, D-Day, 나이와 시간 계산", icon: "CalendarDays", sortOrder: 7, status: "active", seoTitle: "날짜와 시간 계산기", seoDescription: "날짜 차이, D-Day, 나이와 시간 연산을 계산합니다." },
    { id: 36, parentId: 35, name: "날짜 연산", slug: "date-operation", description: "날짜 더하기, 빼기와 기간 계산", icon: "CalendarRange", sortOrder: 1, status: "active", seoTitle: "날짜 연산 계산기", seoDescription: "기준일에서 날짜를 더하거나 빼고 날짜 차이를 계산합니다." },
    { id: 37, parentId: 35, name: "나이", slug: "date-age", description: "만 나이와 세는 나이 계산", icon: "Cake", sortOrder: 2, status: "active", seoTitle: "나이 계산기", seoDescription: "생년월일과 기준일로 만 나이와 세는 나이를 계산합니다." },
    { id: 38, parentId: 14, name: "시간", slug: "time", description: "시간 단위 변환", icon: "Clock3", sortOrder: 8, status: "active", seoTitle: "시간 단위 변환", seoDescription: "초, 분, 시간, 일을 빠르게 환산합니다." },
    { id: 39, parentId: 14, name: "압력", slug: "pressure", description: "압력 단위 변환", icon: "Gauge", sortOrder: 9, status: "active", seoTitle: "압력 단위 변환", seoDescription: "Pa, bar, atm, psi를 변환합니다." },
    { id: 40, parentId: 14, name: "에너지", slug: "energy", description: "에너지 단위 변환", icon: "Zap", sortOrder: 10, status: "active", seoTitle: "에너지 단위 변환", seoDescription: "J, cal, Wh, kWh를 변환합니다." },
  ],
  tools: [
    tool({ id: 101, categoryId: 3, slug: "monthly-rent", title: "월세 계산기", description: "보증금·월세·전환율로 실질 월 지출을 계산합니다.", kind: "calculator", inputs: null, formula: "실질 월 지출 = 월세 + (보증금 × 전환율 ÷ 12)", faq: null, relatedToolIds: [104, 107, 108, 109], seoTitle: "월세 계산기 | 도구상자", seoDescription: "보증금과 월세를 바탕으로 실질 월 지출을 계산합니다.", status: "active", sortOrder: 1, logicKey: "monthly-rent", isPopular: true, searchKeywords: ["월세", "보증금", "전월세"] }),
    tool({ id: 102, categoryId: 2, slug: "loan-interest", title: "대출 이자 계산기", description: "원리금균등과 원금균등 상환 방식의 이자를 비교합니다.", kind: "calculator", inputs: null, formula: "월 이자율 = 연 이자율 ÷ 12", faq: null, relatedToolIds: [110, 120, 121, 115], seoTitle: "대출 이자 계산기 | 도구상자", seoDescription: "대출 상환 방식별 월 납입금과 총 이자를 계산합니다.", status: "active", sortOrder: 1, logicKey: "loan-interest", isPopular: true, searchKeywords: ["대출", "이자", "원리금", "상환"] }),
    tool({ id: 103, categoryId: 4, slug: "annual-net", title: "연봉 실수령액 계산기", description: "4대 보험과 간이 소득세를 반영해 월 예상 실수령액을 추정합니다.", kind: "calculator", inputs: null, formula: "월 실수령액 ≈ 월 급여 − 사회보험료 − 추정 소득세", faq: null, relatedToolIds: [105], seoTitle: "연봉 실수령액 계산기 | 도구상자", seoDescription: "연봉 기준 월 예상 실수령액을 추정합니다.", status: "active", sortOrder: 1, logicKey: "annual-net", searchKeywords: ["연봉", "실수령", "월급"] }),
    tool({ id: 104, categoryId: 3, slug: "pyeong", title: "평수 계산기", description: "제곱미터와 평을 양방향으로 변환합니다.", kind: "calculator", inputs: null, formula: "1평 = 3.305785㎡", faq: null, relatedToolIds: [101], seoTitle: "평수 계산기 | 도구상자", seoDescription: "제곱미터와 평을 빠르게 변환합니다.", status: "active", sortOrder: 2, logicKey: "pyeong", isPopular: true, searchKeywords: ["평", "제곱미터", "면적", "평수 계산", "㎡"] }),
    tool({ id: 105, categoryId: 30, slug: "retirement-pay", title: "퇴직금 계산기", description: "평균 임금과 근속 기간으로 예상 퇴직금을 계산합니다.", kind: "calculator", inputs: null, formula: "예상 퇴직금 = 1일 평균임금 × 30일 × 계속 근로연수", faq: null, relatedToolIds: [103, 130, 127, 129, 131], seoTitle: "퇴직금 계산기 | 도구상자", seoDescription: "평균 임금과 근속 기간으로 퇴직금을 추정합니다.", status: "active", sortOrder: 0, logicKey: "retirement-pay", isPopular: true, searchKeywords: ["퇴직", "퇴직금", "평균임금", "퇴직 정산"] }),
    tool({ id: 106, categoryId: 5, slug: "vat-calculator", title: "부가세 계산기", description: "공급가액과 부가세 포함 금액을 양방향 계산합니다.", kind: "calculator", inputs: null, formula: "부가세 = 공급가액 × 10%", faq: null, relatedToolIds: [132, 136, 122], seoTitle: "부가세 계산기 | 도구상자", seoDescription: "공급가액과 부가세 포함 금액을 계산합니다.", status: "active", sortOrder: 1, logicKey: "vat", isPopular: true, searchKeywords: ["부가세", "VAT", "공급가", "매출세액", "매입세액"] }),
    tool({ id: 201, categoryId: 9, slug: "pdf-convert", title: "PDF 변환", description: "PDF 페이지를 이미지로 변환하고 이미지를 PDF로 만듭니다.", kind: "converter", inputs: null, formula: null, faq: null, relatedToolIds: [202], seoTitle: "PDF 변환 | 도구상자", seoDescription: "브라우저에서 PDF와 이미지를 변환합니다.", status: "active", sortOrder: 1, logicKey: "pdf", isPopular: true, searchKeywords: ["PDF", "피디에프"] }),
    tool({ id: 202, categoryId: 11, slug: "image-convert", title: "이미지 변환", description: "JPG·PNG·WebP 변환과 이미지 리사이즈를 제공합니다.", kind: "converter", inputs: null, formula: null, faq: null, relatedToolIds: [201], seoTitle: "이미지 변환 | 도구상자", seoDescription: "브라우저에서 이미지 포맷과 크기를 변환합니다.", status: "active", sortOrder: 1, logicKey: "image", searchKeywords: ["이미지", "JPG", "PNG", "WebP"] }),
    tool({ id: 301, categoryId: 15, slug: "unit-convert", title: "단위 변환기", description: "길이·무게·온도·면적 단위를 한 번에 환산합니다.", kind: "unit", inputs: null, formula: null, faq: null, relatedToolIds: [104], seoTitle: "단위 변환기 | 도구상자", seoDescription: "생활에 필요한 단위를 빠르게 변환합니다.", status: "active", sortOrder: 1, logicKey: "unit", searchKeywords: ["단위", "환산", "길이", "무게", "넓이", "부피", "온도"] }),
    tool({ id: 107, categoryId: 3, slug: "rent-conversion", title: "전월세 전환율 계산기", description: "보증금과 월세의 전환 비용을 계산합니다.", kind: "calculator", inputs: null, formula: "월 환산액 = 보증금 × 전환율 ÷ 12", faq: null, relatedToolIds: [101, 108, 109, 113], seoTitle: "전월세 전환율 계산기 | 도구상자", seoDescription: "전월세 전환율 기준의 월 비용을 계산합니다.", status: "active", sortOrder: 3, logicKey: "rent-conversion", searchKeywords: ["전월세", "전환율", "보증금"] }),
    tool({ id: 108, categoryId: 3, slug: "jeonse-to-monthly", title: "전세 → 월세 계산기", description: "전세 보증금을 월세로 환산합니다.", kind: "calculator", inputs: null, formula: "월세 환산액 = 전세금 × 전환율 ÷ 12", faq: null, relatedToolIds: [101, 107, 113], seoTitle: "전세 월세 계산기 | 도구상자", seoDescription: "전세 보증금을 월세 기준으로 환산합니다.", status: "active", sortOrder: 4, logicKey: "jeonse-to-monthly", searchKeywords: ["전세", "월세", "전환"] }),
    tool({ id: 109, categoryId: 3, slug: "monthly-to-jeonse", title: "월세 → 전세 계산기", description: "월세를 전세 보증금으로 환산합니다.", kind: "calculator", inputs: null, formula: "전세 환산액 = 월세 × 12 ÷ 전환율", faq: null, relatedToolIds: [101, 107, 113], seoTitle: "월세 전세 계산기 | 도구상자", seoDescription: "월세를 전세 보증금 기준으로 환산합니다.", status: "active", sortOrder: 5, logicKey: "monthly-to-jeonse", searchKeywords: ["월세", "전세", "환산"] }),
    tool({ id: 110, categoryId: 2, slug: "loan-amortization", title: "원리금균등상환 계산기", description: "원리금균등 월 상환액을 계산합니다.", kind: "calculator", inputs: null, formula: "원리금균등 상환 공식", faq: null, relatedToolIds: [102, 120, 121, 115], seoTitle: "원리금균등상환 계산기 | 도구상자", seoDescription: "원리금균등 월 상환액과 이자를 계산합니다.", status: "active", sortOrder: 2, logicKey: "loan-amortization", searchKeywords: ["원리금", "대출", "상환"] }),
    tool({ id: 111, categoryId: 2, slug: "deposit-interest", title: "예금 이자 계산기", description: "예치금의 예상 이자를 계산합니다.", kind: "calculator", inputs: null, formula: "이자 = 원금 × 연이율 × 기간", faq: null, relatedToolIds: [112, 119], seoTitle: "예금 이자 계산기 | 도구상자", seoDescription: "예금 원금과 금리로 예상 이자를 계산합니다.", status: "active", sortOrder: 3, logicKey: "deposit-interest", searchKeywords: ["예금", "이자", "금리"] }),
    tool({ id: 112, categoryId: 2, slug: "savings", title: "적금 계산기", description: "매월 납입하는 적금의 예상 만기액을 계산합니다.", kind: "calculator", inputs: null, formula: "만기액 = 납입 원금 + 예상 이자", faq: null, relatedToolIds: [111, 119], seoTitle: "적금 계산기 | 도구상자", seoDescription: "월 납입액과 금리로 적금 만기액을 계산합니다.", status: "active", sortOrder: 4, logicKey: "savings", searchKeywords: ["적금", "예금", "금리"] }),
    tool({ id: 113, categoryId: 22, slug: "jeonse-loan-interest", title: "전세대출 이자 계산기", description: "전세대출 금액·연 이자율·기간으로 월 이자와 총 이자를 계산합니다.", kind: "calculator", inputs: null, formula: "총 이자 = 대출금액 × 연 이자율 × 대출기간(개월) ÷ 12", faq: [{ question: "원금 상환을 반영하나요?", answer: "이 도구는 이자만 납부하는 단순 기준으로 계산합니다. 원금 상환 방식이 있는 상품은 약정 상환표를 확인하세요." }], relatedToolIds: [101, 107, 108, 114], seoTitle: "전세대출 이자 계산기 | 도구상자", seoDescription: "전세대출의 월 이자와 대출 기간 전체 예상 이자를 계산합니다.", status: "active", sortOrder: 1, logicKey: "jeonse-loan-interest", isPopular: true, searchKeywords: ["전세대출", "전세자금", "전세 이자", "전세대출이자"] }),
    tool({ id: 114, categoryId: 22, slug: "mortgage", title: "주택담보대출 계산기", description: "주택담보대출의 월 상환액·총 이자·월별 상환 구조를 계산합니다.", kind: "calculator", inputs: null, formula: "월 상환액 = 원금 × 월이자율 × (1+월이자율)^기간 ÷ ((1+월이자율)^기간−1)", faq: [{ question: "주담대 금리는 고정인가요?", answer: "입력한 하나의 연 이자율을 전체 기간에 적용한 고정금리 가정입니다." }], relatedToolIds: [102, 120, 121, 115], seoTitle: "주택담보대출 계산기 | 도구상자", seoDescription: "주담대 원리금균등 기준 월 납입액, 총 상환액과 월별 상환표를 계산합니다.", status: "active", sortOrder: 2, logicKey: "mortgage", isPopular: true, searchKeywords: ["주택담보대출", "주담대", "아파트 대출", "모기지"] }),
    tool({ id: 115, categoryId: 23, slug: "early-repayment-fee", title: "중도상환수수료 계산기", description: "중도상환 원금·수수료율·잔여일수로 예상 중도상환수수료를 계산합니다.", kind: "calculator", inputs: null, formula: "중도상환수수료 = 중도상환원금 × 수수료율 × 적용일수 ÷ 365", faq: [{ question: "면제 기간은 어떻게 적용하나요?", answer: "입력한 면제일수만큼 잔여일수에서 차감하며, 은행별 약정이 우선합니다." }], relatedToolIds: [114, 102, 120, 121], seoTitle: "중도상환수수료 계산기 | 도구상자", seoDescription: "대출 중도상환 시 원금과 잔여 기간을 기준으로 예상 수수료를 계산합니다.", status: "active", sortOrder: 1, logicKey: "early-repayment-fee", searchKeywords: ["중도상환", "중도상환수수료", "상환수수료"] }),
    tool({ id: 116, categoryId: 23, slug: "brokerage-fee", title: "부동산 중개수수료 계산기", description: "매매·임대차 거래금액에 따른 주택 중개보수 상한액을 계산합니다.", kind: "calculator", inputs: null, formula: "중개보수 = 거래금액 × 구간별 상한요율(한도액 적용)", faq: [{ question: "부가가치세가 포함되나요?", answer: "중개보수 상한액만 계산하며, 부가가치세는 별도일 수 있습니다." }], relatedToolIds: [117, 118, 101], seoTitle: "부동산 중개수수료 계산기 | 도구상자", seoDescription: "주택 매매·임대차 거래금액별 부동산 중개보수 상한액을 계산합니다.", status: "active", sortOrder: 2, logicKey: "brokerage-fee", isPopular: true, searchKeywords: ["중개수수료", "복비", "부동산 수수료", "중개보수"] }),
    tool({ id: 117, categoryId: 24, slug: "acquisition-tax", title: "취득세 계산기", description: "일반 개인 주택 유상취득의 기본 취득세를 주택 수와 지역 조건에 따라 계산합니다.", kind: "calculator", inputs: null, formula: "취득세 = 취득가액 × 적용 세율", faq: [{ question: "부가세목도 포함되나요?", answer: "이 도구는 취득세 본세 기준입니다. 지방교육세·농어촌특별세, 감면과 중과는 위택스에서 확인하세요." }], relatedToolIds: [118, 116], seoTitle: "취득세 계산기 | 도구상자", seoDescription: "주택 취득가액, 보유 주택 수와 조정대상지역 여부로 기본 취득세를 계산합니다.", status: "active", sortOrder: 1, logicKey: "acquisition-tax", isPopular: true, searchKeywords: ["취득세", "주택 취득세", "아파트 취득세"] }),
    tool({ id: 118, categoryId: 24, slug: "property-tax", title: "재산세 계산기", description: "주택 공시가격 기준의 과세표준과 재산세 본세를 간이 계산합니다.", kind: "calculator", inputs: null, formula: "과세표준 = 주택 공시가격 × 60%, 재산세 = 과세표준 × 누진세율", faq: [{ question: "고지서 금액과 왜 다를 수 있나요?", answer: "세부담상한, 도시지역분, 지역자원시설세, 1세대 1주택 특례 등이 반영되지 않은 본세 기준입니다." }], relatedToolIds: [117, 116], seoTitle: "재산세 계산기 | 도구상자", seoDescription: "주택 공시가격을 기준으로 재산세 과세표준과 본세를 계산합니다.", status: "active", sortOrder: 2, logicKey: "property-tax", isPopular: true, searchKeywords: ["재산세", "보유세", "공시가격", "주택 재산세"] }),
    tool({ id: 119, categoryId: 25, slug: "compound-interest", title: "복리 계산기", description: "원금·연 이자율·기간을 기준으로 복리 수익과 만기 금액을 계산합니다.", kind: "calculator", inputs: null, formula: "만기금액 = 원금 × (1 + 연 이자율)^기간", faq: [{ question: "세금과 수수료를 반영하나요?", answer: "세전 연복리 기준입니다. 실제 금융상품의 세금·수수료·복리 주기는 상품설명서를 확인하세요." }], relatedToolIds: [111, 112], seoTitle: "복리 계산기 | 도구상자", seoDescription: "원금, 연 이자율과 기간으로 복리 이자와 만기 예상 금액을 계산합니다.", status: "active", sortOrder: 1, logicKey: "compound-interest", isPopular: true, searchKeywords: ["복리", "복리이자", "복리 계산", "연복리"] }),
    tool({ id: 120, categoryId: 26, slug: "equal-principal", title: "대출 원금균등상환 계산기", description: "원금을 매월 동일하게 나누어 갚는 대출의 상환액과 이자를 계산합니다.", kind: "calculator", inputs: null, formula: "매월 원금상환액 = 대출원금 ÷ 상환개월수", faq: [{ question: "첫 달 납입액이 큰 이유는 무엇인가요?", answer: "원금은 일정하지만 잔액이 큰 첫 달의 이자가 가장 크기 때문입니다." }], relatedToolIds: [102, 110, 114, 121], seoTitle: "대출 원금균등상환 계산기 | 도구상자", seoDescription: "대출 원금균등상환의 첫 달 납입액, 총 이자와 월별 상환표를 계산합니다.", status: "active", sortOrder: 1, logicKey: "equal-principal", isPopular: true, searchKeywords: ["원금균등", "원금균등상환", "대출 상환"] }),
    tool({ id: 121, categoryId: 26, slug: "bullet-loan", title: "대출 만기일시상환 계산기", description: "만기일에 원금을 상환하고 매월 이자를 납부하는 대출의 비용을 계산합니다.", kind: "calculator", inputs: null, formula: "월 이자 = 대출원금 × 연 이자율 ÷ 12, 만기 상환액 = 원금 + 마지막 달 이자", faq: [{ question: "매월 납입액이 같은가요?", answer: "고정금리 가정에서는 만기 전까지 이자만 같고, 마지막 달에는 원금이 함께 청구됩니다." }], relatedToolIds: [102, 110, 114, 120], seoTitle: "대출 만기일시상환 계산기 | 도구상자", seoDescription: "만기일시상환 대출의 월 이자, 만기 상환액과 전체 상환표를 계산합니다.", status: "active", sortOrder: 2, logicKey: "bullet-loan", searchKeywords: ["만기일시", "만기일시상환", "이자만", "대출 상환"] }),
    tool({ id: 122, categoryId: 27, slug: "percentage", title: "퍼센트 계산기", description: "기준값의 퍼센트, 증감액과 증감률을 계산합니다.", kind: "calculator", inputs: null, formula: "결과 = 기준값 × 퍼센트 ÷ 100", faq: [{ question: "0에서의 증감률은 계산되나요?", answer: "0을 기준으로 한 증감률은 정의하기 어려워 이 도구에서는 0%로 표시합니다." }], relatedToolIds: [119, 111, 112], seoTitle: "퍼센트 계산기 | 도구상자", seoDescription: "기준값의 퍼센트와 증감률을 빠르게 계산합니다.", status: "active", sortOrder: 1, logicKey: "percentage", isPopular: true, searchKeywords: ["퍼센트", "백분율", "비율", "증감률", "할인"] }),
    tool({ id: 123, categoryId: 28, slug: "annual-take-home", title: "연봉 실수령액 계산기", description: "연봉, 부양가족·자녀 수와 비과세 급여를 반영해 예상 실수령액을 계산합니다.", kind: "calculator", inputs: null, formula: "월 실수령액 = 월 세전급여 − 4대보험 근로자 부담분 − 간이 추정 소득세", faq: [{ question: "실제 원천징수와 왜 다른가요?", answer: "비과세 구성, 간이세액표 선택비율, 공제요건과 연말정산에 따라 실제 원천징수액이 달라질 수 있습니다." }], relatedToolIds: [124, 125, 128], seoTitle: "연봉 실수령액 계산기 | 도구상자", seoDescription: "2026년 일반 직장가입자 기준으로 연봉의 월·연 예상 실수령액과 공제 항목을 계산합니다.", status: "active", sortOrder: 0, logicKey: "annual-take-home", isPopular: true, searchKeywords: ["연봉", "연봉 실수령액", "연봉계산", "세후 연봉", "연봉 월급"] }),
    tool({ id: 124, categoryId: 28, slug: "monthly-take-home", title: "월급 실수령액 계산기", description: "월 세전 급여와 비과세액을 기준으로 공제 항목별 예상 실수령액을 계산합니다.", kind: "calculator", inputs: null, formula: "월 실수령액 = 월 세전급여 − 사회보험료 − 간이 추정 소득세", faq: [{ question: "비과세 급여는 무엇인가요?", answer: "식대 등 법정 요건을 충족하는 비과세 항목은 보험·소득세 산정에 차이가 있을 수 있습니다." }], relatedToolIds: [123, 125, 128], seoTitle: "월급 실수령액 계산기 | 도구상자", seoDescription: "월 급여의 4대보험, 소득세, 지방소득세와 예상 실수령액을 계산합니다.", status: "active", sortOrder: 0, logicKey: "monthly-take-home", isPopular: true, searchKeywords: ["월급", "월급 실수령액", "월급계산", "세후 월급", "급여 실수령"] }),
    tool({ id: 125, categoryId: 28, slug: "four-insurance", title: "4대보험 계산기", description: "월 보수 기준 국민연금·건강·장기요양·고용보험의 부담액을 계산합니다.", kind: "calculator", inputs: null, formula: "보험료 = 보수월액 × 보험료율", faq: [{ question: "사업주 부담액이 실제와 다른 이유는 무엇인가요?", answer: "고용안정·직업능력개발 부담분과 산재보험은 사업장 규모·업종에 따라 다를 수 있습니다." }], relatedToolIds: [123, 124, 128], seoTitle: "4대보험 계산기 | 도구상자", seoDescription: "2026년 일반 직장가입자 기준의 4대보험 근로자·사업주 기본 부담액을 계산합니다.", status: "active", sortOrder: 3, logicKey: "four-insurance", searchKeywords: ["4대보험", "사대보험", "국민연금", "건강보험", "장기요양보험", "고용보험"] }),
    tool({ id: 126, categoryId: 29, slug: "weekly-holiday-pay", title: "주휴수당 계산기", description: "시급·주당 근로시간·근무일수로 주휴수당과 예상 주급을 계산합니다.", kind: "calculator", inputs: null, formula: "주휴수당 = 시급 × 1일 소정근로시간", faq: [{ question: "주 15시간 미만도 주휴수당을 받나요?", answer: "주 평균 소정근로시간이 15시간 미만이면 이 도구의 주휴수당 추정 대상이 아닙니다." }], relatedToolIds: [128, 129, 124], seoTitle: "주휴수당 계산기 | 도구상자", seoDescription: "시급과 주당 소정근로시간을 기준으로 주휴수당과 주급을 계산합니다.", status: "active", sortOrder: 1, logicKey: "weekly-holiday-pay", searchKeywords: ["주휴수당", "주휴", "주급", "알바 주휴수당", "주 15시간"] }),
    tool({ id: 127, categoryId: 29, slug: "annual-leave-pay", title: "연차수당 계산기", description: "통상시급과 미사용 연차일수로 예상 연차수당을 계산합니다.", kind: "calculator", inputs: null, formula: "연차수당 = 1일 통상임금 × 미사용 연차일수", faq: [{ question: "모든 미사용 연차가 수당이 되나요?", answer: "사용촉진, 소멸과 회사 운영 방식에 따라 실제 지급 여부가 달라질 수 있습니다." }], relatedToolIds: [105, 129, 128], seoTitle: "연차수당 계산기 | 도구상자", seoDescription: "통상시급, 1일 근로시간과 미사용 연차일수로 예상 연차수당을 계산합니다.", status: "active", sortOrder: 2, logicKey: "annual-leave-pay", searchKeywords: ["연차수당", "미사용 연차", "연차 정산", "연차 계산"] }),
    tool({ id: 128, categoryId: 29, slug: "hourly-wage", title: "시급 계산기", description: "월급에서 시급을 계산하거나 시급에서 월급을 환산합니다.", kind: "calculator", inputs: null, formula: "시급 = 월급 ÷ 월 환산 근로시간", faq: [{ question: "월 209시간을 항상 사용하나요?", answer: "주 40시간·유급주휴를 포함한 일반 환산 예시입니다. 계약에 따라 월 환산시간이 달라질 수 있습니다." }], relatedToolIds: [126, 128, 124, 139], seoTitle: "시급 계산기 | 도구상자", seoDescription: "월급과 월 환산 근로시간으로 시급을 계산하고 시급에서 월급을 환산합니다.", status: "active", sortOrder: 3, logicKey: "hourly-wage", searchKeywords: ["시급", "시급계산", "월급 시급", "209시간", "알바 시급", "시간당 급여", "시간당임금"] }),
    tool({ id: 129, categoryId: 29, slug: "work-hours", title: "근무시간 계산기", description: "시작·종료시간과 휴게시간으로 자정 경과 근무를 포함한 실근무시간을 계산합니다.", kind: "calculator", inputs: null, formula: "실근무시간 = 전체 근무시간 − 휴게시간", faq: [{ question: "자정을 넘는 근무도 계산되나요?", answer: "종료시간이 시작시간보다 이르면 다음 날 종료로 보고 계산합니다." }], relatedToolIds: [126, 128, 127, 145], seoTitle: "근무시간 계산기 | 도구상자", seoDescription: "시작시간, 종료시간, 휴게시간으로 실근무시간을 계산합니다.", status: "active", sortOrder: 4, logicKey: "work-hours", searchKeywords: ["근무시간", "근로시간", "야간근무", "휴게시간", "근무시간 계산", "출퇴근 시간"] }),
    tool({ id: 130, categoryId: 30, slug: "retirement-income-tax", title: "퇴직소득세 계산기", description: "퇴직급여와 근속연수로 퇴직소득세·지방소득세와 예상 수령액을 계산합니다.", kind: "calculator", inputs: null, formula: "산출세액 = 환산 과세표준 세액 ÷ 12 × 근속연수", faq: [{ question: "실제 세액이 달라질 수 있나요?", answer: "중간정산·과세이연·비과세소득 및 귀속연도별 특례가 있어 국세청 프로그램 확인이 필요합니다." }], relatedToolIds: [105, 127, 129], seoTitle: "퇴직소득세 계산기 | 도구상자", seoDescription: "퇴직급여와 근속연수를 기준으로 퇴직소득세, 지방소득세와 예상 실수령액을 계산합니다.", status: "active", sortOrder: 2, logicKey: "retirement-income-tax", searchKeywords: ["퇴직소득세", "퇴직세", "퇴직금 세금", "퇴직소득"] }),
    tool({ id: 131, categoryId: 30, slug: "unemployment-benefit", title: "실업급여 계산기", description: "퇴직 전 월급·나이·고용보험 가입기간으로 예상 실업급여를 계산합니다.", kind: "calculator", inputs: null, formula: "구직급여 = 1일 평균임금 × 60% × 소정급여일수", faq: [{ question: "계산 결과만으로 수급할 수 있나요?", answer: "아닙니다. 퇴사사유, 피보험단위기간과 재취업활동 등 법정 요건을 고용센터가 최종 판단합니다." }], relatedToolIds: [105, 124, 125, 139], seoTitle: "실업급여 계산기 | 도구상자", seoDescription: "퇴직 전 월급과 고용보험 가입기간을 기준으로 예상 1일 지급액·지급일수·총액을 계산합니다.", status: "active", sortOrder: 0, logicKey: "unemployment-benefit", isPopular: true, searchKeywords: ["실업급여", "구직급여", "고용보험 실업급여", "실업급여 계산", "실업급여 기간"] }),
    tool({ id: 132, categoryId: 31, slug: "comprehensive-income-tax", title: "종합소득세 계산기", description: "수입·필요경비·공제와 기납부세액으로 종합소득세를 간이 계산합니다.", kind: "calculator", inputs: null, formula: "납부 추정액 = (과세표준 누진세액 − 세액공제) + 지방소득세 − 기납부세액", faq: [{ question: "사업소득 외 소득도 계산되나요?", answer: "입력한 수입·필요경비·공제 합계를 바탕으로 한 간이 추정입니다. 분리과세와 개별 특례는 반영하지 않습니다." }], relatedToolIds: [123, 122, 106], seoTitle: "종합소득세 계산기 | 도구상자", seoDescription: "수입금액, 필요경비와 공제액을 바탕으로 종합소득세와 지방소득세를 간이 계산합니다.", status: "active", sortOrder: 1, logicKey: "comprehensive-income-tax", searchKeywords: ["종합소득세", "종소세", "종합소득", "프리랜서 세금", "사업자 소득세"] }),
    tool({ id: 133, categoryId: 32, slug: "capital-gains-tax", title: "양도소득세 계산기", description: "양도가액·취득가액·필요경비와 보유기간으로 양도소득세를 간이 계산합니다.", kind: "calculator", inputs: null, formula: "과세표준 = 양도차익 − 기본공제, 세액 = 과세표준 × 적용세율 + 지방소득세", faq: [{ question: "1세대 1주택 비과세가 반영되나요?", answer: "아닙니다. 이 도구는 일반 자산의 간이 추정이며 비과세·중과·감면과 장기보유특별공제는 반영하지 않습니다." }], relatedToolIds: [117, 118, 116], seoTitle: "양도소득세 계산기 | 도구상자", seoDescription: "일반 자산의 양도가액, 취득가액, 비용과 보유기간으로 양도소득세를 간이 계산합니다.", status: "active", sortOrder: 1, logicKey: "capital-gains-tax", searchKeywords: ["양도소득세", "양도세", "부동산 양도", "양도차익"] }),
    tool({ id: 134, categoryId: 32, slug: "gift-tax", title: "증여세 계산기", description: "증여재산·채무·관계와 이전 증여액으로 증여세를 간이 계산합니다.", kind: "calculator", inputs: null, formula: "과세표준 = 증여 과세가액 − 관계별 공제, 산출세액 = 누진세율 적용", faq: [{ question: "10년 이내 증여는 왜 입력하나요?", answer: "동일인에게 받은 이전 증여재산은 일정 요건에서 합산될 수 있으므로 간이 계산에 반영합니다." }], relatedToolIds: [135, 117], seoTitle: "증여세 계산기 | 도구상자", seoDescription: "증여재산, 관계별 공제와 이전 증여액을 기준으로 증여세를 간이 계산합니다.", status: "active", sortOrder: 2, logicKey: "gift-tax", searchKeywords: ["증여세", "가족 증여", "자녀 증여", "증여 공제"] }),
    tool({ id: 135, categoryId: 32, slug: "inheritance-tax", title: "상속세 계산기", description: "상속재산·채무·공제와 사전증여액으로 상속세를 간이 계산합니다.", kind: "calculator", inputs: null, formula: "과세표준 = 순상속재산가액 − 상속공제, 산출세액 = 누진세율 적용", faq: [{ question: "배우자공제를 자동 계산하나요?", answer: "배우자공제를 포함한 공제금액을 사용자가 입력하는 간이 계산입니다. 법정 요건은 별도 확인이 필요합니다." }], relatedToolIds: [134, 117], seoTitle: "상속세 계산기 | 도구상자", seoDescription: "상속재산과 공제를 기준으로 상속세와 신고세액공제 반영 예상액을 계산합니다.", status: "active", sortOrder: 3, logicKey: "inheritance-tax", searchKeywords: ["상속세", "상속 재산", "상속 공제", "상속세 계산"] }),
    tool({ id: 136, categoryId: 33, slug: "year-end-tax-refund", title: "연말정산 환급금 계산기", description: "총급여·공제·기납부세액을 기준으로 예상 환급 또는 추가납부액을 계산합니다.", kind: "calculator", inputs: null, formula: "환급/추가납부 = 기납부세액 − (결정 소득세 + 결정 지방소득세)", faq: [{ question: "실제 환급금과 같나요?", answer: "간소화 자료, 공제 요건과 회사 원천징수에 따라 달라지는 간이 추정 결과입니다." }], relatedToolIds: [123, 124, 125], seoTitle: "연말정산 환급금 계산기 | 도구상자", seoDescription: "총급여, 공제와 기납부세액을 바탕으로 연말정산 예상 환급금을 계산합니다.", status: "active", sortOrder: 0, logicKey: "year-end-tax-refund", isPopular: true, searchKeywords: ["연말정산", "환급금", "추가납부", "소득공제", "연말정산 계산"] }),
    tool({ id: 137, categoryId: 34, slug: "national-pension", title: "국민연금 예상수령액 계산기", description: "기준소득월액과 가입기간으로 노령연금 예상액을 간이 추정합니다.", kind: "calculator", inputs: null, formula: "간이 예상액 = 평균 기준소득 × 소득대체율 × (총 가입연수 ÷ 40)", faq: [{ question: "국민연금공단 예상연금과 왜 다를 수 있나요?", answer: "실제 가입이력, A값, 재평가율과 수급개시연령이 반영되는 공단 조회 결과와 차이가 날 수 있습니다." }], relatedToolIds: [125, 123], seoTitle: "국민연금 예상수령액 계산기 | 도구상자", seoDescription: "기준소득월액과 국민연금 가입기간으로 월 예상 노령연금을 간이 계산합니다.", status: "active", sortOrder: 1, logicKey: "national-pension", searchKeywords: ["국민연금", "노령연금", "연금 예상액", "국민연금 수령액"] }),
    tool({ id: 138, categoryId: 34, slug: "health-insurance", title: "건강보험료 계산기", description: "직장·지역가입자 기준의 건강보험료와 장기요양보험료를 간이 계산합니다.", kind: "calculator", inputs: null, formula: "보험료 = 소득월액 × 보험료율 + 재산점수 보험료, 장기요양보험료는 건강보험료에 연동", faq: [{ question: "피부양자 여부도 판단하나요?", answer: "아닙니다. 이 도구는 입력된 가입유형의 간이 보험료만 계산하며 자격·경감·정산은 반영하지 않습니다." }], relatedToolIds: [125, 123], seoTitle: "건강보험료 계산기 | 도구상자", seoDescription: "직장·지역가입자 유형과 소득월액을 기준으로 건강보험료를 간이 계산합니다.", status: "active", sortOrder: 2, logicKey: "health-insurance", isPopular: true, searchKeywords: ["건강보험료", "건보료", "지역가입자", "장기요양보험"] }),
    tool({ id: 139, categoryId: 29, slug: "minimum-wage", title: "최저임금 월급 계산기", description: "시급·근로시간·주휴 여부로 월 예상 최저임금과 주급을 계산합니다.", kind: "calculator", inputs: null, formula: "월 예상액 = (주 기본급 + 주휴수당) × 365 ÷ 12 ÷ 7", faq: [{ question: "월 209시간을 항상 적용하나요?", answer: "이 도구는 입력한 근로시간과 주휴 포함 여부로 월 환산값을 계산합니다. 계약별 월 환산시간은 다를 수 있습니다." }], relatedToolIds: [128, 126, 129, 131], seoTitle: "최저임금 월급 계산기 | 도구상자", seoDescription: "2026년 최저시급과 근로시간, 주휴수당을 기준으로 예상 월급을 계산합니다.", status: "active", sortOrder: 5, logicKey: "minimum-wage", isPopular: true, searchKeywords: ["최저임금", "최저시급", "최저월급", "주휴수당", "2026 최저임금"] }),
    tool({ id: 140, categoryId: 36, slug: "date-calculator", title: "날짜 계산기", description: "기준일에서 연·월·일을 더하거나 빼 결과 날짜를 계산합니다.", kind: "calculator", inputs: null, formula: "결과일 = 기준일 ± 연/월/일", faq: [{ question: "월말 날짜는 어떻게 처리하나요?", answer: "대상 월에 같은 일이 없으면 해당 월의 마지막 날로 보정합니다." }], relatedToolIds: [141, 144, 145], seoTitle: "날짜 계산기 | 도구상자", seoDescription: "기준일에 연, 월, 일을 더하거나 빼서 결과 날짜를 계산합니다.", status: "active", sortOrder: 1, logicKey: "date-calculator", isPopular: true, searchKeywords: ["날짜 계산", "날짜 더하기", "날짜 빼기", "기간 계산"] }),
    tool({ id: 141, categoryId: 36, slug: "d-day", title: "D-Day 계산기", description: "기준일과 목표일의 남은 날짜 또는 지난 날짜를 계산합니다.", kind: "calculator", inputs: null, formula: "D-Day = 목표일 − 기준일", faq: [{ question: "목표일이 지나면 어떻게 표시되나요?", answer: "지난 날짜는 D+숫자로 표시합니다." }], relatedToolIds: [140, 144, 142], seoTitle: "D-Day 계산기 | 도구상자", seoDescription: "기준일과 목표일을 입력해 D-Day와 남은 일수를 계산합니다.", status: "active", sortOrder: 0, logicKey: "d-day", isPopular: true, searchKeywords: ["D-Day", "디데이", "기념일", "남은 날짜"] }),
    tool({ id: 142, categoryId: 37, slug: "age", title: "나이 계산기", description: "생년월일과 기준일로 만 나이, 세는 나이, 연 나이를 비교합니다.", kind: "calculator", inputs: null, formula: "만 나이 = 기준연도 − 출생연도 − 생일 경과 보정", faq: [{ question: "세는 나이는 법적 기준인가요?", answer: "세는 나이는 관습상 정보이며 법률상 나이 판단에는 만 나이를 확인하세요." }], relatedToolIds: [143, 141], seoTitle: "나이 계산기 | 도구상자", seoDescription: "생년월일과 기준일을 바탕으로 만 나이, 세는 나이와 연 나이를 계산합니다.", status: "active", sortOrder: 1, logicKey: "age", searchKeywords: ["나이 계산", "세는 나이", "연 나이", "생년월일 나이"] }),
    tool({ id: 143, categoryId: 37, slug: "man-age", title: "만 나이 계산기", description: "생년월일과 기준일로 현재 만 나이와 다음 생일까지 남은 날짜를 계산합니다.", kind: "calculator", inputs: null, formula: "만 나이 = 기준연도 − 출생연도 − 생일 전 보정", faq: [{ question: "2월 29일 생일도 계산되나요?", answer: "비윤년에는 2월의 마지막 날을 기준으로 생일을 계산합니다." }], relatedToolIds: [142, 141], seoTitle: "만 나이 계산기 | 도구상자", seoDescription: "생년월일과 기준일로 현재 만 나이와 생일 경과 여부를 계산합니다.", status: "active", sortOrder: 2, logicKey: "man-age", searchKeywords: ["만나이", "만 나이", "국제나이", "생일 나이"] }),
    tool({ id: 144, categoryId: 36, slug: "date-difference", title: "날짜 차이 계산기", description: "시작일과 종료일의 일수·주수·완전한 개월 수를 계산합니다.", kind: "calculator", inputs: null, formula: "총 일수 = 종료일 − 시작일", faq: [{ question: "시작일과 종료일을 모두 포함할 수 있나요?", answer: "포함일 옵션을 선택하면 양 끝 날짜를 포함한 일수를 표시합니다." }], relatedToolIds: [140, 141, 145], seoTitle: "날짜 차이 계산기 | 도구상자", seoDescription: "시작일과 종료일 사이의 총 일수, 주수와 개월 수를 계산합니다.", status: "active", sortOrder: 3, logicKey: "date-difference", searchKeywords: ["날짜 차이", "기간 계산", "며칠 차이", "날짜 기간"] }),
    tool({ id: 145, categoryId: 36, slug: "time-calculator", title: "시간 계산기", description: "기준 시각에 시간과 분을 더하거나 빼 결과 시각을 계산합니다.", kind: "calculator", inputs: null, formula: "결과 시각 = 기준 시각 ± 시간/분", faq: [{ question: "자정을 넘는 시간도 계산되나요?", answer: "예. 결과에 전날 또는 다음 날 여부를 함께 표시합니다." }], relatedToolIds: [140, 144, 129], seoTitle: "시간 계산기 | 도구상자", seoDescription: "시:분 기준으로 시간과 분을 더하거나 빼 결과 시각을 계산합니다.", status: "active", sortOrder: 4, logicKey: "time-calculator", searchKeywords: ["시간 계산", "시간 더하기", "시간 빼기", "시분 계산"] }),
    tool({ id: 302, categoryId: 9, slug: "pdf-to-jpg", title: "PDF → JPG 변환", description: "PDF 각 페이지를 JPG 이미지로 로컬 변환합니다.", kind: "converter", inputs: null, formula: null, faq: [{ question: "페이지별로 다운로드할 수 있나요?", answer: "예. 변환 결과에서 각 PDF 페이지를 개별 JPG로 다운로드할 수 있습니다." }], relatedToolIds: [303, 306, 312], seoTitle: "PDF JPG 변환 | 도구상자", seoDescription: "PDF 각 페이지를 브라우저에서 JPG 이미지로 변환합니다.", status: "active", sortOrder: 2, logicKey: "pdf-to-jpg", searchKeywords: ["PDF JPG", "PDF 이미지", "PDF 사진 변환", "PDF를 JPG로"] }),
    tool({ id: 303, categoryId: 9, slug: "pdf-to-png", title: "PDF → PNG 변환", description: "PDF 각 페이지를 PNG 이미지로 로컬 변환합니다.", kind: "converter", inputs: null, formula: null, faq: [{ question: "PNG는 투명 배경을 유지하나요?", answer: "PDF 페이지는 일반적으로 불투명 배경으로 렌더링됩니다." }], relatedToolIds: [302, 304, 312], seoTitle: "PDF PNG 변환 | 도구상자", seoDescription: "PDF 각 페이지를 브라우저에서 PNG 이미지로 변환합니다.", status: "active", sortOrder: 3, logicKey: "pdf-to-png", searchKeywords: ["PDF PNG", "PDF 그림 변환", "PDF를 PNG로"] }),
    tool({ id: 304, categoryId: 9, slug: "jpg-to-pdf", title: "JPG → PDF 변환", description: "JPG 이미지를 하나의 PDF 파일로 만듭니다.", kind: "converter", inputs: null, formula: null, faq: [{ question: "여러 이미지를 한 번에 넣을 수 있나요?", answer: "예. 선택한 이미지 순서대로 PDF 페이지가 만들어집니다." }], relatedToolIds: [305, 302, 306], seoTitle: "JPG PDF 변환 | 도구상자", seoDescription: "JPG 사진을 브라우저에서 PDF 문서로 변환합니다.", status: "active", sortOrder: 4, logicKey: "jpg-to-pdf", searchKeywords: ["JPG PDF", "사진 PDF", "이미지 PDF", "JPG를 PDF로"] }),
    tool({ id: 305, categoryId: 9, slug: "png-to-pdf", title: "PNG → PDF 변환", description: "PNG 이미지를 하나의 PDF 파일로 만듭니다.", kind: "converter", inputs: null, formula: null, faq: [{ question: "PNG도 여러 개 선택할 수 있나요?", answer: "예. JPG, PNG, WebP 이미지를 함께 선택해 PDF로 만들 수 있습니다." }], relatedToolIds: [304, 303, 306], seoTitle: "PNG PDF 변환 | 도구상자", seoDescription: "PNG 이미지를 브라우저에서 PDF 문서로 변환합니다.", status: "active", sortOrder: 5, logicKey: "png-to-pdf", searchKeywords: ["PNG PDF", "PNG를 PDF로", "사진 PDF"] }),
    tool({ id: 306, categoryId: 10, slug: "pdf-merge", title: "PDF 합치기", description: "여러 PDF를 선택한 순서대로 하나의 파일로 합칩니다.", kind: "converter", inputs: null, formula: null, faq: [{ question: "원본 PDF 순서는 어떻게 정하나요?", answer: "파일 선택 목록의 순서를 기준으로 병합합니다." }], relatedToolIds: [307, 308, 312], seoTitle: "PDF 합치기 | 도구상자", seoDescription: "여러 PDF 파일을 브라우저에서 하나로 합칩니다.", status: "active", sortOrder: 1, logicKey: "pdf-merge", isPopular: true, searchKeywords: ["PDF 합치기", "PDF 병합", "PDF 결합"] }),
    tool({ id: 307, categoryId: 10, slug: "pdf-split", title: "PDF 분할", description: "PDF의 각 페이지를 개별 PDF 파일로 분할합니다.", kind: "converter", inputs: null, formula: null, faq: [{ question: "분할한 페이지는 모두 저장할 수 있나요?", answer: "예. 결과 목록에서 페이지별 PDF를 각각 다운로드합니다." }], relatedToolIds: [306, 308, 309], seoTitle: "PDF 분할 | 도구상자", seoDescription: "PDF 문서를 페이지별 PDF 파일로 분할합니다.", status: "active", sortOrder: 2, logicKey: "pdf-split", searchKeywords: ["PDF 분할", "PDF 나누기", "PDF 페이지 분리"] }),
    tool({ id: 308, categoryId: 10, slug: "pdf-extract-pages", title: "PDF 페이지 추출", description: "지정한 페이지 범위만 새 PDF로 추출합니다.", kind: "converter", inputs: null, formula: null, faq: [{ question: "페이지 범위는 어떻게 입력하나요?", answer: "1,3-5처럼 쉼표와 하이픈을 사용해 입력합니다." }], relatedToolIds: [307, 309, 310], seoTitle: "PDF 페이지 추출 | 도구상자", seoDescription: "PDF에서 필요한 페이지만 새 PDF로 추출합니다.", status: "active", sortOrder: 3, logicKey: "pdf-extract-pages", searchKeywords: ["PDF 페이지 추출", "PDF 페이지 저장", "PDF 일부 추출"] }),
    tool({ id: 309, categoryId: 10, slug: "pdf-delete-pages", title: "PDF 페이지 삭제", description: "지정한 페이지를 제외한 새 PDF를 만듭니다.", kind: "converter", inputs: null, formula: null, faq: [{ question: "원본 파일이 바뀌나요?", answer: "아니요. 원본을 수정하지 않고 새 PDF를 만듭니다." }], relatedToolIds: [308, 307, 310], seoTitle: "PDF 페이지 삭제 | 도구상자", seoDescription: "PDF에서 원하지 않는 페이지를 제외한 새 파일을 만듭니다.", status: "active", sortOrder: 4, logicKey: "pdf-delete-pages", searchKeywords: ["PDF 페이지 삭제", "PDF 페이지 제거"] }),
    tool({ id: 310, categoryId: 10, slug: "pdf-reorder-pages", title: "PDF 페이지 순서 변경", description: "입력한 번호 순서대로 PDF 페이지를 재구성합니다.", kind: "converter", inputs: null, formula: null, faq: [{ question: "번호를 중복할 수 있나요?", answer: "아니요. 모든 페이지를 한 번씩 입력해야 합니다." }], relatedToolIds: [311, 308, 309], seoTitle: "PDF 페이지 순서 변경 | 도구상자", seoDescription: "PDF 페이지 순서를 바꾸어 새 PDF를 만듭니다.", status: "active", sortOrder: 5, logicKey: "pdf-reorder-pages", searchKeywords: ["PDF 순서 변경", "PDF 페이지 정렬", "PDF 페이지 이동"] }),
    tool({ id: 311, categoryId: 10, slug: "pdf-rotate-pages", title: "PDF 페이지 회전", description: "선택한 PDF 페이지를 90·180·270도 회전합니다.", kind: "converter", inputs: null, formula: null, faq: [{ question: "전체 페이지를 한 번에 회전할 수 있나요?", answer: "예. 페이지 입력을 비워 두면 전체 페이지를 회전합니다." }], relatedToolIds: [310, 309, 312], seoTitle: "PDF 페이지 회전 | 도구상자", seoDescription: "PDF 페이지 방향을 회전해 새 PDF로 저장합니다.", status: "active", sortOrder: 6, logicKey: "pdf-rotate-pages", searchKeywords: ["PDF 회전", "PDF 방향 변경", "PDF 가로 세로"] }),
    tool({ id: 312, categoryId: 13, slug: "pdf-compress", title: "PDF 용량 줄이기", description: "JPEG 재구성 방식으로 PDF 용량을 실제로 줄입니다.", kind: "converter", inputs: null, formula: null, faq: [{ question: "압축하면 품질이 달라지나요?", answer: "예. 이미지 재구성 방식이므로 낮은 품질에서는 선명도와 텍스트 레이어가 손실될 수 있습니다." }], relatedToolIds: [306, 302, 313], seoTitle: "PDF 용량 줄이기 | 도구상자", seoDescription: "브라우저에서 JPEG 재구성 방식으로 PDF 파일 용량을 줄입니다.", status: "active", sortOrder: 1, logicKey: "pdf-compress", searchKeywords: ["PDF 압축", "PDF 용량 줄이기", "PDF 크기 줄이기"] }),
    tool({ id: 313, categoryId: 13, slug: "image-compress", title: "이미지 용량 줄이기", description: "이미지를 실제로 재인코딩해 파일 용량을 줄입니다.", kind: "converter", inputs: null, formula: null, faq: [{ question: "원본 이미지는 바뀌나요?", answer: "아니요. 원본은 바꾸지 않고 새 이미지 파일을 다운로드합니다." }], relatedToolIds: [314, 202, 312], seoTitle: "이미지 용량 줄이기 | 도구상자", seoDescription: "JPG, PNG, WebP 이미지의 품질과 형식을 조절해 용량을 줄입니다.", status: "active", sortOrder: 2, logicKey: "image-compress", searchKeywords: ["이미지 압축", "사진 용량 줄이기", "JPG 용량 줄이기", "PNG 용량 줄이기"] }),
    tool({ id: 314, categoryId: 11, slug: "image-resize", title: "이미지 크기 조절", description: "이미지의 가로·세로 해상도를 유지 비율로 변경합니다.", kind: "converter", inputs: null, formula: null, faq: [{ question: "비율은 유지되나요?", answer: "예. 가로나 세로 값을 입력하면 다른 쪽은 원본 비율에 맞춰 조절됩니다." }], relatedToolIds: [202, 313, 304], seoTitle: "이미지 크기 조절 | 도구상자", seoDescription: "JPG, PNG, WebP 이미지의 크기와 해상도를 조절합니다.", status: "active", sortOrder: 2, logicKey: "image-resize", searchKeywords: ["이미지 크기 조절", "이미지 리사이즈", "사진 해상도 변경", "이미지 해상도"] }),
    tool({ id: 315, categoryId: 12, slug: "csv-to-excel", title: "CSV → Excel 변환", description: "CSV 표 데이터를 실제 XLSX Excel 파일로 만듭니다.", kind: "converter", inputs: null, formula: null, faq: [{ question: "한글이 깨지지 않나요?", answer: "UTF-8 기반 CSV를 읽고 XLSX 통합문서로 저장합니다." }], relatedToolIds: [316, 317, 318], seoTitle: "CSV Excel 변환 | 도구상자", seoDescription: "CSV 데이터를 브라우저에서 실제 XLSX Excel 파일로 변환합니다.", status: "active", sortOrder: 1, logicKey: "csv-to-excel", searchKeywords: ["CSV Excel", "CSV 엑셀", "CSV XLSX", "csv to excel"] }),
    tool({ id: 316, categoryId: 12, slug: "excel-to-csv", title: "Excel → CSV 변환", description: "Excel 첫 번째 워크시트를 UTF-8 CSV 파일로 내보냅니다.", kind: "converter", inputs: null, formula: null, faq: [{ question: "여러 시트가 있는 파일은 어떻게 되나요?", answer: "현재는 첫 번째 워크시트를 CSV로 변환합니다." }], relatedToolIds: [315, 317, 318], seoTitle: "Excel CSV 변환 | 도구상자", seoDescription: "Excel XLSX 또는 XLS 파일의 첫 시트를 CSV로 변환합니다.", status: "active", sortOrder: 2, logicKey: "excel-to-csv", searchKeywords: ["Excel CSV", "엑셀 CSV", "XLSX CSV", "excel to csv"] }),
    tool({ id: 317, categoryId: 12, slug: "csv-to-json", title: "CSV → JSON 변환", description: "CSV 첫 줄을 필드명으로 사용해 JSON 배열을 만듭니다.", kind: "converter", inputs: null, formula: null, faq: [{ question: "CSV 첫 줄은 무엇으로 사용되나요?", answer: "각 JSON 객체의 필드 이름으로 사용됩니다." }], relatedToolIds: [318, 315, 316], seoTitle: "CSV JSON 변환 | 도구상자", seoDescription: "CSV 표 데이터를 JSON 배열 파일로 변환합니다.", status: "active", sortOrder: 3, logicKey: "csv-to-json", searchKeywords: ["CSV JSON", "csv to json", "CSV 데이터 변환"] }),
    tool({ id: 318, categoryId: 12, slug: "json-to-csv", title: "JSON → CSV 변환", description: "객체 배열 JSON 데이터를 CSV 표 파일로 만듭니다.", kind: "converter", inputs: null, formula: null, faq: [{ question: "어떤 JSON을 지원하나요?", answer: "최상위가 객체 배열인 JSON을 지원합니다." }], relatedToolIds: [317, 315, 316], seoTitle: "JSON CSV 변환 | 도구상자", seoDescription: "객체 배열 JSON 데이터를 CSV 파일로 변환합니다.", status: "active", sortOrder: 4, logicKey: "json-to-csv", searchKeywords: ["JSON CSV", "json to csv", "JSON 데이터 변환"] }),
    tool({ id: 319, categoryId: 12, slug: "txt-to-pdf", title: "TXT → PDF 변환", description: "일반 텍스트를 페이지 나눔이 있는 PDF로 만듭니다.", kind: "converter", inputs: null, formula: null, faq: [{ question: "표나 이미지도 유지되나요?", answer: "TXT의 일반 텍스트만 PDF 페이지로 구성합니다." }], relatedToolIds: [315, 316, 302], seoTitle: "TXT PDF 변환 | 도구상자", seoDescription: "TXT 텍스트 파일을 브라우저에서 PDF 파일로 변환합니다.", status: "active", sortOrder: 5, logicKey: "txt-to-pdf", searchKeywords: ["TXT PDF", "텍스트 PDF", "메모 PDF 변환"] }),
    tool({ id: 320, categoryId: 16, slug: "unit-area", title: "면적 단위 변환", description: "㎡, 평, 제곱피트, 헥타르를 환산합니다.", kind: "unit", inputs: null, formula: "단위값 = 기준 면적 ÷ 대상 단위 계수", faq: null, relatedToolIds: [104, 301], seoTitle: "면적 단위 변환 | 도구상자", seoDescription: "㎡와 평을 포함한 면적 단위를 빠르게 변환합니다.", status: "active", sortOrder: 1, logicKey: "unit-area", searchKeywords: ["면적 변환", "제곱미터 평", "㎡ 평"] }),
    tool({ id: 321, categoryId: 17, slug: "unit-weight", title: "무게 단위 변환", description: "g, kg, 톤, 파운드, 온스를 환산합니다.", kind: "unit", inputs: null, formula: "단위값 = 기준 무게 ÷ 대상 단위 계수", faq: null, relatedToolIds: [301], seoTitle: "무게 단위 변환 | 도구상자", seoDescription: "그램, 킬로그램, 파운드 등 무게 단위를 변환합니다.", status: "active", sortOrder: 1, logicKey: "unit-weight", searchKeywords: ["무게 변환", "kg g", "파운드 kg"] }),
    tool({ id: 322, categoryId: 18, slug: "unit-volume", title: "부피 단위 변환", description: "mL, L, m³, 컵, 갤런을 환산합니다.", kind: "unit", inputs: null, formula: "단위값 = 기준 부피 ÷ 대상 단위 계수", faq: null, relatedToolIds: [301], seoTitle: "부피 단위 변환 | 도구상자", seoDescription: "밀리리터, 리터, 컵, 갤런 등 부피 단위를 변환합니다.", status: "active", sortOrder: 1, logicKey: "unit-volume", searchKeywords: ["부피 변환", "L mL", "리터 갤런"] }),
    tool({ id: 323, categoryId: 19, slug: "unit-temperature", title: "온도 단위 변환", description: "섭씨, 화씨, 켈빈을 환산합니다.", kind: "unit", inputs: null, formula: "온도는 섭씨를 중간 기준으로 환산", faq: null, relatedToolIds: [301], seoTitle: "온도 단위 변환 | 도구상자", seoDescription: "섭씨, 화씨, 켈빈 온도 단위를 변환합니다.", status: "active", sortOrder: 1, logicKey: "unit-temperature", searchKeywords: ["온도 변환", "섭씨 화씨", "화씨 섭씨"] }),
    tool({ id: 324, categoryId: 20, slug: "unit-speed", title: "속도 단위 변환", description: "m/s, km/h, mph, 노트를 환산합니다.", kind: "unit", inputs: null, formula: "단위값 = 기준 속도 ÷ 대상 단위 계수", faq: null, relatedToolIds: [301], seoTitle: "속도 단위 변환 | 도구상자", seoDescription: "km/h, mph, m/s, 노트 속도 단위를 변환합니다.", status: "active", sortOrder: 1, logicKey: "unit-speed", searchKeywords: ["속도 변환", "kmh mph", "시속 마일"] }),
    tool({ id: 325, categoryId: 21, slug: "unit-data", title: "데이터 용량 변환", description: "B, KB, MB, GB와 KiB, MiB, GiB를 환산합니다.", kind: "unit", inputs: null, formula: "단위값 = 기준 바이트 ÷ 대상 단위 계수", faq: null, relatedToolIds: [301], seoTitle: "데이터 용량 변환 | 도구상자", seoDescription: "KB, MB, GB와 이진 단위 데이터 용량을 변환합니다.", status: "active", sortOrder: 1, logicKey: "unit-data", searchKeywords: ["데이터 용량", "KB MB GB", "파일 용량 변환"] }),
    tool({ id: 326, categoryId: 38, slug: "unit-time", title: "시간 단위 변환", description: "초, 분, 시간, 일, 주를 환산합니다.", kind: "unit", inputs: null, formula: "단위값 = 기준 초 ÷ 대상 단위 계수", faq: null, relatedToolIds: [145, 301], seoTitle: "시간 단위 변환 | 도구상자", seoDescription: "초, 분, 시간, 일, 주 시간 단위를 변환합니다.", status: "active", sortOrder: 1, logicKey: "unit-time", searchKeywords: ["시간 단위", "초 분 시간", "시간 환산"] }),
    tool({ id: 327, categoryId: 39, slug: "unit-pressure", title: "압력 단위 변환", description: "Pa, kPa, bar, atm, psi를 환산합니다.", kind: "unit", inputs: null, formula: "단위값 = 기준 파스칼 ÷ 대상 단위 계수", faq: null, relatedToolIds: [301], seoTitle: "압력 단위 변환 | 도구상자", seoDescription: "파스칼, bar, atm, psi 압력 단위를 변환합니다.", status: "active", sortOrder: 1, logicKey: "unit-pressure", searchKeywords: ["압력 단위", "psi bar", "atm kpa"] }),
    tool({ id: 328, categoryId: 40, slug: "unit-energy", title: "에너지 단위 변환", description: "J, kJ, cal, kcal, Wh, kWh를 환산합니다.", kind: "unit", inputs: null, formula: "단위값 = 기준 줄 ÷ 대상 단위 계수", faq: null, relatedToolIds: [301], seoTitle: "에너지 단위 변환 | 도구상자", seoDescription: "줄, 칼로리, 와트시 에너지 단위를 변환합니다.", status: "active", sortOrder: 1, logicKey: "unit-energy", searchKeywords: ["에너지 단위", "칼로리 줄", "kWh Wh"] }),
  ],
};
