export type GuideSection = { heading: string; paragraphs: string[] };

export type GuideContent = {
  slug: string;
  title: string;
  description: string;
  eyebrow: string;
  intro: string;
  coreAnswer?: string;
  example?: string;
  caution?: string;
  sections: GuideSection[];
  faq: Array<{ question: string; answer: string }>;
  relatedToolSlugs: string[];
  relatedGuideSlugs: string[];
  monetizationCategory: "finance" | "real-estate" | "tax" | "business" | "automobile" | "retirement";
};

export const guideContents: GuideContent[] = [
  {
    slug: "jeonse-vs-monthly-cost-guide",
    title: "전세와 월세 비용 비교 방법: 보증금·월세를 같은 기준으로 계산하기",
    description: "전세와 월세를 비교할 때 보증금 기회비용, 월세, 전환율을 어떤 순서로 계산하는지 설명하고 비교 계산기로 연결합니다.",
    eyebrow: "REAL ESTATE GUIDE",
    intro: "전세와 월세 중 어느 조건이 유리한지는 월세만 보고 결정하기 어렵습니다. 보증금이 묶이는 비용과 월세를 같은 기간 기준으로 바꾸면 두 계약의 차이를 더 명확하게 비교할 수 있습니다.",
    sections: [
      { heading: "전세와 월세 비교에서 먼저 정리할 입력값", paragraphs: ["전세 보증금, 월세 보증금, 월세, 비교 기간, 보증금에 적용할 가정 수익률을 따로 적습니다. 계약 조건이 다르면 관리비·대출이자·보증보험료처럼 실제 부담에 영향을 주는 항목도 별도로 기록해야 합니다.", "이 계산은 특정 계약을 추천하는 것이 아니라 입력한 가정의 비용 차이를 보여주는 참고용 비교입니다."] },
      { heading: "보증금 기회비용을 월 비용으로 바꾸는 방법", paragraphs: ["보증금 차액에 가정한 연 수익률을 곱해 연간 기회비용을 구한 뒤 12개월로 나누면 월 단위 비교가 가능합니다. 실제 대출금리나 투자수익률은 사람마다 다르므로 한 가지 값만 넣기보다 낮은 값과 높은 값을 함께 비교하는 편이 안전합니다.", "계산 결과 아래의 전세 vs 월세 비교 계산기에 보증금과 월세 조건을 넣으면 월간·연간 차이를 한 화면에서 확인할 수 있습니다."] },
      { heading: "계약 전에 추가로 확인할 항목", paragraphs: ["전세대출 이자, 보증보험 가입 가능 여부, 갱신 조건, 중도 해지 비용, 관리비와 수리 책임은 단순 월세 환산에 포함되지 않을 수 있습니다. 계약서와 금융기관 안내를 최종 기준으로 확인하세요."] },
    ],
    faq: [
      { question: "전세 보증금 전체를 비용으로 봐야 하나요?", answer: "보증금 자체는 반환을 전제로 하는 자산이지만, 자금이 묶이거나 대출을 이용한다면 기회비용과 이자가 발생할 수 있습니다. 비교 목적에 따라 보증금 차액의 기회비용을 월 비용으로 환산합니다." },
      { question: "전세와 월세 중 어느 쪽이 항상 유리한가요?", answer: "금리, 보증금, 월세, 거주기간, 보증보험료와 자금 여건에 따라 달라집니다. 계산기는 입력한 가정에 따른 비교값만 제공합니다." },
    ],
    relatedToolSlugs: ["jeonse-vs-monthly", "monthly-rent", "jeonse-loan-interest"],
    relatedGuideSlugs: ["retirement-fund-how-much-guide", "vat-supply-price-guide"],
    monetizationCategory: "real-estate",
  },
  {
    slug: "family-loan-io-document-guide",
    title: "가족간 차용증 작성 전 확인할 항목과 이자 계산 방법",
    description: "가족간 금전거래에서 차용금액·기간·상환방식·이자율을 정리하는 방법과 참고용 이자 계산기를 안내합니다.",
    eyebrow: "FINANCE GUIDE",
    intro: "가족 사이의 돈 거래도 나중에 사실관계와 상환 흐름을 설명할 수 있도록 조건을 명확히 남기는 것이 중요합니다. 차용증은 법률·세무 판단을 대신하지 않지만 거래 조건을 정리하는 출발점이 될 수 있습니다.",
    sections: [
      { heading: "차용증에 정리할 핵심 조건", paragraphs: ["대여일, 원금, 만기일 또는 분할상환 일정, 약정이율, 이자 지급일, 상환 계좌와 연체 시 처리 방법을 구체적으로 적습니다. 당사자와 실제 자금 이동을 확인할 수 있는 자료도 함께 보관하는 것이 좋습니다.", "가족간 거래의 세무상 인정 여부는 거래의 목적·금액·상환능력·실제 이행 등 여러 사실관계에 따라 달라질 수 있습니다."] },
      { heading: "이자 계산에서 상환방식이 중요한 이유", paragraphs: ["만기일시상환은 기간 동안 이자를 계산하고 만기에 원금을 갚는 방식이며, 원금균등분할상환은 원금이 줄어드는 만큼 이자도 달라집니다. 같은 원금·이율이라도 상환방식이 다르면 월별 현금흐름이 달라집니다.", "가족간 차용증 이자 계산기에 원금·기간·이율과 상환방식을 입력하면 방식별 이자와 총 상환액을 비교할 수 있습니다."] },
      { heading: "세무·법률 확인이 필요한 경우", paragraphs: ["무이자 또는 낮은 이율, 큰 금액, 부동산 취득자금, 미성년자 거래, 상환능력과 다른 금액의 거래는 세무사·변호사 또는 관련 기관에 구체적인 사실관계를 확인하세요. 이 페이지와 계산기는 신고나 계약의 결론을 제공하지 않습니다."] },
    ],
    faq: [
      { question: "가족간 차용증에 반드시 이자를 적어야 하나요?", answer: "거래의 성격과 세무·법률 적용은 사실관계에 따라 달라질 수 있습니다. 이자율과 지급일을 포함한 조건을 명확히 기록하고, 실제 이행 여부와 관련된 자료를 보관하는 것이 좋습니다." },
      { question: "계산기 결과가 세무상 인정되는 이자를 의미하나요?", answer: "아닙니다. 계산기는 입력한 원금·기간·이율·상환방식에 따른 산술 결과만 제공합니다. 적용 기준과 신고 여부는 최신 공식 안내 또는 전문가에게 확인해야 합니다." },
    ],
    relatedToolSlugs: ["family-loan-interest", "compound-interest", "simple-interest"],
    relatedGuideSlugs: ["vat-supply-price-guide", "annual-net-pay-guide"],
    monetizationCategory: "finance",
  },
  {
    slug: "retirement-fund-how-much-guide",
    title: "은퇴자금은 얼마가 필요할까? 생활비·연금·물가를 함께 계산하는 방법",
    description: "은퇴 후 생활비와 연금의 차이, 은퇴기간, 물가와 수익률을 반영해 필요한 은퇴자금을 추정하는 방법을 설명합니다.",
    eyebrow: "RETIREMENT GUIDE",
    intro: "은퇴자금은 하나의 정답이 있는 금액이 아니라 은퇴 시점·예상 수명·생활비·연금·물가·수익률 가정에 따라 달라지는 추정치입니다. 먼저 어떤 가정을 사용했는지 확인하면 계산 결과를 더 현실적으로 해석할 수 있습니다.",
    sections: [
      { heading: "은퇴자금 추정에 필요한 입력값", paragraphs: ["현재 나이와 은퇴 나이로 준비 기간을 정하고, 예상 수명으로 은퇴 후 기간을 계산합니다. 월 생활비에서 예상 연금을 뺀 금액이 은퇴 후 매달 필요한 부족액이며, 현재 자산과 예상 수익률을 함께 넣어 부족자금을 추정합니다.", "생활비는 현재 금액만 입력하기보다 의료비·주거비·여가비처럼 은퇴 후 변동할 수 있는 항목을 나누어 생각하는 것이 좋습니다."] },
      { heading: "결과를 한 가지 숫자로 해석하지 않는 방법", paragraphs: ["수익률이 낮아지거나 물가가 높아지면 필요한 자금은 증가할 수 있습니다. 기본값 하나만 믿기보다 보수적·기준·낙관 시나리오를 나누어 비교하세요.", "은퇴자금 계산기는 은퇴 시점 필요자금과 현재 자산 대비 부족자금, 추가 월 저축액을 참고용으로 보여줍니다."] },
      { heading: "연금과 퇴직금은 따로 확인하기", paragraphs: ["국민연금 예상수령액, 퇴직금, 개인연금은 지급 시기와 조건이 서로 다릅니다. 계산기에 입력한 연금이 세전인지 세후인지, 평생 지급인지, 물가에 따라 조정되는지 확인해야 합니다."] },
    ],
    faq: [
      { question: "은퇴자금 계산에서 물가상승률을 넣는 이유는 무엇인가요?", answer: "현재의 월 생활비가 은퇴 시점에도 같은 구매력을 갖는다고 보기 어렵기 때문입니다. 물가상승률은 미래 생활비를 추정하는 가정이며 실제 물가와 다를 수 있습니다." },
      { question: "은퇴자금 결과를 금융상품 가입 기준으로 사용해도 되나요?", answer: "계산기는 참고용 시뮬레이션입니다. 금융상품의 수익률·수수료·세금·지급 조건과 개인의 위험 성향은 별도로 확인해야 합니다." },
    ],
    relatedToolSlugs: ["retirement-fund", "national-pension", "retirement-pay"],
    relatedGuideSlugs: ["pension-retirement-income-guide", "annual-net-pay-guide"],
    monetizationCategory: "retirement",
  },
  {
    slug: "car-monthly-maintenance-cost-guide",
    title: "자동차 월 유지비 계산 항목: 유류비·보험료·세금·정비비 정리",
    description: "자동차 유지비를 월 단위로 비교할 때 필요한 유류비·보험료·자동차세·정비비·주차비 항목을 정리합니다.",
    eyebrow: "AUTOMOBILE GUIDE",
    intro: "자동차 유지비는 주유비만으로 결정되지 않습니다. 주행거리와 연비를 바탕으로 한 유류비에 고정비와 주기적으로 발생하는 비용을 나누어 더하면 차종별 월 부담을 비교하기 쉬워집니다.",
    sections: [
      { heading: "월 유지비를 고정비와 변동비로 나누기", paragraphs: ["유류비·통행료·주차비는 사용량에 따라 바뀌는 변동비이고, 자동차세·보험료·정기점검·소모품은 월 환산이 필요한 비용입니다. 연간 비용은 12개월로 나누고, 주행거리에 따라 달라지는 항목은 별도로 계산합니다.", "자동차 유지비 계산기는 주행거리·연비·유류비와 자동차세·보험료·정비비를 함께 입력해 월·연간 비용을 추정합니다."] },
      { heading: "차량을 비교할 때 같은 조건을 쓰기", paragraphs: ["차량마다 연비·보험료·정비비·세금이 다르므로 같은 월 주행거리와 같은 유류비 가정을 사용해야 비교가 가능합니다. 신차와 중고차는 감가·수리비·보증기간이 달라 별도 항목으로 두세요."] },
      { heading: "자동차 비용과 사업 경비를 구분하기", paragraphs: ["사업용 차량의 비용 처리 여부는 운행 목적·명의·증빙·세법과 사업 형태에 따라 달라질 수 있습니다. 일반 가계의 유지비 계산 결과를 사업자 세무 처리 금액으로 바로 사용하지 마세요."] },
    ],
    faq: [
      { question: "자동차 유지비에 감가상각이나 차량 할부금을 넣어야 하나요?", answer: "목적에 따라 다릅니다. 실제 보유 비용을 비교하려면 할부금·감가·주차비를 별도 항목으로 추가하고, 운행비만 비교하려면 유류비·세금·보험·정비처럼 운영비 중심으로 계산합니다." },
      { question: "자동차 유지비 계산 결과가 실제 비용과 다른 이유는 무엇인가요?", answer: "주행거리, 보험 경력, 지역, 차종, 정비 시기와 유류비가 달라질 수 있기 때문입니다. 계산기는 입력값에 따른 비교용 추정치입니다." },
    ],
    relatedToolSlugs: ["maintenance-cost", "fuel-cost", "parking-fee"],
    relatedGuideSlugs: ["small-business-fixed-cost-guide", "vat-supply-price-guide"],
    monetizationCategory: "automobile",
  },
  {
    slug: "roas-break-even-guide",
    title: "손익분기 ROAS 계산 방법: 광고비·원가·수수료까지 반영하기",
    description: "ROAS가 높아도 이익이 아닐 수 있는 이유와 광고비·상품원가·플랫폼 수수료를 반영한 손익분기 ROAS 계산 방법을 설명합니다.",
    eyebrow: "BUSINESS GUIDE",
    intro: "ROAS는 광고매출을 광고비로 나눈 비율이지만, 상품 원가와 플랫폼 수수료까지 반영한 실제 이익과는 다릅니다. 광고 의사결정에는 ROAS와 광고 후 이익을 함께 보는 것이 필요합니다.",
    sections: [
      { heading: "ROAS와 광고 후 이익은 다른 지표", paragraphs: ["광고비 100만원으로 매출 400만원이 발생하면 ROAS는 400%입니다. 그러나 상품 원가·수수료·배송·반품·기타 비용을 차감하면 실제 이익은 달라집니다.", "ROAS 계산기에 광고비·광고매출·상품 원가·플랫폼 수수료율·기타 비용을 넣으면 기본 ROAS와 광고 후 이익을 함께 확인할 수 있습니다."] },
      { heading: "손익분기 ROAS를 해석하는 방법", paragraphs: ["손익분기 ROAS는 입력한 원가율과 수수료율 조건에서 광고 후 이익이 0원이 되는 최소 수준을 의미합니다. 상품 마진이 낮으면 손익분기 ROAS가 높아지고, 광고 외 고정비를 넣으면 결과가 달라질 수 있습니다."] },
      { heading: "캠페인 비교 전에 동일한 비용 범위 사용하기", paragraphs: ["캠페인마다 매출 집계 기간, 쿠폰, 무료배송, 반품과 부가세 포함 여부가 다르면 ROAS만 비교하기 어렵습니다. 동일한 매출 정의와 비용 범위를 정한 뒤 비교하세요."] },
    ],
    faq: [
      { question: "ROAS가 300%면 무조건 흑자인가요?", answer: "아닙니다. 상품 원가율과 수수료율, 배송·반품·쿠폰·인건비 등 광고 외 비용에 따라 손익분기점이 달라집니다." },
      { question: "목표 ROAS는 어떻게 정하나요?", answer: "판매가에서 상품 원가와 변동비를 제외한 기여이익을 확인한 뒤 광고비를 감당할 수 있는 수준을 기준으로 정합니다. 계산기는 입력값에 따른 참고값을 제공합니다." },
    ],
    relatedToolSlugs: ["roas", "margin", "break-even"],
    relatedGuideSlugs: ["small-business-fixed-cost-guide", "annual-net-pay-guide"],
    monetizationCategory: "business",
  },
  {
    slug: "annual-net-pay-guide",
    title: "연봉 실수령액과 월급 실수령액이 달라지는 이유",
    description: "연봉을 12개월로 나눈 금액과 실제 월급이 다른 이유, 비과세액·공제·상여를 비교하는 방법을 설명합니다.",
    eyebrow: "SALARY GUIDE",
    intro: "연봉을 12개월로 나눈 금액은 세전 월 환산액일 뿐 실제 입금액과 같지 않습니다. 공제 항목과 비과세 수당, 상여 지급 방식이 달라지면 같은 연봉에서도 월 실수령액이 달라질 수 있습니다.",
    sections: [
      { heading: "연봉에서 월 실수령액으로 내려가는 과정", paragraphs: ["세전 급여에서 4대보험과 소득세·지방소득세 등 공제액을 빼고, 비과세 수당이 있다면 과세 대상 급여와 구분합니다. 회사의 급여 구성과 개인의 부양가족·공제 조건에 따라 실제 원천징수액이 달라질 수 있습니다.", "연봉 실수령액 계산기와 월급 실수령액 계산기를 각각 사용하면 연봉 기준과 월 급여 기준의 차이를 비교할 수 있습니다."] },
      { heading: "연봉 비교 때 확인할 계약 조건", paragraphs: ["퇴직금 포함 여부, 고정 상여, 성과급, 식대·차량 유지비 같은 비과세 또는 수당 항목, 수습기간 급여를 확인해야 합니다. 채용 제안의 연봉 숫자만 비교하면 실제 현금흐름을 놓칠 수 있습니다."] },
      { heading: "계산 결과를 급여명세서와 비교하기", paragraphs: ["계산기는 일반적인 조건의 참고값입니다. 실제 급여명세서에서는 국민연금·건강보험·고용보험·소득세의 산정 기준과 회사 급여 규정을 확인하세요."] },
    ],
    faq: [
      { question: "연봉을 12로 나누면 월 실수령액인가요?", answer: "아닙니다. 12로 나눈 값은 보통 세전 월 환산액이며, 실제 지급액은 공제와 비과세·상여 조건을 반영한 뒤 달라집니다." },
      { question: "실수령액 계산기는 정확한 급여명세서를 대신하나요?", answer: "아닙니다. 계산기는 입력 조건에 따른 참고용 추정이며, 실제 급여는 회사의 급여 규정과 최신 공제 기준을 적용합니다." },
    ],
    relatedToolSlugs: ["annual-take-home", "monthly-take-home", "four-insurance"],
    relatedGuideSlugs: ["retirement-fund-how-much-guide", "vat-supply-price-guide"],
    monetizationCategory: "finance",
  },
  {
    slug: "vat-supply-price-guide",
    title: "부가세 포함 금액에서 공급가액과 부가세를 역산하는 방법",
    description: "부가세 포함 금액과 공급가액의 차이, 10% 부가세를 기준으로 양방향 계산하는 방법과 주의사항을 설명합니다.",
    eyebrow: "TAX GUIDE",
    intro: "견적서나 영수증의 금액이 부가세 포함인지 별도인지에 따라 공급가액과 세액을 해석하는 방법이 달라집니다. 금액의 기준을 먼저 확인한 뒤 역산해야 합니다.",
    sections: [
      { heading: "공급가액과 부가세 포함 금액 구분하기", paragraphs: ["공급가액은 부가세를 제외한 과세 대상 금액이고, 부가세 포함 금액은 공급가액과 세액을 더한 금액입니다. 일반적인 10% 부가세 가정에서는 포함 금액을 1.1로 나누어 공급가액을 추정합니다.", "부가세 계산기는 공급가액에서 포함 금액을 계산하거나, 포함 금액에서 공급가액과 세액을 역산하는 양방향 기능을 제공합니다."] },
      { heading: "거래 유형과 세율 확인하기", paragraphs: ["실제 신고에는 과세·면세·영세율 여부, 매입세액 공제, 사업자 유형과 거래 증빙이 영향을 줍니다. 모든 거래에 동일한 계산을 적용할 수 있는 것은 아닙니다."] },
      { heading: "견적과 신고 금액을 구분하기", paragraphs: ["계산기 결과는 견적·가격 검토용 참고값입니다. 신고서 작성이나 환급·납부 판단에는 국세청 최신 안내와 세무 전문가의 확인이 필요합니다."] },
    ],
    faq: [
      { question: "부가세 포함 금액에서 부가세 10%를 바로 빼면 되나요?", answer: "포함 금액의 10%가 세액인 것은 아닙니다. 일반적인 10% 가정에서는 포함 금액을 11로 나눈 값이 세액에 해당하고, 공급가액은 포함 금액에서 세액을 뺀 값입니다." },
      { question: "모든 사업자가 같은 부가세 계산을 사용하나요?", answer: "사업자 유형, 거래의 과세 여부와 적용 세율에 따라 달라질 수 있습니다. 계산기는 일반적인 입력값에 따른 참고용 산술 결과입니다." },
    ],
    relatedToolSlugs: ["vat-calculator", "margin", "fee"],
    relatedGuideSlugs: ["small-business-fixed-cost-guide", "annual-net-pay-guide"],
    monetizationCategory: "tax",
  },
  {
    slug: "small-business-fixed-cost-guide",
    title: "소상공인 손익분기점 계산: 고정비와 판매량을 나누어 보기",
    description: "임대료·인건비 같은 고정비와 판매단가·변동비를 구분해 사업 손익분기 판매량을 계산하는 방법을 안내합니다.",
    eyebrow: "BUSINESS GUIDE",
    intro: "사업의 매출이 늘어도 변동비가 함께 증가하면 이익이 바로 늘지 않을 수 있습니다. 고정비와 변동비를 나누면 몇 개를 팔아야 비용을 회수하는지 더 명확하게 볼 수 있습니다.",
    sections: [
      { heading: "고정비와 변동비 구분하기", paragraphs: ["임대료·기본 인건비·구독료처럼 판매량과 관계없이 발생하는 비용은 고정비로, 재료비·판매 수수료·포장비처럼 판매량에 따라 늘어나는 비용은 변동비로 분류합니다.", "손익분기점 계산기는 고정비·판매단가·변동비를 입력해 손익분기 판매수량과 매출을 참고 계산합니다."] },
      { heading: "판매량 목표와 실제 이익은 다르다", paragraphs: ["손익분기점은 이익이 0원이 되는 지점입니다. 목표 이익을 만들려면 손익분기 판매량에 목표 이익을 더해 판매단가와 단위당 공헌이익을 다시 계산해야 합니다.", "마진율 계산기와 ROAS 계산기를 함께 사용하면 판매가·원가·광고비를 나누어 볼 수 있습니다."] },
      { heading: "월별 현금흐름으로 다시 확인하기", paragraphs: ["세금 납부, 재고 구매, 카드 매출 입금 시차, 대출 상환은 손익계산과 현금흐름에 다르게 영향을 줍니다. 손익분기점 결과만으로 자금 부족 여부를 판단하지 마세요."] },
    ],
    faq: [
      { question: "손익분기점 판매량이 낮으면 사업이 안전한가요?", answer: "그것만으로 판단할 수 없습니다. 판매량 변동, 현금흐름, 재고, 세금, 부채와 실제 고객 확보 비용을 함께 확인해야 합니다." },
      { question: "광고비는 고정비인가요 변동비인가요?", answer: "캠페인 운영 방식에 따라 다릅니다. 판매량과 함께 증가하면 변동비에 가깝고, 월 정액 집행이면 고정비처럼 관리할 수 있습니다. 분석 목적에 맞춰 일관되게 분류하세요." },
    ],
    relatedToolSlugs: ["break-even", "margin", "roas"],
    relatedGuideSlugs: ["roas-break-even-guide", "vat-supply-price-guide"],
    monetizationCategory: "business",
  },
  {
    slug: "pension-retirement-income-guide",
    title: "국민연금·퇴직금·은퇴자금을 함께 확인하는 순서",
    description: "은퇴 준비에서 국민연금 예상액·퇴직금·개인 자산을 어떤 순서로 확인하고 부족자금을 추정하는지 안내합니다.",
    eyebrow: "RETIREMENT GUIDE",
    intro: "은퇴 준비는 하나의 계산기 결과보다 연금과 자산을 같은 기간 기준으로 정리하는 과정에 가깝습니다. 지급 시기와 금액의 성격이 다른 항목을 분리한 뒤 부족한 생활비를 추정하세요.",
    sections: [
      { heading: "먼저 현금흐름 시점을 정리하기", paragraphs: ["국민연금·퇴직연금·개인연금은 지급 개시 연령과 방식이 다를 수 있습니다. 은퇴 직후부터 연금이 나오는지, 일시금인지, 물가 조정이 있는지 확인한 후 월 생활비와 비교합니다.", "국민연금 예상수령액 계산기와 퇴직금 계산기를 각각 사용한 뒤 은퇴자금 계산기의 예상 월 연금 입력값에 반영할 수 있습니다."] },
      { heading: "부족자금은 가정별로 비교하기", paragraphs: ["생활비·물가·수익률·예상 수명을 바꾸어 보수적 시나리오와 기준 시나리오를 비교하세요. 연금이 있어도 의료비·주거비·간병비처럼 별도 준비가 필요한 항목이 있을 수 있습니다."] },
      { heading: "공식 예상액과 계산기 추정치를 구분하기", paragraphs: ["사이트 계산기는 입력값을 바탕으로 한 참고용 추정치입니다. 실제 연금 가입 기록과 지급 예상액은 국민연금공단 등 공식 기관의 조회 결과를 기준으로 확인하세요."] },
    ],
    faq: [
      { question: "국민연금 예상액을 은퇴자금 계산기에 그대로 넣어도 되나요?", answer: "지급 시점·세전 여부·물가 반영 여부를 확인한 뒤 계산 목적에 맞게 입력해야 합니다. 공식 조회 결과와 계산기의 가정이 다르면 결과도 달라질 수 있습니다." },
      { question: "퇴직금과 은퇴자금은 같은 금액인가요?", answer: "아닙니다. 퇴직금은 근로기간과 임금 등에 따라 산정되는 별도 항목이며, 은퇴자금은 은퇴 후 생활비를 충당하기 위해 필요한 전체 자산을 의미합니다." },
    ],
    relatedToolSlugs: ["national-pension", "retirement-pay", "retirement-fund"],
    relatedGuideSlugs: ["retirement-fund-how-much-guide", "annual-net-pay-guide"],
    monetizationCategory: "retirement",
  },
  {
    slug: "four-insurance-payroll-guide",
    title: "월급에서 4대보험 공제액이 달라지는 이유와 확인 순서",
    description: "월급에서 국민연금·건강보험·고용보험·장기요양보험 공제가 어떻게 달라지는지 계산기와 함께 확인합니다.",
    eyebrow: "SALARY & TAX GUIDE",
    intro: "같은 세전 월급이라도 보수월액, 비과세 항목, 가입 유형과 기준 시점에 따라 4대보험 공제액이 달라질 수 있습니다.",
    coreAnswer: "먼저 세전 급여와 비과세 급여를 구분한 뒤 근로자 부담분과 사업주 부담분을 나누어 확인해야 합니다.",
    example: "세전 월급과 비과세 식대, 가입 기준을 입력하고 월급 실수령액과 4대보험 계산기 결과를 함께 비교하세요.",
    caution: "보험료율과 기준소득월액은 시점·가입 유형에 따라 달라질 수 있으므로 실제 급여명세서와 공식 안내를 최종 기준으로 확인하세요.",
    sections: [
      { heading: "급여명세서에서 먼저 확인할 항목", paragraphs: ["세전 급여, 비과세 수당, 보험료 산정 기준이 되는 보수 항목을 구분합니다. 급여 총액과 보험료 산정 기준이 항상 같은 것은 아닐 수 있습니다.", "4대보험 계산기는 입력한 가정으로 근로자와 사업주의 기본 부담액을 비교하는 참고 도구입니다."] },
      { heading: "근로자 부담과 사업주 부담 구분하기", paragraphs: ["급여에서 빠지는 금액은 근로자 부담분이며 사업주 부담분은 급여 공제액과 별도로 회사가 부담합니다. 두 금액을 합쳐 개인의 공제액으로 오해하지 않도록 구분하세요."] },
    ],
    faq: [
      { question: "4대보험 공제액이 매달 같은가요?", answer: "보수 변경, 정산, 휴직·복직, 가입 기준 변경에 따라 달라질 수 있습니다. 실제 급여명세서와 사업장 안내를 확인하세요." },
      { question: "계산기 결과가 급여명세서와 다른 이유는 무엇인가요?", answer: "비과세 항목, 기준소득월액, 정산분과 적용 시점이 계산기의 가정과 다를 수 있기 때문입니다." },
    ],
    relatedToolSlugs: ["four-insurance", "monthly-take-home", "annual-net"],
    relatedGuideSlugs: ["annual-net-pay-guide", "weekly-holiday-pay-guide"],
    monetizationCategory: "tax",
  },
  {
    slug: "weekly-holiday-pay-guide",
    title: "주휴수당 계산 방법: 주 15시간·시급·근무일수 확인하기",
    description: "주휴수당을 계산할 때 시급과 주당 근로시간, 개근 조건을 어떻게 정리하는지 안내합니다.",
    eyebrow: "SALARY GUIDE",
    intro: "주휴수당은 시급 하나만으로 결정되지 않습니다. 주당 소정근로시간과 근무일수, 개근 여부를 함께 확인해야 계산 결과를 해석할 수 있습니다.",
    coreAnswer: "주휴수당을 확인하려면 시급·주당 소정근로시간·1일 근로시간을 같은 주 기준으로 정리해야 합니다.",
    example: "시급과 주당 근로시간을 입력해 주급과 주휴수당을 계산한 뒤, 실제 근로계약서의 소정근로시간과 비교하세요.",
    caution: "근로계약과 실제 근무 형태, 결근·휴업·단시간 근로 여부에 따라 적용이 달라질 수 있어 계산 결과를 임금 확정액으로 사용하지 마세요.",
    sections: [
      { heading: "주휴수당 계산에 필요한 입력값", paragraphs: ["시급, 주당 소정근로시간, 주당 근무일수와 1일 근로시간을 확인합니다. 실제 근무시간과 계약상 소정근로시간이 다르면 어느 기준을 적용할지 먼저 정리해야 합니다.", "주휴수당 계산기는 입력한 조건을 기준으로 예상 주휴수당과 주급을 보여줍니다."] },
      { heading: "주급과 월급을 혼동하지 않기", paragraphs: ["주급은 한 주 기준 금액이고 월급은 월 환산 기준이므로 단순히 4배 하는 방식은 실제 급여 산정과 다를 수 있습니다. 월 환산이 필요하면 시급 계산기와 근무시간 계산기를 함께 사용하세요."] },
    ],
    faq: [
      { question: "주 15시간이면 항상 주휴수당이 발생하나요?", answer: "소정근로시간과 개근 여부 등 여러 요건을 함께 확인해야 합니다. 이 페이지는 일반적인 계산 구조를 설명하는 참고 자료입니다." },
      { question: "알바 주휴수당을 계산기에 나온 그대로 청구해도 되나요?", answer: "아닙니다. 근로계약서, 근무기록과 최신 공식 기준을 확인한 뒤 실제 지급액을 판단하세요." },
    ],
    relatedToolSlugs: ["weekly-holiday-pay", "hourly-wage", "work-hours"],
    relatedGuideSlugs: ["four-insurance-payroll-guide", "annual-net-pay-guide"],
    monetizationCategory: "finance",
  },
  {
    slug: "real-estate-brokerage-fee-guide",
    title: "부동산 중개수수료 계산 방법: 거래금액·상한요율 확인하기",
    description: "매매·전세·월세 중개보수를 비교할 때 거래금액과 적용 요율, 부가세 여부를 확인하는 방법을 안내합니다.",
    eyebrow: "REAL ESTATE GUIDE",
    intro: "부동산 중개수수료는 거래 유형과 금액, 적용 구간에 따라 달라집니다. 계산 전 거래금액을 어떤 방식으로 산정하는지부터 확인해야 합니다.",
    coreAnswer: "중개보수는 거래 유형과 거래금액을 확정한 뒤 해당 구간의 상한요율을 적용해 참고 금액을 계산합니다.",
    example: "매매가 또는 전세보증금, 월세 거래라면 보증금과 월세 환산 기준을 확인해 중개보수 계산기에 입력하세요.",
    caution: "지역·거래 유형·적용 시점·부가세와 실제 협의 조건에 따라 달라질 수 있으므로 계약 전 중개사와 공식 기준을 확인하세요.",
    sections: [
      { heading: "거래 유형별 거래금액 정리", paragraphs: ["매매는 매매대금, 전세는 보증금, 월세는 보증금과 월세를 기준으로 거래금액을 산정하는 방식이 달라질 수 있습니다. 계약서와 최신 요율표를 먼저 확인합니다.", "중개보수 계산기는 입력한 거래금액과 요율을 바탕으로 상한액을 참고 계산합니다."] },
      { heading: "상한액과 실제 지급액 구분하기", paragraphs: ["계산 결과가 곧 확정 지급액을 뜻하는 것은 아닙니다. 중개보수는 상한 범위, 협의 내용, 부가세 처리와 계약 조건을 함께 확인해야 합니다."] },
    ],
    faq: [
      { question: "계산기에 나온 금액을 반드시 지급해야 하나요?", answer: "계산기는 입력값과 상한요율을 기준으로 한 참고값입니다. 실제 지급 조건은 계약 당사자와 중개사, 최신 공식 기준을 확인하세요." },
      { question: "월세 거래금액은 월세만 입력하나요?", answer: "지역과 적용 기준에 따라 보증금과 월세를 환산하는 방식이 달라질 수 있습니다. 거래 유형에 맞는 기준을 확인하세요." },
    ],
    relatedToolSlugs: ["brokerage-fee", "monthly-rent", "jeonse-vs-monthly"],
    relatedGuideSlugs: ["jeonse-vs-monthly-cost-guide", "family-loan-io-document-guide"],
    monetizationCategory: "real-estate",
  },
  {
    slug: "loan-interest-comparison-guide",
    title: "대출 이자 계산과 원리금균등·원금균등 비교 방법",
    description: "대출 원금·금리·기간을 기준으로 월 상환액과 총이자를 비교하고 상환방식 차이를 이해하는 방법입니다.",
    eyebrow: "FINANCE GUIDE",
    intro: "대출 조건을 비교할 때 금리만 보는 것보다 상환방식과 기간에 따른 월 현금흐름, 총이자를 함께 확인하는 것이 중요합니다.",
    coreAnswer: "같은 원금과 금리라도 상환방식과 기간에 따라 월 납입액과 총이자가 달라지므로 두 값을 같이 비교해야 합니다.",
    example: "대출 원금·연이율·기간을 동일하게 넣고 원리금균등과 원금균등의 첫 달 납입액, 총이자를 비교하세요.",
    caution: "실제 금융상품에는 우대금리, 변동금리, 거치기간, 중도상환수수료와 원 단위 절사 등이 반영될 수 있습니다.",
    sections: [
      { heading: "월 납입액과 총이자를 따로 보기", paragraphs: ["월 납입액이 낮아도 기간이 길면 총이자가 늘어날 수 있습니다. 반대로 초기 납입액이 높은 방식은 총이자가 줄어들 수 있어 현금흐름과 비용을 함께 봐야 합니다.", "대출 이자 계산기와 원리금 상환 계산기를 이용해 월 납입액과 총 상환액을 비교하세요."] },
      { heading: "금리 비교 전에 동일 조건 만들기", paragraphs: ["대출금액, 기간, 거치기간, 금리 유형이 다르면 결과 비교가 어렵습니다. 먼저 동일한 조건을 입력한 뒤 한 요소씩 바꾸어 민감도를 확인합니다."] },
    ],
    faq: [
      { question: "원리금균등이 항상 더 유리한가요?", answer: "월 현금흐름을 일정하게 관리하기 쉬운 방식일 수 있지만, 총이자와 초기 상환 부담은 개인 조건에 따라 달라집니다." },
      { question: "계산기 결과가 금융기관 상환표와 다른 이유는 무엇인가요?", answer: "납입일, 금리 변동, 거치기간, 우대조건과 절사 규칙이 계산기의 가정과 다를 수 있기 때문입니다." },
    ],
    relatedToolSlugs: ["loan-interest", "loan-amortization", "monthly-rent"],
    relatedGuideSlugs: ["family-loan-io-document-guide", "jeonse-vs-monthly-cost-guide"],
    monetizationCategory: "finance",
  },
  {
    slug: "retirement-income-tax-guide",
    title: "퇴직소득세 계산 전 확인할 항목과 예상 수령액 보는 법",
    description: "퇴직급여·근속연수·퇴직소득세를 계산할 때 결과를 해석하고 공식 정산과 구분하는 방법을 안내합니다.",
    eyebrow: "RETIREMENT & TAX GUIDE",
    intro: "퇴직급여에서 실제 수령액을 추정하려면 퇴직급여 총액뿐 아니라 근속연수와 과세 방식, 귀속연도별 기준을 함께 확인해야 합니다.",
    coreAnswer: "퇴직소득세 계산기는 입력값에 따른 예상치이므로 퇴직급여·근속연수·세액·지방소득세를 단계별로 나누어 확인해야 합니다.",
    example: "퇴직급여와 근속연수를 입력해 예상 세액을 확인한 뒤 회사 정산 내역과 국세청 안내를 비교하세요.",
    caution: "중간정산, 과세이연, 특별한 퇴직 사유와 귀속연도별 세법에 따라 실제 세액이 달라질 수 있습니다.",
    sections: [
      { heading: "퇴직급여와 퇴직소득세 구분하기", paragraphs: ["퇴직급여는 세전 지급액이고 퇴직소득세는 과세 계산을 거친 공제 항목입니다. 지방소득세와 실제 원천징수 방식도 별도로 확인해야 합니다.", "퇴직소득세 계산기는 단순화된 입력값으로 예상 세액과 수령액을 보여주는 참고 도구입니다."] },
      { heading: "근속연수와 정산 자료 확인하기", paragraphs: ["입사일·퇴사일, 중간정산 여부, 퇴직급여 구성 항목을 확인해야 합니다. 급여명세서와 회사의 퇴직소득 원천징수 내역을 보관하세요."] },
    ],
    faq: [
      { question: "계산기 결과를 세금 신고 금액으로 사용해도 되나요?", answer: "아닙니다. 실제 신고와 원천징수는 공식 정산자료와 최신 세법을 기준으로 확인해야 합니다." },
      { question: "퇴직금이 많으면 세율이 단순히 같은 비율로 오르나요?", answer: "퇴직소득은 일반 근로소득과 계산 구조가 다를 수 있어 금액·근속연수·공제 구조를 함께 확인해야 합니다." },
    ],
    relatedToolSlugs: ["retirement-income-tax", "retirement-pay", "annual-net"],
    relatedGuideSlugs: ["pension-retirement-income-guide", "retirement-fund-how-much-guide"],
    monetizationCategory: "tax",
  },
  {
    slug: "commute-fuel-cost-guide",
    title: "출퇴근 자동차 기름값 계산: 거리·연비·월 주행일수 기준",
    description: "출퇴근 거리와 연비, 유가, 근무일수를 이용해 월 주유비를 비교하고 차량 유지비와 연결하는 방법입니다.",
    eyebrow: "AUTOMOBILE GUIDE",
    intro: "출퇴근 기름값은 하루 이동거리보다 왕복거리와 실제 운행일수, 차량 연비와 유가를 함께 넣어야 현실적인 월 비용에 가까워집니다.",
    coreAnswer: "왕복거리 × 월 운행일수를 먼저 계산한 뒤 연비와 리터당 유가를 적용하면 월 주유비를 비교할 수 있습니다.",
    example: "주유비 계산기에 왕복거리와 월 운행일수를 반영한 총거리, 연비와 유가를 입력하고 자동차 유지비 계산기에서 보험·세금·정비비를 더해 보세요.",
    caution: "교통체증, 계절, 운전습관, 주차비·통행료와 실제 유가 변동은 계산 결과에 포함되지 않을 수 있습니다.",
    sections: [
      { heading: "출퇴근 거리는 왕복 기준으로 입력하기", paragraphs: ["편도 거리만 알고 있다면 왕복으로 환산한 뒤 실제 출근일수와 재택근무일을 반영합니다. 휴일·휴가·출장을 평균적으로 조정하면 월 비교가 더 현실적입니다.", "주유비 계산기는 거리·연비·유가로 예상 연료량과 주유비를 계산합니다."] },
      { heading: "주유비와 보유비용을 나누어 보기", paragraphs: ["주유비는 변동비이고 자동차세·보험료·정비비는 월 또는 연간 환산이 필요한 비용입니다. 차량을 비교할 때는 자동차 유지비 계산기에서 같은 주행조건으로 확인하세요."] },
    ],
    faq: [
      { question: "연비는 공인연비를 입력하면 되나요?", answer: "공인연비는 비교 기준으로 사용할 수 있지만 실제 도심·고속도로 비율과 운전습관에 따라 실연비가 달라질 수 있습니다." },
      { question: "출퇴근 기름값만 보면 차량 선택이 가능한가요?", answer: "아닙니다. 보험료·세금·정비·주차·감가와 초기 구매비용을 함께 비교해야 합니다." },
    ],
    relatedToolSlugs: ["fuel-cost", "maintenance-cost", "parking-fee"],
    relatedGuideSlugs: ["car-monthly-maintenance-cost-guide", "small-business-fixed-cost-guide"],
    monetizationCategory: "automobile",
  },
  {
    slug: "freelancer-project-quote-guide",
    title: "프리랜서 프로젝트 견적 계산: 시급·예상시간·마진 정리",
    description: "프리랜서와 소규모 사업자가 프로젝트 견적에 작업시간·추가비용·마진을 반영하는 방법을 안내합니다.",
    eyebrow: "BUSINESS GUIDE",
    intro: "프로젝트 견적은 작업시간만 곱하는 것이 아니라 회의·수정·프로젝트 관리와 외주·운영비를 포함해 산정해야 실제 수익성을 판단하기 쉽습니다.",
    coreAnswer: "시간당 단가와 예상 작업시간에 추가 비용과 목표 마진을 일관된 기준으로 반영해야 견적과 실제 이익을 비교할 수 있습니다.",
    example: "프로젝트 견적 계산기에 시간당 단가·예상시간·추가비용·마진율을 넣고 마진율 계산기와 손익분기점 계산기로 결과를 교차 확인하세요.",
    caution: "부가세 포함 여부, 원천징수, 플랫폼 수수료, 수정 범위와 대금 지급 시점을 계약서에서 별도로 확인하세요.",
    sections: [
      { heading: "견적에 포함할 작업시간 범위", paragraphs: ["고객 미팅, 자료조사, 디자인·개발, 검수와 수정시간을 나누어 적습니다. 실제 작업 외 시간이 빠지면 시간당 실질 수익이 낮아질 수 있습니다.", "프로젝트 견적 계산기는 입력한 시간당 단가와 예상시간, 추가비용·마진을 기준으로 참고 견적을 계산합니다."] },
      { heading: "마진과 현금흐름을 함께 확인하기", paragraphs: ["견적상 이익과 실제 현금 유입은 다를 수 있습니다. 선금·잔금, 플랫폼 수수료, 세금과 미수금 위험을 별도로 관리하세요."] },
    ],
    faq: [
      { question: "시간당 단가는 어떻게 정하나요?", answer: "목표 월수입과 유급 작업시간, 운영비·세금·휴가 기간을 함께 고려해 기준을 정하고 프로젝트별 난이도와 책임 범위를 조정하세요." },
      { question: "마진율과 마크업률은 같은가요?", answer: "판매가 대비 이익 비율과 원가에 더하는 비율은 계산 기준이 다릅니다. 마진율 계산기에서 두 값을 구분해 확인하세요." },
    ],
    relatedToolSlugs: ["project-quote", "margin", "break-even"],
    relatedGuideSlugs: ["small-business-fixed-cost-guide", "roas-break-even-guide"],
    monetizationCategory: "business",
  },
  {
    slug: "small-business-roas-margin-guide",
    title: "광고 ROAS와 마진율을 함께 보는 소상공인 광고비 계산",
    description: "광고매출만 보는 대신 상품 마진·플랫폼 수수료·고정비를 함께 반영해 광고 효율을 판단하는 방법입니다.",
    eyebrow: "BUSINESS GUIDE",
    intro: "ROAS가 높아도 상품 마진이 낮거나 수수료와 배송비가 크면 광고 후 이익이 작을 수 있습니다. ROAS와 마진율을 같은 비용 기준으로 연결해 보세요.",
    coreAnswer: "광고 의사결정은 ROAS 하나가 아니라 광고 후 이익, 상품 마진, 고정비 회수 가능성을 함께 확인해야 합니다.",
    example: "ROAS 계산기에 광고비·매출·원가·수수료를 입력하고 마진율·손익분기점 계산기로 목표 판매량과 이익을 비교하세요.",
    caution: "매출 집계 시점, 쿠폰·반품·무료배송·부가세 처리 범위를 캠페인마다 동일하게 맞추지 않으면 ROAS 비교가 왜곡될 수 있습니다.",
    sections: [
      { heading: "ROAS와 마진율을 같은 주문 기준으로 계산하기", paragraphs: ["광고 매출에서 상품 원가와 플랫폼 수수료, 배송·반품·쿠폰 비용을 차감한 금액이 광고비를 감당하는지 확인합니다.", "ROAS 계산기는 광고 후 이익과 손익분기 ROAS를 함께 확인할 수 있고, 마진율 계산기는 판매가와 원가의 관계를 보여줍니다."] },
      { heading: "고정비 회수까지 연결하기", paragraphs: ["광고 후 이익이 양수여도 임대료·인건비·구독료 같은 고정비를 회수하지 못할 수 있습니다. 손익분기점 계산기로 월 목표 판매량까지 연결하세요."] },
    ],
    faq: [
      { question: "ROAS가 300%면 광고를 늘려도 되나요?", answer: "상품 마진과 수수료, 재고·현금흐름과 광고 확장에 따른 효율 변화를 함께 확인해야 합니다. ROAS만으로 증액을 결정하지 마세요." },
      { question: "광고비는 마진 계산에 어떻게 넣나요?", answer: "상품 단위 변동비와 광고비 배분 기준을 먼저 정한 뒤, 캠페인·기간·주문 기준을 일관되게 적용해야 합니다." },
    ],
    relatedToolSlugs: ["roas", "margin", "break-even"],
    relatedGuideSlugs: ["roas-break-even-guide", "small-business-fixed-cost-guide"],
    monetizationCategory: "business",
  },
  {
    slug: "early-repayment-fee-guide",
    title: "대출 중도상환수수료 계산 방법과 갈아타기 손익분기점",
    description: "대출을 중도상환하거나 갈아탈 때 수수료·이자절감액·잔여기간을 함께 비교하는 방법을 안내합니다.",
    eyebrow: "FINANCE GUIDE",
    intro: "대출을 빨리 갚거나 다른 상품으로 갈아탈 때는 금리만 비교하면 안 됩니다. 남은 이자와 중도상환수수료, 부대비용을 같은 기간 기준으로 비교해야 실제 절감액을 판단할 수 있습니다.",
    coreAnswer: "중도상환의 실익은 남은 기간 동안 줄어드는 이자에서 중도상환수수료와 신규 대출 비용을 뺀 금액으로 비교해야 합니다.",
    example: "남은 원금·잔여기간·현재 금리와 중도상환수수료를 입력하고 대출 이자 계산기와 중도상환수수료 계산기를 함께 사용해 절감액을 비교하세요.",
    caution: "실제 수수료 면제 조건, 금리변동, 인지대·보증료와 신규 상품의 조건은 금융기관 약정서를 최종 기준으로 확인하세요.",
    sections: [
      { heading: "중도상환 전에 정리할 숫자", paragraphs: ["남은 원금, 남은 기간, 현재 적용금리, 상환방식과 수수료율을 먼저 확인합니다. 대출 잔액만으로는 앞으로 낼 이자와 수수료를 비교할 수 없습니다.", "중도상환수수료 계산기는 입력한 잔액과 수수료율에 따른 예상 수수료를 보여주며, 대출 이자 계산기로 남은 이자와 함께 비교할 수 있습니다."] },
      { heading: "갈아타기 비용까지 포함하기", paragraphs: ["새 대출의 설정·보증·인지 관련 비용, 우대금리 조건과 변동금리 위험을 함께 적습니다. 월 납입액이 줄어도 총비용이 늘어날 수 있습니다."] },
    ],
    faq: [
      { question: "중도상환수수료가 없으면 무조건 갈아타는 것이 유리한가요?", answer: "아닙니다. 신규 대출 비용, 금리 유형, 남은 기간과 현금흐름을 함께 비교해야 합니다." },
      { question: "계산기 결과가 은행의 실제 수수료와 다른 이유는 무엇인가요?", answer: "약정별 면제기간, 일할 계산, 상환일과 상품 조건이 계산기의 단순 가정과 다를 수 있기 때문입니다." },
    ],
    relatedToolSlugs: ["early-repayment-fee", "loan-interest", "loan-amortization"],
    relatedGuideSlugs: ["loan-interest-comparison-guide", "jeonse-loan-interest-guide"],
    monetizationCategory: "finance",
  },
  {
    slug: "jeonse-loan-interest-guide",
    title: "전세대출 이자 계산과 월 부담 비교 방법",
    description: "전세보증금·대출금리·대출비율을 기준으로 월 이자와 실제 주거비를 비교하는 방법입니다.",
    eyebrow: "REAL ESTATE FINANCE GUIDE",
    intro: "전세 계약의 월 부담은 월세가 없다는 이유만으로 0원이 아닙니다. 전세대출 이자와 자기자본의 기회비용, 보증료와 관리비를 함께 확인해야 합니다.",
    coreAnswer: "전세대출 월 부담은 대출원금과 금리로 계산한 이자에 보증료·관리비·자기자본 비용을 별도로 더해 비교해야 합니다.",
    example: "전세보증금과 대출금액·금리를 전세대출 이자 계산기에 입력한 뒤 전세와 월세 비용 비교 가이드에서 같은 기간의 총비용을 비교하세요.",
    caution: "대출한도·보증기관·금리조건·보증료와 실제 승인 여부는 개인 조건과 상품별 심사에 따라 달라질 수 있습니다.",
    sections: [
      { heading: "전세대출 월 부담의 구성", paragraphs: ["대출이자는 대출원금과 금리에 따라 달라지고, 보증료·관리비·이사비·자기자본의 기회비용은 별도 항목입니다. 계약기간 전체를 같은 기준으로 정리하세요.", "전세대출 이자 계산기는 입력한 대출금액과 금리로 월·연간 이자를 추정하는 출발점입니다."] },
      { heading: "월세와 비교할 때 같은 조건 쓰기", paragraphs: ["월세 보증금, 월세, 전세보증금과 대출금리를 같은 거주기간으로 맞추어 비교합니다. 금리 상승 시나리오도 별도로 확인하면 안전합니다."] },
    ],
    faq: [
      { question: "전세대출 이자만 월세와 비교해도 되나요?", answer: "보증료·관리비·자기자본 비용과 갱신·이사 비용까지 목적에 맞게 포함해야 더 현실적인 비교가 됩니다." },
      { question: "전세대출 금리는 고정으로 계산하나요?", answer: "계산기는 입력 금리를 기준으로 합니다. 변동금리 상품은 금리 상승 시나리오를 따로 계산하세요." },
    ],
    relatedToolSlugs: ["jeonse-loan-interest", "loan-interest", "jeonse-vs-monthly"],
    relatedGuideSlugs: ["jeonse-vs-monthly-cost-guide", "early-repayment-fee-guide"],
    monetizationCategory: "real-estate",
  },
  {
    slug: "home-acquisition-tax-guide",
    title: "주택 취득세 계산 전 확인할 거래금액·주택수·감면 조건",
    description: "주택을 매수할 때 취득세 계산에 필요한 거래금액과 주택수, 적용 조건을 정리하고 계산기로 연결합니다.",
    eyebrow: "REAL ESTATE TAX GUIDE",
    intro: "취득세는 매매가만 입력하면 끝나는 세금이 아닙니다. 주택 유형과 보유 주택수, 취득 시점과 감면·중과 적용 여부를 함께 확인해야 합니다.",
    coreAnswer: "취득세는 거래금액에 세율을 단순 적용하기 전에 주택수·지역·취득 유형과 최신 적용 기준을 확인해야 합니다.",
    example: "매매금액과 주택 유형을 취득세 계산기에 입력한 뒤 중개보수·대출이자·등기비용을 별도 항목으로 더해 총 취득비용을 추정하세요.",
    caution: "세율·중과·감면 기준은 정책과 사실관계에 따라 달라질 수 있으므로 신고 전 지방자치단체와 최신 공식 기준을 확인하세요.",
    sections: [
      { heading: "취득세 입력 전에 확인할 항목", paragraphs: ["매매가, 주택 유형, 조정대상 여부, 보유 주택수, 취득 원인과 감면 대상 여부를 체크합니다. 계산기에 없는 조건은 결과에 반영되지 않을 수 있습니다.", "취득세 계산기는 기본 입력값에 따른 참고 세액을 보여줍니다."] },
      { heading: "취득세 외 부대비용도 함께 보기", paragraphs: ["중개보수, 법무·등기비, 대출 관련 비용, 이사비와 수리비는 취득세와 별도입니다. 주택 구매 예산을 잡을 때 총액으로 관리하세요."] },
    ],
    faq: [
      { question: "취득세 계산 결과가 신고세액과 다를 수 있나요?", answer: "주택수·감면·중과·취득 유형과 적용 시점이 다르면 결과가 달라질 수 있습니다. 공식 신고 안내를 최종 기준으로 보세요." },
      { question: "취득세만 준비하면 주택 구매비용이 충분한가요?", answer: "아닙니다. 중개보수·등기·대출·이사·수리 등 거래 부대비용을 별도로 준비해야 합니다." },
    ],
    relatedToolSlugs: ["acquisition-tax", "brokerage-fee", "loan-interest"],
    relatedGuideSlugs: ["real-estate-brokerage-fee-guide", "jeonse-loan-interest-guide"],
    monetizationCategory: "tax",
  },
  {
    slug: "property-tax-guide",
    title: "재산세 계산과 주택 보유비용을 월 단위로 보는 방법",
    description: "주택 보유 시 재산세와 공시가격·과세표준의 관계를 이해하고 연간 비용을 월 부담으로 비교합니다.",
    eyebrow: "REAL ESTATE TAX GUIDE",
    intro: "주택 보유비용을 비교할 때 재산세는 연간 고정비로 보고, 관리비·대출이자·보험료와 함께 월 환산하면 현금흐름을 파악하기 쉽습니다.",
    coreAnswer: "재산세는 계산기의 참고값과 실제 고지서를 구분하고, 연간 세금을 월 환산해 대출이자·관리비와 함께 비교해야 합니다.",
    example: "주택 가격·보유 조건을 재산세 계산기에 입력하고 연간 결과를 12개월로 나눈 뒤 월세·대출이자와 비교하세요.",
    caution: "공시가격·과세표준·세율과 감면·세부담상한 적용은 시점과 개인 조건에 따라 달라질 수 있습니다.",
    sections: [
      { heading: "재산세와 주택 가격은 같은 숫자가 아니다", paragraphs: ["재산세 계산은 단순한 시세 곱셈이 아니라 과세 기준과 적용 조건을 사용합니다. 계산 전 어떤 가격·기준을 입력하는지 확인하세요.", "계산 결과는 예산 계획을 위한 참고값이며 실제 고지서와 다를 수 있습니다."] },
      { heading: "보유비용을 월 현금흐름으로 합산하기", paragraphs: ["재산세 외에 대출이자, 관리비, 보험료, 수선비와 주차비를 연간 또는 월간 기준으로 맞춥니다. 임대수익이 있다면 공실·수선비도 별도로 고려하세요."] },
    ],
    faq: [
      { question: "재산세는 매달 내는 세금인가요?", answer: "일반적으로 고지·납부 시기와 방식이 정해져 있으므로 연간 부담액을 월 예산에 나누어 적립하는 방식으로 관리할 수 있습니다." },
      { question: "계산기로 실제 고지세액을 확정할 수 있나요?", answer: "아닙니다. 실제 고지서는 과세 기준과 감면·상한 적용 여부를 포함하므로 공식 고지서와 기관 안내를 확인해야 합니다." },
    ],
    relatedToolSlugs: ["property-tax", "monthly-budget", "loan-interest"],
    relatedGuideSlugs: ["home-acquisition-tax-guide", "jeonse-vs-monthly-cost-guide"],
    monetizationCategory: "real-estate",
  },
  {
    slug: "capital-gains-tax-cost-guide",
    title: "양도소득세 계산에서 필요경비와 실제 수익률을 함께 보는 법",
    description: "부동산·자산 매도 시 양도가액·취득가액·필요경비와 세금을 구분해 순수익을 추정하는 방법입니다.",
    eyebrow: "TAX & RETURN GUIDE",
    intro: "매도가에서 취득가를 뺀 금액이 그대로 이익은 아닙니다. 취득·양도 관련 비용과 세금, 보유기간을 구분해 순수익을 계산해야 합니다.",
    coreAnswer: "양도 관련 순수익은 매도가에서 취득가·인정 가능한 비용·세금을 구분해 차감한 뒤 보유기간과 함께 해석해야 합니다.",
    example: "매입·매도금액과 비용을 수익률 계산기에 넣고 양도소득세 계산기의 참고값과 비교해 세전·세후 결과를 나누어 확인하세요.",
    caution: "필요경비 인정 여부, 보유·거주기간, 주택수와 적용 세율은 자산 유형과 시점에 따라 달라질 수 있으므로 신고 전 전문가·공식 안내를 확인하세요.",
    sections: [
      { heading: "세전 차익과 세후 순수익 구분하기", paragraphs: ["매도가에서 취득가를 뺀 금액은 단순 차익입니다. 중개보수·수리·취득 관련 비용 중 인정 범위와 세금을 구분해야 실제 손에 남는 금액을 추정할 수 있습니다.", "수익률 계산기는 비용을 반영한 단순 순손익 비교에 활용하고, 세금 계산기는 별도 참고값으로 보세요."] },
      { heading: "필요경비 자료를 미리 보관하기", paragraphs: ["계약서, 영수증, 중개보수와 수리비 증빙은 비용 인정 여부 확인에 필요할 수 있습니다. 거래가 끝난 뒤 자료를 찾기보다 취득·보유·양도 단계별로 보관하세요."] },
    ],
    faq: [
      { question: "수익률 계산기 결과가 양수면 세후 이익인가요?", answer: "아닙니다. 수익률 계산기는 입력한 비용 기준의 단순 결과이며 실제 세금과 신고 요건은 별도로 확인해야 합니다." },
      { question: "모든 수리비가 필요경비로 인정되나요?", answer: "비용의 성격과 증빙, 자산 유형에 따라 다를 수 있습니다. 신고 전 최신 공식 기준과 전문가 확인이 필요합니다." },
    ],
    relatedToolSlugs: ["capital-gains-tax", "return-rate", "brokerage-fee"],
    relatedGuideSlugs: ["home-acquisition-tax-guide", "real-estate-brokerage-fee-guide"],
    monetizationCategory: "tax",
  },
  {
    slug: "year-end-tax-refund-guide",
    title: "연말정산 환급액을 미리 계산할 때 확인할 공제 항목",
    description: "총급여·원천징수·공제항목을 기준으로 연말정산 환급 또는 추가납부를 추정하는 순서를 설명합니다.",
    eyebrow: "SALARY & TAX GUIDE",
    intro: "연말정산 결과는 월급에서 이미 낸 세금과 최종 공제·세액공제를 비교해 결정됩니다. 환급을 기대하기 전에 어떤 금액이 입력되었는지 확인해야 합니다.",
    coreAnswer: "환급액은 총급여만으로 결정되지 않고 원천징수액과 공제·세액공제 자료를 함께 입력해야 추정할 수 있습니다.",
    example: "연간 급여와 원천징수액, 주요 공제 항목을 연말정산 환급 계산기에 입력한 뒤 연봉 실수령액과 별도로 결과를 확인하세요.",
    caution: "공제 요건과 한도, 부양가족·주거·교육·의료비 자료는 귀속연도별 기준과 증빙을 확인해야 합니다.",
    sections: [
      { heading: "환급과 추가납부의 기본 구조", paragraphs: ["매월 원천징수한 세금과 연간 최종 세액을 비교해 환급 또는 추가납부가 결정됩니다. 월급 실수령액과 연말정산 결과는 서로 다른 계산입니다.", "계산기는 입력한 공제 가정에 따른 참고 결과만 제공합니다."] },
      { heading: "공제자료를 입력할 때 빠뜨리기 쉬운 항목", paragraphs: ["부양가족 요건, 보험·의료·교육비, 주택 관련 공제와 기부금 등은 증빙과 적용요건이 함께 필요합니다. 금액만 입력하지 말고 자격 요건을 확인하세요."] },
    ],
    faq: [
      { question: "환급액이 크면 세금을 많이 낸 것인가요?", answer: "환급은 이미 낸 원천징수액과 최종 세액의 차이입니다. 환급액만으로 실제 세금 부담을 판단할 수는 없습니다." },
      { question: "계산기 결과를 회사 정산액으로 사용해도 되나요?", answer: "아닙니다. 회사의 원천징수 자료와 귀속연도별 공제 요건, 국세청 간소화 자료를 최종 확인하세요." },
    ],
    relatedToolSlugs: ["year-end-tax-refund", "annual-net", "monthly-take-home"],
    relatedGuideSlugs: ["annual-net-pay-guide", "four-insurance-payroll-guide"],
    monetizationCategory: "tax",
  },
  {
    slug: "comprehensive-income-tax-business-guide",
    title: "사업자 종합소득세 계산 전 매출·경비·이익 정리하기",
    description: "사업자 종합소득세를 이해하기 위해 매출·필요경비·사업소득과 세전 이익을 구분하는 방법을 안내합니다.",
    eyebrow: "BUSINESS TAX GUIDE",
    intro: "사업자의 세금은 매출 전체에 단순 세율을 곱하는 방식으로 이해하기 어렵습니다. 매출과 필요경비, 사업소득과 다른 소득을 구분해야 계산 결과를 해석할 수 있습니다.",
    coreAnswer: "종합소득세를 추정하려면 매출과 비용을 먼저 분리하고, 비용의 인정 여부와 다른 소득을 별도로 확인해야 합니다.",
    example: "예상 매출과 경비를 종합소득세 계산기에 입력하고 마진율·손익분기점 계산기로 세금 전 사업이익을 먼저 교차 확인하세요.",
    caution: "장부·증빙·업종·신고유형·공제와 세액공제에 따라 실제 세액이 달라질 수 있으므로 신고 전 세무 전문가와 공식 안내를 확인하세요.",
    sections: [
      { heading: "매출과 사업비용을 분리하기", paragraphs: ["매출은 입금액과 신고 기준이 다를 수 있고, 비용도 사업 관련성·증빙·인정 범위를 확인해야 합니다. 플랫폼 수수료와 광고비는 별도 항목으로 기록하세요.", "종합소득세 계산기는 입력한 소득과 공제 가정의 참고 결과입니다."] },
      { heading: "세금 전 이익과 현금흐름 구분하기", paragraphs: ["매출이 발생해도 카드 입금 시차, 재고 구매, 부가세 납부와 대출 상환 때문에 현금이 부족할 수 있습니다. 손익과 현금흐름을 별도로 관리하세요."] },
    ],
    faq: [
      { question: "매출에서 비용을 빼면 바로 과세표준인가요?", answer: "사업 형태와 신고·공제 구조에 따라 추가로 확인할 항목이 있을 수 있습니다. 계산기는 단순 참고용입니다." },
      { question: "광고비와 플랫폼 수수료를 경비로 넣어도 되나요?", answer: "사업 관련성·증빙·적용 기준에 따라 달라질 수 있으므로 관련 자료를 보관하고 전문가 또는 공식 기준을 확인하세요." },
    ],
    relatedToolSlugs: ["comprehensive-income-tax", "margin", "break-even"],
    relatedGuideSlugs: ["small-business-roas-margin-guide", "small-business-fixed-cost-guide"],
    monetizationCategory: "business",
  },
  {
    slug: "deposit-savings-comparison-guide",
    title: "예금과 적금 만기수령액 비교: 금리보다 납입방식이 중요한 이유",
    description: "예치금과 월 납입액, 기간·금리를 기준으로 예금과 적금의 예상 이자와 만기수령액을 비교합니다.",
    eyebrow: "FINANCE GUIDE",
    intro: "예금과 적금은 같은 금리를 표시해도 돈이 계좌에 머무는 방식이 달라 이자 결과가 다릅니다. 총 납입액과 납입 시점을 맞춰 비교해야 합니다.",
    coreAnswer: "예금은 목돈을 한 번에 예치하고 적금은 나누어 납입하므로 같은 표시금리라도 실제 이자와 만기금액이 달라집니다.",
    example: "예치금과 기간·금리를 예금 계산기에 입력하고, 월 납입액과 납입기간을 적금 계산기에 넣어 세전·세후 결과를 비교하세요.",
    caution: "우대금리 조건, 이자소득 과세, 중도해지 이율과 납입일에 따라 실제 수령액이 달라질 수 있습니다.",
    sections: [
      { heading: "예금과 적금의 돈이 머무는 기간", paragraphs: ["예금은 처음부터 목돈 전체에 이자가 붙는 반면 적금은 납입된 금액마다 이자가 붙는 기간이 다릅니다. 표시금리만 비교하지 마세요.", "예금·적금 계산기로 동일한 기간과 총 납입 가능액을 기준으로 만기수령액을 비교하세요."] },
      { heading: "세전 이자와 실제 수령액 구분하기", paragraphs: ["계산 결과의 이자와 만기금액이 세전인지 확인합니다. 상품별 과세·우대조건·중도해지 조건은 상품설명서를 최종 기준으로 봅니다."] },
    ],
    faq: [
      { question: "적금 금리가 더 높으면 항상 적금이 유리한가요?", answer: "납입 방식과 기간, 총 납입 가능액, 세금과 우대조건을 같은 기준으로 비교해야 합니다." },
      { question: "중도해지하면 계산기 결과를 받을 수 있나요?", answer: "계산기는 약정 조건의 예상치입니다. 중도해지 이율은 상품별로 다르므로 상품설명서를 확인하세요." },
    ],
    relatedToolSlugs: ["deposit-interest", "savings", "savings-goal"],
    relatedGuideSlugs: ["retirement-fund-how-much-guide", "annual-net-pay-guide"],
    monetizationCategory: "finance",
  },
  {
    slug: "platform-fee-margin-guide",
    title: "플랫폼 수수료를 반영한 판매 마진과 순이익 계산",
    description: "판매가·원가·결제·플랫폼 수수료·배송비를 반영해 상품별 실제 마진을 계산하는 방법입니다.",
    eyebrow: "BUSINESS GUIDE",
    intro: "판매가에서 원가만 빼면 플랫폼에서 실제로 남는 금액을 알기 어렵습니다. 결제수수료·플랫폼 수수료·배송비·쿠폰 비용을 주문 단위로 함께 계산해야 합니다.",
    coreAnswer: "상품 순이익은 판매가에서 원가와 주문에 직접 발생한 수수료·배송·할인비를 차감한 금액으로 비교해야 합니다.",
    example: "판매가와 원가를 마진율 계산기에 입력하고 플랫폼 수수료·광고비를 ROAS 계산기에서 별도로 반영해 주문당 이익을 확인하세요.",
    caution: "수수료가 부가세 포함인지, 광고비가 주문별인지 캠페인별인지, 반품·쿠폰 비용을 포함하는지 기준을 통일해야 합니다.",
    sections: [
      { heading: "판매가와 원가만으로 부족한 이유", paragraphs: ["플랫폼·결제·PG 수수료, 배송비, 포장비, 쿠폰과 반품비는 판매가와 원가 사이에서 실제 이익을 줄입니다. 고정비는 주문당 배분 기준을 별도로 정하세요.", "마진율 계산기는 판매가와 원가 관계를, ROAS 계산기는 광고비를 포함한 광고 후 이익을 확인하는 데 사용합니다."] },
      { heading: "상품별 순이익 표 만들기", paragraphs: ["상품별로 판매가·원가·수수료율·고정 배송비·광고비 배분을 같은 단위로 기록하면 채널별 수익성을 비교하기 쉬워집니다."] },
    ],
    faq: [
      { question: "마진율이 높으면 광고를 늘려도 되나요?", answer: "광고비와 반품·배송·고정비를 차감한 후에도 이익이 남는지 확인해야 합니다. 마진율 하나만으로 판단하지 마세요." },
      { question: "플랫폼 수수료는 판매가에 곱하면 되나요?", answer: "수수료의 과세·배송비 포함 여부와 계약 기준에 따라 달라질 수 있으므로 실제 정산서를 기준으로 입력 기준을 정하세요." },
    ],
    relatedToolSlugs: ["margin", "roas", "break-even"],
    relatedGuideSlugs: ["small-business-roas-margin-guide", "roas-break-even-guide"],
    monetizationCategory: "business",
  },
  {
    slug: "national-pension-retirement-gap-guide",
    title: "국민연금 예상액과 은퇴 후 부족 생활비 계산 방법",
    description: "국민연금 예상수령액과 은퇴 생활비의 차이를 계산해 필요한 추가 은퇴자금을 추정합니다.",
    eyebrow: "RETIREMENT GUIDE",
    intro: "국민연금 예상액은 은퇴 후 현금흐름의 한 부분입니다. 예상 생활비와 지급 시기, 다른 연금·자산을 같은 월 기준으로 맞추면 부족자금을 추정할 수 있습니다.",
    coreAnswer: "은퇴 후 부족 생활비는 예상 월 생활비에서 국민연금과 다른 확정 수입을 뺀 금액으로 시작해 기간·물가·수익률 가정을 더해 추정합니다.",
    example: "국민연금 예상수령액 계산기와 은퇴자금 계산기에 각각 입력한 뒤, 지급 개시 시점이 다른 연금은 기간별로 나누어 비교하세요.",
    caution: "연금 예상액은 가입기록·지급시기·물가와 제도 기준에 따라 달라질 수 있으므로 공식 조회 결과를 최종 기준으로 확인하세요.",
    sections: [
      { heading: "연금 수입과 생활비를 같은 단위로 맞추기", paragraphs: ["월 생활비를 주거·의료·식비·여가로 나누고 국민연금·퇴직연금·개인연금의 월 수입과 지급 시기를 정리합니다. 세전·세후 기준도 구분하세요.", "국민연금 계산기와 은퇴자금 계산기를 함께 사용하면 부족액과 추가 준비액을 비교할 수 있습니다."] },
      { heading: "부족액을 하나의 숫자로 단정하지 않기", paragraphs: ["은퇴기간, 물가, 수익률과 의료비 가정을 보수적·기준·낙관 시나리오로 나누어 결과 범위를 확인하세요."] },
    ],
    faq: [
      { question: "국민연금 예상액만으로 은퇴준비가 끝나나요?", answer: "주거비·의료비·수명·지급시기와 다른 자산을 함께 확인해야 합니다. 계산기는 부족액 추정용 참고 도구입니다." },
      { question: "연금 예상액은 세후로 입력해야 하나요?", answer: "계산 목적에 맞게 세전·세후 기준을 통일하고, 실제 수령 조건은 공식 조회 결과와 상품·제도 안내를 확인하세요." },
    ],
    relatedToolSlugs: ["national-pension", "retirement-fund", "monthly-budget"],
    relatedGuideSlugs: ["pension-retirement-income-guide", "retirement-fund-how-much-guide"],
    monetizationCategory: "retirement",
  },
];

export function getGuideContent(slug: string) { return guideContents.find((item) => item.slug === slug); }
export function getGuidePath(slug: string) { return `/guides/${slug}`; }
